### ISSUE TITLE
qTox crashes 1-2 times a day after update to 0.2.4

### ISSUE THREAD

**Issue by yurivict** [TokTok/c-toxcore#1028]
I am a maintainer of the qTox port on FreeBSD. The user reported that he sees qTox crashing 1-2 times a day.
Both qTox and toxcore were recently updated. The only difference with my own installation - I didn't have toxcore updated, and he did.

**Comment by nurupo** [comment]
Sounds similar to https://github.com/TokTok/c-toxcore/issues/1004, which was fixed with https://github.com/TokTok/c-toxcore/pull/1008. The fix is in c-toxcore v0.2.4. Is v0.2.4 crashing too?

**Comment by yurivict** [comment]
This user has 0.2.4.

**Comment by iphydf** [comment]
Does the user have a stack trace?

**Comment by iphydf** [comment]
Can you reproduce this?

**Comment by VVD** [comment]
Work fine for me: qTox 1.16.3, toxcore 0.2.4, Qt 5.10.1, FreeBSD 11.2 amd64.
@yurivict, did he recompile both qTox and toxcore?
And can you write PR number in FreeBSD's bugtracker?

**Comment by yurivict** [comment]
Closing for now.

**Comment by nurupo** [comment]
Any reasoning for closing?

**Comment by yurivict** [comment]
It looks like a random crash, no other users complained.

**Comment by VVD** [comment]
Possible it's hardware issue?

**Comment by yurivict** [comment]
I thought mostly that this user had a bad build, or a hardware issue, or some other random thing. I use qTox on the same type of system without problems, except 2 regressions with warnings that I've reported. No crashes, and no other user reports.
