### ISSUE TITLE
Random numbers should not be produced using `rng() % max`.

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#1040]
Modulus creates a bias towards smaller numbers.

**Comment by iphydf** [comment]
We need a `uint32_t random_range(uint32_t min, uint32_t max);` and replace the uses of random-modulo with it.

**Comment by JFreegman** [comment]
Libsodium's `randombytes_uniform` should be used https://libsodium.gitbook.io/doc/generating_random_data

**Comment by robinlinden** [comment]
Fixed in #1975.
