### ISSUE TITLE
Sometimes Toxcore reports the wrong connection status for both the DHT, and friends.

### ISSUE THREAD

**Issue by GrayHatter** [TokTok/c-toxcore#106]
@cleverca22 has given me a pcap dump that caught this bug which may or may not be helpful when dx this bug.

**Comment by cleverca22** [comment]
i believe i was running toxcore e1089c1779fb1c58f17937108a6ba8c3d39573ae at the time

**Comment by GrayHatter** [comment]
> e1089c1 was commited Nov 2015

http://i.imgur.com/djTuIN6.gif

**Comment by iphydf** [comment]
@cleverca22 this is possibly fixed now. Can you check?

**Comment by iphydf** [comment]
No response for almost 2 years, I'm considering it fixed.

**Comment by JFreegman** [comment]
This was probably fixed a couple months ago with https://github.com/TokTok/c-toxcore/commit/c0a0a8204c9c9046ef3b543155b735b31b31ae13 and https://github.com/TokTok/c-toxcore/commit/8b725c1ecc2c77215353e9005ae53da2f308dce1
