### ISSUE TITLE
Add empty handler for LAN discovery packets when LAN discovery is disabled

### ISSUE THREAD

**Issue by anthonybilinski** [TokTok/c-toxcore#1115]
Running 76f4ae64b7e2b20ff39806bbe248eb89116e365f I periodically see
`Warning: "WARN :network.c:networking_poll:654: [33] -- Packet has no handler"`
in the logs. I see it on multiple networks and computers.

There are no observable effects.

**Comment by zugz** [comment]
It seems this packet is handled iff local discovery is enabled in the 
tox options. Possibly we should register a null handler for it when 
local discovery in disabled, just to avoid this warning?

Did you have another tox running which might be producing these packets?

**Comment by sudden6** [comment]
That this happens when two Toxes are running on the same computer with LAN discovery disabled on one and enabled on the other.

**Comment by anthonybilinski** [comment]
I have two Tox instances on my network, my own with LAN discovery disabled, and a tox-bootstrapd instance with LAN discovery disabled.

Stopping the tox-bootstrapd instance stops the log generation, so I guess its config isn't working correctly.

>Possibly we should register a null handler for it when local discovery in disabled

This seems reasonable to me.
