### ISSUE TITLE
Message length is too large log spam

### ISSUE THREAD

**Issue by anthonybilinski** [TokTok/c-toxcore#1116]
Seems to be when bootstrapping, I see multiple warning logs:
```
Warning: "ERROR:Messenger.c:m_send_message_generic:508: Message length 1374 is too large"
core/toxlogger.cpp:57 : Warning: "ERROR:Messenger.c:m_send_message_generic:508: Message length 1378 is too large"
core/toxlogger.cpp:57 : Warning: "ERROR:Messenger.c:m_send_message_generic:508: Message length 1378 is too large"
core/toxlogger.cpp:57 : Warning: "ERROR:Messenger.c:m_send_message_generic:508: Message length 1378 is too large"
core/core.cpp:374 : Debug: "Connecting to node.tox.biribiri.org:33445 (nurupo)"                     
```

No observable client, bootstrapping succeeds.

**Comment by zugz** [comment]
Looks like a client bug. m_send_message_generic is called only by the 
api function tox_friend_send_message, which as is documented in the api 
may only be called with a message of length at most 1372.

**Comment by anthonybilinski** [comment]
This is a bug in qTox. It looks like the history in one of my profiles had a message that was too long, which it was trying to send on start without splitting the message since that's supposed to be done when added to history.
