### ISSUE TITLE
Fix threading issues in tests caught by tsan (data race etc)

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#1118]
See the tsan circle ci build. We have some data races and broken lock handling.

**Comment by hugbubby** [comment]
What does the tsan build test for that wasn't being looked at?

**Comment by iphydf** [comment]
It tests for data races, deadlocks, etc. All kinds of threading issues. The code happens to work, but it's probably undefined behaviour.

**Comment by hugbubby** [comment]
Forks in what, though? The tox creation process?

**Comment by iphydf** [comment]
There are currently no threading issues. TSAN is a blocking check on CI.
