### ISSUE TITLE
Data Race failures?

### ISSUE THREAD

**Issue by hugbubby** [TokTok/c-toxcore#1159]
There are a ton of failed tests with multiple different commits complaining about data race failures in the toxav_many test, across many pull requests. These tests seem to sometimes fail and sometimes not. What's going on? Did we accidentally let in a bad commit?

**Comment by hugbubby** [comment]
Duplicate of  #1118, I will attempt to see what the problem is

**Comment by iphydf** [comment]
It has probably been broken forever, but we never caught it because we only recently added the tsan build.
