### ISSUE TITLE
NGC: Update spec on New Group Chats to account for changes done to get TCP working

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#1167]
Assignee: @ingvar1995 (once invitation accepted)

* Ensure [DHT-Group-Chats.md](https://github.com/ingvar1995/toxcore/blob/ngc_rebase/docs/DHT-Group-Chats.md) is accurate and up to date.
* Modify [spec.md](https://github.com/TokTok/spec/blob/master/spec.md) (or the LaTeX source in [Tox.lhs](https://github.com/TokTok/hs-toxcore/blob/master/src/tox/Network/Tox.lhs), if you prefer) to reflect the changes to the core protocol (e.g. changes to announce).

**Comment by JFreegman** [comment]
Done
