### ISSUE TITLE
NGC: Make `struct Group_Chat_Self_Peer_Info` private.

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#1179]
Currently, `Group_Chat_Self_Peer_Info` is a public struct, exposed in the tox.h API. This makes its ABI fixed, and we can never add new fields to it until 0.4.0.

Also, don't use `const char *` for the nick field. We use byte arrays for all strings in toxcore except ones that go to C library functions for DNS lookup.

**Comment by JFreegman** [comment]
This struct no longer exists
