### ISSUE TITLE
NGC: Disentangle util and DHT modules

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#1182]
The `util` module now depends on the `DHT` module and vice versa. The dependency edge should be only `DHT -> util`. The only reason for this dependency is some numeric constants from `DHT.h`.

**Comment by algor1th** [comment]
DHT.h appears in neither util.c nor util.h. Does this mean the issue is resolved?

**Comment by sudden6** [comment]
Good catch
