### ISSUE TITLE
NGC: Make events "const", i.e. remove the userdata parameter.

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#1185]
Userdata should come from `tox_iterate`, so none of the group callbacks should have their own user data. Today, the user data parameter is already ignored, so we should get rid of it properly.

**Comment by crypto-universe** [comment]
Looks like an easy task. Can you clarify the scope (files, functions to clear)?

**Comment by crypto-universe** [comment]
As I can see, all events are already const.

**Comment by iphydf** [comment]
They are in master, but not in NGC, i.e. #1170 (https://github.com/iphydf/c-toxcore/tree/ngc-rebased-master).

**Comment by crypto-universe** [comment]
Shall we close this issue?
