### ISSUE TITLE
Windows cross-compilation is broken

### ISSUE THREAD

**Issue by nurupo** [TokTok/c-toxcore#1201]
Looks like #1191 broke Windows cross-compilation builds, even though we tried our best not to break them.

https://travis-ci.org/TokTok/c-toxcore/builds/432322743

```
Scanning dependencies of target random_testing
make[2]: *** No rule to make target 'sodium_LIBRARY_RELEASE-NOTFOUND', needed by 'random_testing.exe'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target 'sodium_LIBRARY_RELEASE-NOTFOUND', needed by 'auto_file_saving_test.exe'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

**Comment by nurupo** [comment]
Alright, so here is a summary of what is going on. CMake tries to find a shared library first.

https://github.com/TokTok/c-toxcore/blob/f87f8719d02a9adbc9413256fe22958267cfefee/cmake/Dependencies.cmake#L26-L28

Then it checks if `sodium` target exists, under the assumption that the target not existing means that the static libsodium was not found. If the static libsodium was not found, it tries to find a static libsodium.

https://github.com/TokTok/c-toxcore/blob/f87f8719d02a9adbc9413256fe22958267cfefee/cmake/Dependencies.cmake#L29-L32

Our Windows builds use static libsodium, so you'd expect the first `find_package(sodium)` to fail, the if-condition evaluate to True and then the second `find_package(sodium)` to succeed. However, what is happening is that the if-condition is always false, as **`/cmake/Findsodium.cmake` always creates the `sodium` target, no matter if it failed to find the library or not**.

https://github.com/TokTok/c-toxcore/blob/f87f8719d02a9adbc9413256fe22958267cfefee/cmake/Findsodium.cmake#L251

The proper way to check if shared libsodium was not found would be

```cmake
if (NOT sodium_FOUND)
```

instead of checking if `sodium` target was created.

(Interestingly enough, @sphaerophoria [did write the proper check the first time around, but then changed it to the broken one because the proper one was causing issues on Ubuntu 14.04 for them](https://github.com/TokTok/c-toxcore/pull/1191#issuecomment-423707860).)

However, this proper check exposes another issue, while the the second `find_package(sodium)` call does properly find the static libsodium, it errors out when trying to create the `sodium` target, because it already exists, created by the first `find_package(sodium)` call:

```
-- Could NOT find sodium (missing:  sodium_LIBRARY_RELEASE sodium_LIBRARY_DEBUG) 
-- Found sodium: /root/prefix/i686/lib/libsodium.a  
CMake Error at cmake/Findsodium.cmake:251 (add_library):
  add_library cannot create imported target "sodium" because another target
  with the same name already exists.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:31 (find_package)
  CMakeLists.txt:123 (include)
```
 
This situation with `/cmake/Findsodium.cmake` is a mess, it doesn't support being called multiple times, which is what we need in order to emulate the previous behavior of searching for shared libsodium and then falling back to static. We should either fix `/cmake/Findsodium.cmake` or revert f87f8719d02a9adbc9413256fe22958267cfefee.

**Comment by nurupo** [comment]
This inconsistency in fallback on Linux and Windows is annoying, opened the issue with Findsodium.cmake's upstream https://github.com/jedisct1/libsodium/issues/757 just so they know about it.

**Comment by sphaerophoria** [comment]
ill roll back the change tonight
