### ISSUE TITLE
Links to binaries

### ISSUE THREAD

**Issue by redmanmale** [TokTok/c-toxcore#1232]
In README link **Binaries/Downloads** leads to the [empty page](https://wiki.tox.chat/Binaries) which leads to the [Tox.chat downloading page](https://tox.chat/download.html) and there are not any ToxCore binaries.

The only working binaries I found are at the [Compiling page](https://github.com/TokTok/c-toxcore/blob/master/INSTALL.md#pre-built-binaries).

> Debian and Ubuntu packages are available in tox.chat's package repository.

But that's not true, there's no more package repository.

Moreover, there's no more up-to-date Debian packages at all.

**Comment by iphydf** [comment]
Binaries are working now.
