### ISSUE TITLE
lib on system:

### ISSUE THREAD

**Issue by letarg0** [TokTok/c-toxcore#1237]
Haiku OS
Solaris
QNX
OpenVMS

is possible to check, compiling?

**Comment by iphydf** [comment]
Haiku: sure, I'm all for it.
Solaris: we already do (I don't know if it works right now, but we have a port that I test on Solaris).
QNX: possible.
OpenVMS: unlikely, but you can try?

**Comment by xor256** [comment]
the question is, what system using my interlocutor (friend)
this is important

**Comment by letarg0** [comment]
yes
