### ISSUE TITLE
NGC: Ensure that all group chats callbacks correctly pass user data

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#1265]
* Get rid of [global state](https://github.com/iphydf/c-toxcore/blob/ngc-rebased-master/auto_tests/group_message_test.c#L60) in tests.
* Get rid of all [userdata pointers](https://github.com/iphydf/c-toxcore/blob/ngc-rebased-master/toxcore/group_chats.h#L338) in group chats.
* Get rid of [non_const_user_data](https://github.com/iphydf/c-toxcore/blob/ngc-rebased-master/toxcore/tox.c#L85).
* Ensure that the [user_data](https://github.com/iphydf/c-toxcore/blob/ngc-rebased-master/toxcore/tox.c#L942) in tox_iterate is passed down to all the group chat callbacks.

**Comment by crypto-universe** [comment]
@iphydf so instead of switch-case with handlers you suggest to call all gc handlers one by one? Strange decision to be honest. A lot of useless work will be done in places like [this](https://github.com/iphydf/c-toxcore/blob/ngc-rebased-master/toxcore/Messenger.c#L2822).

**Comment by JFreegman** [comment]
I believe this is all done now
