### ISSUE TITLE
Toxcore should provide an easy, local method for making sure Travis checks will pass

### ISSUE THREAD

**Issue by GrayHatter** [TokTok/c-toxcore#128]
something like  `make commit` which will run the apidsl, style, direct decendant of current (local?) master, and other misc checks that Travis does.

**Comment by nurupo** [comment]
Throw some docker at it.

**Comment by iphydf** [comment]
`make test` does the apidsl and style checks (`format_test`). Travis does not check whether the branch is up to date (perhaps it should?). How would you suggest we implement that check? The way I see it could work would involve `git fetch $toktok_repo` (where toktok repo would be inferred from `git remote -v`), which modifies the user's git repository. I'm not sure that's acceptable. Is there a different/better way?

**Comment by GrayHatter** [comment]
```
git remote add toktok ...
git checkout toktok/master
git merge -ff-only $BRANCH || CATCH FAILURE HERE
```

**Comment by sudden6** [comment]
you might be interested in the way we do it for qTox, [merge-pr.sh](https://github.com/qTox/qTox/blob/master/merge-pr.sh) and [test-pr.sh](https://github.com/qTox/qTox/blob/master/test-pr.sh) for merging and testing PRs. There we create separate branches for things to merge.

**Comment by nbraud** [comment]
Without running any code that modifies the repo:
```
if [ -n "$(git show -q HEAD..toktok/master)" ]; then
    echo "Non fast-forward merge" >&2
    exit 1
fi
```

In general, I don't think that
