### ISSUE TITLE
How to make libtox4j-c.so for android?

### ISSUE THREAD

**Issue by 1971192997** [TokTok/c-toxcore#1298]
I try to make the libtox4j-c.so and the .jar,but failed,can you tell me how to do that ?

**Comment by zoff99** [comment]
@1971192997 you can see the commands here:

https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/dev003/circle.yml

**Comment by 1971192997** [comment]
@zoff99 thanks , get it done
