### ISSUE TITLE
I need a full list of dependencies.

### ISSUE THREAD

**Issue by ghost** [TokTok/c-toxcore#1301]
At FreeBSD's ports https://www.freshports.org/net-im/tox/ I find that latest Toxcore release depends on libsndfile, msgpack, check, portaudio and GNU version of test(1) found in GNU coreutils. But hey! Why you didn't list that at https://github.com/TokTok/c-toxcore/blob/master/INSTALL.md ?

**Comment by mazocomp** [comment]
Wow, that's google test actually, I should contact thierry@freebsd.org

**Comment by mazocomp** [comment]
So, as I understand, check is no longer a dependency, but libsndfile, msgpack, portaudio and gtest are test dependencies. Trying to run tests makes me stuck in infinite loop at OpenBSD, that can't be helped, I won't provide them as test dependencies in port then.

**Comment by iphydf** [comment]
This is done.
