### ISSUE TITLE
Loaded persistent groups fail to send audio

### ISSUE THREAD

**Issue by anthonybilinski** [TokTok/c-toxcore#1303]
From https://github.com/qTox/qTox/issues/5509.
After loading a persistent group, attempting to send audio always results in `toxav_group_send_audio` returning -1. New groups still work properly.

**Comment by zugz** [comment]
Given the discussion in #1304, I think the correct immediate solution to 
this is just for clients to understand that an audio group which exists 
at startup will not accept audio, i.e. toxav_group_send_audio will fail. 
Nor will it do anything with audio received on the group - which makes 
sense as the client can't set an audio callback for the group.

Currently there's no way to enable audio except by the user leaving and 
rejoining the group. But #1304 suggests an API change to make it 
possible.

**Comment by anthonybilinski** [comment]
>Currently there's no way to enable audio except by the user leaving and rejoining the group.

Is there some way for a client to craft an invite for itself or something? Or would it require a user to manually quit the group and get a new invite from a friend each time? If it's the second, that's a pretty big limitation for persistent groups especially since the workaround is so non-obvious to users :(

**Comment by zugz** [comment]
* Friday, 2019-01-25 at 09:01 +0000 - Anthony Bilinski <notifications@github.com>:

>Is there some way for a client to craft an invite for itself or 
>something?

I don't think so, sadly. Until this is sorted in core, clients might 
even want to just kill any audio group which exists at startup. But the 
fix I proposed should be easy to implement, if I'm not missing anything, 
so hopefully will be available to clients before long. I'll start 
working on it.

**Comment by zugz** [comment]
This is fixed in #1305, which adds a toxav API function 
toxav_groupchat_enable_av which clients can call to enable audio on audio 
groups loaded from save.
