### ISSUE TITLE
Onion client review

### ISSUE THREAD

**Issue by kurnevsky** [TokTok/c-toxcore#1312]
I think I found few problems in onion client implementation. But I'd like someone to confirm it:

- https://github.com/TokTok/c-toxcore/blob/d14989f6dffedc8bc402afc2a503f72f8546fde6/toxcore/onion_client.c#L1586

It seems it should be `or` instead of `and`. Otherwise there is no much sense in the second condition - we can ping a node, don't get a response and stop pings since this one node was pinged recently.

- https://github.com/TokTok/c-toxcore/blob/d14989f6dffedc8bc402afc2a503f72f8546fde6/toxcore/onion_client.c#L1711

The condition here should be `list_nodes[i].unsuccessful_pings == 0 || list_nodes[i].unsuccessful_pings == 1 && mono_time_is_timeout(onion_c->mono_time, list_nodes[i].last_pinged, ONION_NODE_TIMEOUT)`. The same with the next condition.

- https://github.com/TokTok/c-toxcore/blob/d14989f6dffedc8bc402afc2a503f72f8546fde6/toxcore/onion_client.c#L1721

It should be for all nodes instead of just the current one, like in `do_friend`. Otherwise each node will be pinged at the rate `ONION_NODE_PING_INTERVAL + MAX_ONION_CLIENTS_ANNOUNCE*3` maximum since `do_announce` executes every 3 seconds.

**Comment by zugz** [comment]
* Wednesday, 2019-03-20 at 14:10 -0700 - Evgeny Kurnevsky <notifications@github.com>:

>- https://github.com/TokTok/c-toxcore/blob/d14989f6dffedc8bc402afc2a503f72f8546fde6/toxcore/onion_client.c#L1586
>
>It seems it should be `or` instead of `and`. Otherwise there is no much 
>sense in the second condition - we can ping a node, don't get 
>a response and stop pings since this one node was pinged recently.

I believe "and" is intended. It prevents this ping balancing mechanism 
from producing excess pings, in particular when `interval` is small.

>- https://github.com/TokTok/c-toxcore/blob/d14989f6dffedc8bc402afc2a503f72f8546fde6/toxcore/onion_client.c#L1711
>
>The condition here should be `list_nodes[i].unsuccessful_pings == 0 || list_nodes[i].unsuccessful_pings == 1 && mono_time_is_timeout(onion_c->mono_time, list_nodes[i].last_pinged, ONION_NODE_TIMEOUT)`. The same with the next condition.

Why?

>- https://github.com/TokTok/c-toxcore/blob/d14989f6dffedc8bc402afc2a503f72f8546fde6/toxcore/onion_client.c#L1721
>
>It should be for all nodes instead of just the current one, like in 
>`do_friend`. Otherwise each node will be pinged at the rate 
>`ONION_NODE_PING_INTERVAL + MAX_ONION_CLIENTS_ANNOUNCE*3` maximum since 
>`do_announce` executes every 3 seconds.

I'm not sure what you mean here. This mechanism ensures we at least send 
one ping per ONION_NODE_PING_INTERVAL seconds. Note that last_announce 
gets set each time.

**Comment by kurnevsky** [comment]
> I believe "and" is intended. It prevents this ping balancing mechanism from producing excess pings, in particular when `interval` is small.

This condition is used only for `ping_random`, i.e. to check if we should ping one random node now. It doesn't depend on current `interval`. Also comment says:
```
// ensure we get a response from some node roughly once per
// (interval / MAX_ONION_CLIENTS)
```
But imagine that we sent a ping and the node didn't respond. In this case we won't ping some node again because of the first condition. Which means we won't get a response for `interval / MAX_ONION_CLIENTS` and will wait for another `ONION_NODE_PING_INTERVAL`.

> Why?

This condition should check if node is alive and 'stable'. But what if it didn't respond last time? In this case it becomes 'unstable', we send another ping request and consider it 'stable' again for another `ONION_NODE_TIMEOUT` second which is not right, even if it's dead.

> I'm not sure what you mean here. This mechanism ensures we at least send one ping per ONION_NODE_PING_INTERVAL seconds. Note that last_announce gets set each time.

Right, but this check executes every 3 seconds for each node independently. It means that regardless of how big interval is it will likely be pinged after some time. The worst probability is `1 - (1 - 1/MAX_ONION_CLIENTS_ANNOUNCE)^n` (if we ignore `i`), which is ~0.9 for 90 seconds. So it means that each node will be pinged every 90 seconds with high probability regardless of interval. So instead of checking this condition for every node independently we should check it for all nodes, like we do in `do_friend`. This way after one node was pinged we won't ping other nodes.

**Comment by zugz** [comment]
* Saturday, 2019-03-23 at 03:11 -0700 - Evgeny Kurnevsky <notifications@github.com>:

>> I believe "and" is intended. It prevents this ping balancing mechanism from producing excess pings, in particular when `interval` is small.
>
>This condition is used only for `ping_random`, i.e. to check if we should ping one random node now. It doesn't depend on current `interval`. Also comment says:
>```
>// ensure we get a response from some node roughly once per
>// (interval / MAX_ONION_CLIENTS)
>```
>But imagine that we sent a ping and the node didn't respond. In this 
>case we won't ping some node again because of the first condition. 
>Which means we won't get a response for `interval / MAX_ONION_CLIENTS` 
>and will wait for another `ONION_NODE_PING_INTERVAL`.

Correct. Perhaps the comment is misleading (though the word "roughly" 
could be understood as covering this).

If we do want to make many pings in quick succession in this 
circumstance, it looks like we'd want a separate mechanism to do it. 
Changing the && to || isn't what we want - it would mean we ping at 
least once per ONION_NODE_PING_INTERVAL, which may be a lot faster than 
`interval` asks for.

>> Why?
>
>This condition should check if node is alive and 'stable'. But what if 
>it didn't respond last time? In this case it becomes 'unstable', we 
>send another ping request and consider it 'stable' again for another 
>`ONION_NODE_TIMEOUT` second which is not right, even if it's dead.

Yes, we give it another chance to prove its stability. Maybe "stable" 
isn't the best word here... but I'm not sure what's better, and the 
current behaviour seems to make sense.

Considering a node as unstable if we've sent more than one unsuccessful 
ping might make some sense with the way pings are currently sent, but it 
doesn't make sense for the paths since we might well send multiple pings 
in quick succession on the same path. It seems good to keep the two 
parallel.

>> I'm not sure what you mean here. This mechanism ensures we at least 
>> send one ping per ONION_NODE_PING_INTERVAL seconds. Note that 
>> last_announce gets set each time.
>
>Right, but this check executes every 3 seconds for each node 
>independently. It means that regardless of how big interval is it will 
>likely be pinged after some time. The worst probability is `1 - (1 
>- 1/MAX_ONION_CLIENTS_ANNOUNCE)^n` (if we ignore `i`),

Don't ignore i! The test is
```random_u32() % (MAX_ONION_CLIENTS_ANNOUNCE - i) == 0```
and since i ranges up to MAX_ONION_CLIENTS_ANNOUNCE-1
(ignoring the exceptional case that some nodes are timed out, which is 
quickly dealt with),
this means that one node, chosen uniformly, does get pinged if 
last_announce was at least ONION_PING_INTERVAL ago.

So if there were no other pinging, this would cause each node to be 
pinged on average once per 
ONION_PING_INTERVAL*MAX_ONION_CLIENTS_ANNOUNCE seconds, which as it 
happens is exactly ANNOUNCE_INTERVAL_STABLE.

Or am I missing something?


>which is ~0.9 for 90 seconds. So it means that each node will be pinged 
>every 90 seconds with high probability regardless of interval. So 
>instead of checking this condition for every node independently we 
>should check it for all nodes, like we do in `do_friend`. This way 
>after one node was pinged we won't ping other nodes.

**Comment by kurnevsky** [comment]
> Correct. Perhaps the comment is misleading (though the word "roughly" could be understood as covering this). If we do want to make many pings in quick succession in this circumstance, it looks like we'd want a separate mechanism to do it. Changing the && to || isn't what we want - it would mean we ping at least once per ONION_NODE_PING_INTERVAL, which may be a lot faster than `interval` asks for.

I thought it was supposed to provide reliable friends searching on big ping intervals when nodes/paths can become invalid. But ok, this makes sense because with no response we will try to ping nodes every `ONION_NODE_PING_INTERVAL`.

> Yes, we give it another chance to prove its stability. Maybe "stable" isn't the best word here... but I'm not sure what's better, and the current behaviour seems to make sense.

ok then. Anyway it shouldn't be a big deal.

> So if there were no other pinging, this would cause each node to be pinged on average once per ONION_PING_INTERVAL*MAX_ONION_CLIENTS_ANNOUNCE seconds, which as it happens is exactly ANNOUNCE_INTERVAL_STABLE.

Ah, I missed the fact that `last_announce` is global for all nodes. It's fine then.

So I guess the issue can be closed. Thanks!
