### ISSUE TITLE
NGC: propose to change packet structure.

### ISSUE THREAD

**Issue by NamsooCho** [TokTok/c-toxcore#1317]
There is `password` field in many packets, for example `Invite request`
```
Serialized form:

Length      | Content
----------- | ------
`1`         | `0x5b`
`4`         | `hash id`
`32`        | `PK of sender`
`24`        | `nonce`
`1`         | `0xf6`(packet kind: invite request)
`8`         | `message id`
`4`         | `sender pk hash`
`2`         | `length`(of nickname)
variable    | `nickname` of length `length`(UTF-8 string)
`32`        | `password`(comes only when password is setted)
```
When we parse this packet we need to check if we used password.
If yes then sender would append password to packet, if not there would be no password.
I think this scheme may cause inconsistency between peers.
I suggest to insert flag to indicate the password is included or not.
This would permit us to parse packet only using packet itself, without checking other variable.

**Comment by JFreegman** [comment]
All packets that include a password now have a length field preceding the password. However the length field is still only included if a password is set. There should be no inconsistencies between peers. The flag you're looking for is implicit in whether or not the length field is set, which can be determined by the size of the payload.

See the updated packet spec here: https://github.com/JFreegman/toxcore/blob/ngc_jf/docs/DHT_Group_Chats_Packet_Spec.md
