### ISSUE TITLE
Question: ETA of v0.2.10?

### ISSUE THREAD

**Issue by Hasshu** [TokTok/c-toxcore#1325]
> **Closed** 11 days ago

What gives?

**Comment by sudden6** [comment]
A draft is already available at: https://github.com/TokTok/c-toxcore/releases I think it's just a formality for the final release now.

**Comment by Hasshu** [comment]
Ah, good. I hope that qTox is finally going to see an update soon.

**Comment by robinlinden** [comment]
Yeah, sorry about that. I was counting on the review going through before I left for my vacation and forgot to reopen the milestone after generating the changelog.

**Comment by Hasshu** [comment]
@robinlinden No worries.
