### ISSUE TITLE
the cause is great, but this thing is completely unusable

### ISSUE THREAD

**Issue by ruxtain** [TokTok/c-toxcore#1326]
my android app gets stuck all the time. and I can't send friend request. and my mac's app can't send request either...

**Comment by ruxtain** [comment]
Great thanks for trying anyway..

**Comment by zoff99** [comment]
@ruxtain what android app do you use? Antox has not been in active development for years.
please try it with TRIfA on f-droid store

**Comment by ruxtain** [comment]
ok.. thanks.
