### ISSUE TITLE
Load-test new group chats: determine a rough maximum group size

### ISSUE THREAD

**Issue by zhuzhenlongn** [TokTok/c-toxcore#1327]
When I create a group，I can invite some friends into my group， but I don't know the most count of friends I can Invite.  Can you tell me how many friends Tox can support?

**Comment by zugz** [comment]
* Tuesday, 2019-07-02 at 01:53 -0700 - zhuzhenlong <notifications@github.com>:

>When I create a group，I can invite some friends into my group， but 
>I don't know the most count of friends I can Invite.  Can you tell me 
>how many friends Tox can support?

There's no particular theoretical limit. However, very large groups 
might not work as well. The time for a message to propagate throughout 
the group is proportional to the size of the group. There's also 
a chance that random churn will mean a message fails to propagate to the 
whole group -- that requires a failure at two independent locations in 
the ring which the group forms, so the probability is roughly 
proportional to the square of the size of the group. I'm not sure how 
big the group would have to be before this is a real problem. 

Back-of-the-envelope estimate: assuming a connection goes down on 
average once per hour and the connection isn't replaced for 30 seconds, 
so a given link is down 1/120 of the time, so some neighbouring pair is 
down about N/(120^2) of the time, so two such are down about 
(N/(120^2))^2 of the time, if the size N of the group is 120^2/10 = 1440 
then messages will fail to fully propagate roughly 1% of the time. 
I don't know how accurate the numbers going into that calculation were, 
but it sounds reasonable that groups with thousands of peers will be 
flaky.

**Comment by zhuzhenlongn** [comment]
Thank you very much, Your answer is very detailed. When I use toxcore in my project,  I want to know toxcore some performance indicators about group chat. May you provide some or Where I can get it.

**Comment by zugz** [comment]
* Wednesday, 2019-07-03 at 01:04 -0700 - zhuzhenlong <notifications@github.com>:

>Thank you very much, Your answer is very detailed. When I use toxcore 
>in my project,  I want to know toxcore some performance indicators 
>about group chat. May you provide some or Where I can get it.

If you're asking for statistics on how well large groups work, as far as 
I know we have nothing like that. If you're asking for ways to tell how 
well a large group is performing, I guess the key things to check are 
speed and reliability of message propagation.

**Comment by iphydf** [comment]
Might be worth documenting something like this somewhere, maybe in the spec?

**Comment by JFreegman** [comment]
I'm not sure how we could specify this since it would depend on the hardware and available bandwidth of every peer

**Comment by iphydf** [comment]
Probably not in the spec, but we can do some testing and put it into the PR description for NGC.

**Comment by iphydf** [comment]
Let's leave this be for now. We'll load test it together by chatting in a big group.
