### ISSUE TITLE
Padding bytes in Tox save format are not specified

### ISSUE THREAD

**Issue by sudden6** [TokTok/c-toxcore#1332]
In https://toktok.ltd/spec.html#friends-0x03 there are some bytes marked as `PADDING`, should they be zero or are they unspecified on purpose?

The current code assumes `PADDING` means zeroed via this line: https://github.com/TokTok/c-toxcore/blob/master/toxcore/Messenger.c#L3066 at least in debug build.

**Comment by sudden6** [comment]
#1333 changes c-toxcore to accept any byte as padding, but I'm not 100% sure this is the best way.

**Comment by iphydf** [comment]
Is this resolved now?

**Comment by sudden6** [comment]
I guess, the code now no longer checks the value of bytes marked as `PADDING`.
