### ISSUE TITLE
Join to group chat over group chat id

### ISSUE THREAD

**Issue by whoizit** [TokTok/c-toxcore#1337]
Is it possible to join a chat without an invite, using only group chat id?

**Comment by zugz** [comment]
* Saturday, 2019-08-17 at 06:03 -0700 - whoami <notifications@github.com>:

>Is it possible to join a chat without an invite using only group chat id?

No.

**Comment by iphydf** [comment]
DHT-based group chats will allow this.

**Comment by satotaku-dev** [comment]
Why was the group-chat architecture changed in a way that breaks interoperability with existing public groups?
Is backward compatibility with the existing by-ID public-group join mechanism possible?

**Comment by Green-Sky** [comment]
DHT based group chats are fundamentally different, intercompatibility makes no sense.

**Comment by JFreegman** [comment]
> Why was the group-chat architecture changed in a way that breaks interoperability with existing public groups? Is backward compatibility with the existing by-ID public-group join mechanism possible?

They're two completely separate implementations. We call the old implementation "conferences", and the new ones "group chats". The old ones work exactly as they always did.
