### ISSUE TITLE
return NULL when call tox_new()function

### ISSUE THREAD

**Issue by letmestudy** [TokTok/c-toxcore#1348]
i am using toktok toxcore,the version is 2.9.0,when i call the tox_new(NULL,&err) to get the tox obj,it return NULL,and the err is TOX_ERR_NEW_PORT_ALLOC,i don't know why.  
    this code can running on windows,so i compile it in linux,but it not work,
    is there anybody can reslove the problem?thanks.

**Comment by zoff99** [comment]
@letmestudy can you link to your full sourcecode please?

**Comment by letmestudy** [comment]
thanks for your response,i resloved the problem,the point is in "struct Tox_Options",it can't enable ipv6 option.it works when i disabled it.

**Comment by crypto-universe** [comment]
@letmestudy can we close the issue?
