### ISSUE TITLE
libtoxdns.a and libtoxav.a

### ISSUE THREAD

**Issue by username1565** [TokTok/c-toxcore#1353]
Hello. I'm try to compile old versions of utox, but got fail.
I see here, in this [`BUILD.md`](https://github.com/uTox/uTox/blob/develop/docs/BUILD.md#cygwin-setup)
the following package: toxcore ([x86](https://build.tox.chat/view/libtoxcore/job/libtoxcore-toktok_build_windows_x86_static_release/lastSuccessfulBuild/artifact/libtoxcore-toktok_build_windows_x86_static_release.zip)/x64),
and there is inside that [libtoxcore-toktok_build_windows_x86_static_release.zip](https://github.com/TokTok/c-toxcore/files/3831341/libtoxcore-toktok_build_windows_x86_static_release.zip)

,
I can see the following files:
```
\lib\libvpx.a
\lib\libopus.a
\lib\libopus.la
\lib\libsodium.a
\lib\libsodium.la
\lib\libtoxcore.a
```
But compiler return me an error, because `libtoxdns.a` and `libtoxav.a`, and compilation is terminated:
```
user@COMPUTER /cygdrive/c/projects/notsecure/utox
$ sh tools/cross-compile-windows.sh -32 win
Building 32bit version of uTox
Building from a ~Unix environment within windows
fatal: Not a git repository (or any parent up to mount point /cygdrive/c)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Git version: fatal: Not a git repository (or any parent up to mount point /cygdrive/c)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
i686-w64-mingw32-gcc: error: ./lib/toxcore/lib/libtoxdns.a: No such file or directory
i686-w64-mingw32-gcc: error: ./lib/toxcore/lib/libtoxav.a: No such file or directory
```

How to get `libtoxdns.a` and `libtoxav.a`? Can you compile it and attach it here, please?

**Comment by robinlinden** [comment]
If you want to build an old version of uTox you have to build an old version of Toxcore which isn't really recommended. toxdns was deleted in 2c8fb05f6e1631403053ef8648d5860e0ec15cc3 and the toxav library was merged into the toxcore one in f2b6090eca42f4a364ef7517c5eec6d472e9b5f6, so something before then might work.

Again, really not recommended. You should probably build the latest version of uTox against the latest version of Toxcore since it appears that uTox still has Windows XP support.

**Comment by username1565** [comment]
No, I would prefer to use old versions while maintaining the maximum backward compatibility. Because a many people continue to communicate and do not want to update software or equipment at the whim of newly-minted programmers.

After this all, I'll be glad to download venom_win32 from 2014 year: https://habr.com/ru/post/212029/
and working with this and devoping this, just because all new versions not working correcly on Windows XP, and cann't be compiled there!

**Comment by iphydf** [comment]
It's fairly straightforward to change utox build system to stop looking for toxdns and toxav, but the old version is likely not compatible with the API of toxcore 0.2.x. It should be possible to get toxcore 0.1.x to build with utox, though.

We are not planning to continue to support client versions from 6 years ago.
