### ISSUE TITLE
Unstable Tests

### ISSUE THREAD

**Issue by sudden6** [TokTok/c-toxcore#1354]
Currently 2-3 CirrusCI tests are very unstable and often fail.

It seems that Cirrus CI supports only re-running the failed tests, but our setup doesn't allow that.

I think we could speed up merging by splitting the unstable tests into their own run. Of course we still should fix the test themselves.

@robinlinden what do you think?

**Comment by robinlinden** [comment]
Yeah, I think that sounds pretty reasonable. Trying to merge things like this is unbearable. Either coveralls fails to report coverage and that blocks it or one of our unstable tests fails and that blocks it.
