### ISSUE TITLE
sudo systemctl start tox-bootstrapd.service failed

### ISSUE THREAD

**Issue by lxb325710** [TokTok/c-toxcore#1359]
● tox-bootstrapd.service - Tox DHT Bootstrap Daemon
   Loaded: loaded (/etc/systemd/system/tox-bootstrapd.service; enabled; vendor preset
   Active: failed (Result: exit-code) since Mon 2019-11-25 16:46:46 CST; 14s ago
  Process: 6212 ExecStart=/usr/local/bin/tox-bootstrapd --config /etc/tox-bootstrapd.

Nov 25 16:46:46 localhost systemd[1]: Starting Tox DHT Bootstrap Daemon...
Nov 25 16:46:46 localhost systemd[1]: tox-bootstrapd.service: Control process exited,
Nov 25 16:46:46 localhost systemd[1]: Failed to start Tox DHT Bootstrap Daemon.
Nov 25 16:46:46 localhost systemd[1]: tox-bootstrapd.service: Unit entered failed sta
Nov 25 16:46:46 localhost systemd[1]: tox-bootstrapd.service: Failed with result 'exi

**Comment by anthonybilinski** [comment]
Could you post the logs from the last run, viewable from `# journalctl -u tox-bootstrapd`

**Comment by lxb325710** [comment]
> 您能否发布上次运行的日志，可从 `# journalctl -u tox-bootstrapd`


-- Logs begin at Mon 2019-11-25 16:38:20 CST, end at Mon 2019-11-25 18:06:35 CST. --
Nov 25 16:38:24 localhost systemd[1]: Starting Tox DHT Bootstrap Daemon...
Nov 25 16:38:24 localhost systemd[1]: tox-bootstrapd.service: Control process exited, code=exited status=203
Nov 25 16:38:24 localhost systemd[1]: Failed to start Tox DHT Bootstrap Daemon.
Nov 25 16:38:24 localhost systemd[1]: tox-bootstrapd.service: Unit entered failed state.
Nov 25 16:38:24 localhost systemd[1]: tox-bootstrapd.service: Failed with result 'exit-code'.
Nov 25 16:46:41 localhost systemd[1]: Starting Tox DHT Bootstrap Daemon...
Nov 25 16:46:41 localhost systemd[1]: tox-bootstrapd.service: Control process exited, code=exited status=203
Nov 25 16:46:41 localhost systemd[1]: Failed to start Tox DHT Bootstrap Daemon.
Nov 25 16:46:41 localhost systemd[1]: tox-bootstrapd.service: Unit entered failed state.
Nov 25 16:46:41 localhost systemd[1]: tox-bootstrapd.service: Failed with result 'exit-code'.
Nov 25 16:46:46 localhost systemd[1]: Starting Tox DHT Bootstrap Daemon...
Nov 25 16:46:46 localhost systemd[1]: tox-bootstrapd.service: Control process exited, code=exited status=203
Nov 25 16:46:46 localhost systemd[1]: Failed to start Tox DHT Bootstrap Daemon.
Nov 25 16:46:46 localhost systemd[1]: tox-bootstrapd.service: Unit entered failed state.
Nov 25 16:46:46 localhost systemd[1]: tox-bootstrapd.service: Failed with result 'exit-code'.
Nov 25 18:05:56 localhost systemd[1]: Starting Tox DHT Bootstrap Daemon...
Nov 25 18:05:56 localhost systemd[1]: tox-bootstrapd.service: Control process exited, code=exited status=203
Nov 25 18:05:56 localhost systemd[1]: Failed to start Tox DHT Bootstrap Daemon.
Nov 25 18:05:56 localhost systemd[1]: tox-bootstrapd.service: Unit entered failed state.
Nov 25 18:05:56 localhost systemd[1]: tox-bootstrapd.service: Failed with result 'exit-code'.

**Comment by nurupo** [comment]
Huh, tox-bootstrapd didn't output anything in the log. It could be that the binary is failing to start due to the linker not knowing that tox libraries got installed.

What's the output of:
```
ldd /usr/local/bin/tox-bootstrapd
```

and

```
/usr/local/bin/tox-bootstrapd --help
```
?

**Comment by nurupo** [comment]
No reply? Anyway, if it's what I think then a simple

```
sudo ldconfig
```

will update the dynamic linker's cache, fixing the issue of `tox-bootstrapd` not being able to start.
