### ISSUE TITLE
Add the option to use LAN discovery even when using a proxy for remote connections

### ISSUE THREAD

**Issue by wuniversales** [TokTok/c-toxcore#1365]
Why disable the local use of the application when activating a proxy?
I honestly do not understand why.
I think it is useful to be able to use the proxy only for internet connections.

**Comment by iphydf** [comment]
It might be tricky to get right, because we need to be very careful not to send any packets to nodes outside the LAN.

**Comment by zoff99** [comment]
what is the local LAN?
netmasks vary. also local LAN can be your internet.
this is very dangerous IMHO
