### ISSUE TITLE
Generate a link for websites (Friendship and proxy)

### ISSUE THREAD

**Issue by wuniversales** [TokTok/c-toxcore#1366]
I think it would be useful to generate a link to add a friend request, by clicking on a website.
For example:

`<a href="tox://BD1A5F4E7933F10F6980A8469FC617AF4C3B9C0F8EC5BCE1C0C5274E2E4F3B07E3430F9ADF5W">Send friend request to Tox </a>`

You could also this function to add a proxy in applications.
For example:

`<a href="tox://proxy?type=socks5&server=213.136.89.190&port=14500">Add Proxy to Tox </a>`

**Comment by anthonybilinski** [comment]
Linking back to https://github.com/qTox/qTox/issues/5970, I think this is more a client issue.
