### ISSUE TITLE
Changelog is unaccessible

### ISSUE THREAD

**Issue by lamuguo** [TokTok/c-toxcore#1367]
https://toktok.ltd/changelog/c-toxcore.html, it introduces to an error page, I assume. Would you kindly fix it? Thanks!

**Comment by robinlinden** [comment]
That page should have roughly the same information as https://github.com/TokTok/c-toxcore/blob/master/CHANGELOG.md if you just want to read the changelog. 

The error itself is probably Heroku having issues when the toktok.ltd website was last generated. The changelog endpoint is still up, so regenerating it should be enough. (No idea how to trigger that without merging something though.)

**Comment by lamuguo** [comment]
Nice. Please close the issue when the regenerating is run.

Thanks!
