### ISSUE TITLE
0.2.11 doesn't install toxav and toxencryptsave

### ISSUE THREAD

**Issue by yurivict** [TokTok/c-toxcore#1410]
The source tree contains ```toxcore/libtoxcore.pc.in```, but the FreeBSD port only installs the ```toxav``` header ```/usr/local/include/tox/toxav.h```, and not corresponding libraries and .pc file.

Similar thing happens with the ```toxencryptsave``` - only the header is installed: ```/usr/local/include/tox/toxencryptsave.h```.

qTox fails to find these modules:
```
-- Checking for one of the modules 'toxav'
-- TOXAV not found
-- Checking for one of the modules 'toxencryptsave'
-- TOXENCRYPTSAVE not found
```

**Comment by iphydf** [comment]
Did this change between 0.2.10 and 0.2.11? I thought we had changed that a long time ago (but then 0.2.10 is also a long time ago).
