### ISSUE TITLE
Toxcore needs a CHANGELOG

### ISSUE THREAD

**Issue by GrayHatter** [TokTok/c-toxcore#149]
I don't think it needs to be updated every commit, but every once in a while I'd like something rolled into an existing pull.

**Comment by zetok** [comment]
https://github.com/clog-tool/clog-cli
https://github.com/qTox/qTox/blob/master/verify-commit-messages.sh

**Comment by GrayHatter** [comment]
retracted per IRC comment, we just need more commits per changes

**Comment by zetok** [comment]
>retracted per IRC comment, we just need more commits per changes

Good luck with that.

Aternative: https://github.com/saschagrunert/git-journal#git-journal-

Offers automated git hooks.

https://github.com/saschagrunert/git-journal/blob/master/rfc/0001-commit-msg.md#example-commit-message

Reopen?
