### ISSUE TITLE
EPOLLHUP undeclared

### ISSUE THREAD

**Issue by pineapple4321** [TokTok/c-toxcore#1554]
I cannot build the driver. "make" gives me many error messages of the type

error: ‘EPOLLHUP’ undeclared
error: ‘EPOLLWRNORM’ undeclared
error: ‘EPOLLIN’ undeclared
and a few more of that type.

I am using OpenSuse Linux Leap 15.1. Kernel sources are installed. Current update 
installed.
I am a private user and I want to control USB measurement devices e.g. an arbitrary 
waveform generator. I also tried it in a more direct way with a new group 'usbtmc' and a file 
usbtmc.rules in /etc/udev/rules.d/ but I did not succeed. Could you give me any help?

Regards Werner

**Comment by iphydf** [comment]
I think you got the wrong repository there. We [don't have any EPOLLWRNORM](https://github.com/irungentoo/toxcore/search?q=EPOLLWRNORM&unscoped_q=EPOLLWRNORM) in our codebase.
