### ISSUE TITLE
ERROR:  heap-buffer-overflow in group.c found with AddressSanitizer

### ISSUE THREAD

**Issue by peirick** [TokTok/c-toxcore#1598]
In `group.c` in method  `handle_message_packet_group` the variable `index` can change if message is `GROUP_MESSAGE_KILL_PEER_ID` see:

https://github.com/TokTok/c-toxcore/blob/03a511482ffa643a636cd5bcce596f110ca2d8e0/toxcore/group.c#L2695

At the end of the method `index` is pointing to an eventually deleted entry:
https://github.com/TokTok/c-toxcore/blob/03a511482ffa643a636cd5bcce596f110ca2d8e0/toxcore/group.c#L2764

**Comment by iphydf** [comment]
peirick: can you reproduce this in a test case? See https://github.com/TokTok/c-toxcore/tree/master/auto_tests (`conference_*test.c`) for examples.

**Comment by peirick** [comment]
Sorry no. Tests are expensive to write. A simple fix would be to move the lines 

https://github.com/TokTok/c-toxcore/blob/03a511482ffa643a636cd5bcce596f110ca2d8e0/toxcore/group.c#L2758-L2764

above 

https://github.com/TokTok/c-toxcore/blob/03a511482ffa643a636cd5bcce596f110ca2d8e0/toxcore/group.c#L2666

Kind regards

**Comment by iphydf** [comment]
Thanks, what situation would this occur in, so I can write the test?

**Comment by peirick** [comment]
Given two peers in a group. A and B
A is first online, B comes later online.
B goes offline first.

flow:

GROUP_MESSAGE_KILL_PEER_ID or GROUP_MESSAGE_FREEZE_PEER_ID is send. 
`peer_number` resolves to `index` of last added peer in group.

`delpeer` / `freeze_peer` is called. Because `index` is the last peer `realloc` on `g->group` is called. Thus Memory to that group is invalid. 

After call to `delpeer` invalid memory on `g->group[index]` is accessed to set `relay_back` .
