### ISSUE TITLE
where can i get offlineMessenger Bot Sourcecode

### ISSUE THREAD

**Issue by AmerRaza** [TokTok/c-toxcore#1631]

**Comment by nurupo** [comment]
What is Offline Messenger Bot?

**Comment by AmerRaza** [comment]
is this not part of https://github.com/InsightIM/Tok-Android

**Comment by nurupo** [comment]
Don't know anything about it, you will have to ask Tok-Android's developers for the source. toxcore doesn't support offline messaging and has no such bot service.
