### ISSUE TITLE
Error: memset in client_or_ip_port_in_list in DHT.c

### ISSUE THREAD

**Issue by zgfzgf** [TokTok/c-toxcore#1648]
/* Initialize client timestamp. */
    assoc->timestamp = temp_time;
    memcpy(list[index].public_key, public_key, CRYPTO_PUBLIC_KEY_SIZE);

    LOGGER_DEBUG(log, "coipil[%u]: switching public_key (ipv%d)", index, ip_version);

    /* kill the other address, if it was set */
    memset(assoc, 0, sizeof(IPPTsPng));   // ERROR Should be corresponding
    ip_version is 4     memset list[index].assoc6
    ip_version is 6     memset list[index].assoc4  

2017 DHT.c : 91e3eb01  old code
if (ip_port.ip.family == AF_INET) {
        /* Initialize client timestamp. */
        list[index].assoc4.timestamp = temp_time;
        memcpy(list[index].public_key, public_key, CRYPTO_PUBLIC_KEY_SIZE);

        LOGGER_DEBUG(log, "coipil[%u]: switching public_key (ipv4)", index);

        /* kill the other address, if it was set */
        memset(&list[index].assoc6, 0, sizeof(list[index].assoc6));
        return 1;
    }

    if (ip_port.ip.family == AF_INET6) {
        /* Initialize client timestamp. */
        list[index].assoc6.timestamp = temp_time;
        memcpy(list[index].public_key, public_key, CRYPTO_PUBLIC_KEY_SIZE);

        LOGGER_DEBUG(log, "coipil[%u]: switching public_key (ipv6)", index);

        /* kill the other address, if it was set */
        memset(&list[index].assoc4, 0, sizeof(list[index].assoc4));
        return 1;
    }

**Comment by zgfzgf** [comment]
DHC: f9607bce

**Comment by iphydf** [comment]
Unclear.
