### ISSUE TITLE
About groups graph topology

### ISSUE THREAD

**Issue by MyK00L** [TokTok/c-toxcore#1649]
From what i could gather without looking at the source code, ["new" group chats](https://github.com/JFreegman/toxcore/blob/new_groupchats/docs/Group-Chats.md) were implemented with a clique and [right now(?)](https://github.com/JFreegman/toxcore/blob/new_groupchats/docs/Group-Chats.md) they are implemented with a circular graph.
In the first method, the number of messages a client would have to send is linear with the group size and the maximum distance (=latency) between clients is constant, the second way has these two reversed.
While I believe the first method was better (since i think latency should cost more), i think a middle ground would be a better way.
Of course it doesn't really matter for small-ish groups, but let me propose a more scalable approach.
If every client were connected to a constant number of other clients (randomly), say 2k with k>1, while the number of clients you have to send a message to is constant, the maximum distance would almost always be logarithmic.
To achieve this, a client needs to send the message to all neighbouring clients it didn't receive the message from, which is <2k.
Another idea would have to have k be in the order log(group size), this way the number of messages a client needs to forward is logarithmic and the maximum latency is in the order of log(group size)/loglog(group size).
Either way, I don't see any benefit in having k=1 as in my understanding is the current state of group chats (sorry if I'm wrong).
The reason I say 2k and not k is because i think it would be much easier to implement, since it would be impossible in some cases when k (not doubled) is odd, and if it is even, adding a new client would be as "easy" as breaking k random edges in the graph and connecting the new client, and removing a client would need matching 2k clients.
And if this turns out to be unfeasable to do, I believe a (more) randomized approach were each client is connected to a constant >2 clients with the same properties would not be hard to implement.

**Comment by JFreegman** [comment]
>Either way, I don't see any benefit in having k=1 as in my understanding is the current state of group chats (sorry if I'm wrong).

The main benefit is that we can have a unique encryption key for each peer. With the current implementation messages can be modified by malicious relays because all peers share the same encryption key, which means message integrity can never be verified. It also makes DOS attacks trivial. The relay system only works properly when we trust every other peer. The new implementation was designed to be as trustless as possible.

**Comment by MyK00L** [comment]
Ok this makes perfect sense, I think that with my approach the attacker would need a number of clients proportional to the size of the group, but it does not make the attack unfeasable in any way.
This said, I understand how the new implementation would be the best solution, and I don't see any reason to push this issue further until maybe we see heavy performance issues with the new implementation.
