### ISSUE TITLE
Resolve compilation errors in run_afl.sh  add -DCMAKE_C_FLAGS=-fPIC

### ISSUE THREAD

**Issue by zgfzgf** [TokTok/c-toxcore#1651]
./run_afl.sh
/usr/bin/ld: libtoxcore.a(tox.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(logger.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(mono_time.c.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(network.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(state.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(DHT.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(LAN_discovery.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(ping.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(net_crypto.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(onion_client.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(friend_requests.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(Messenger.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(group.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(TCP_connection.c.o): relocation R_X86_64_32 against symbol `net_family_ipv4' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(TCP_server.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(onion.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(onion_announce.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(friend_connection.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libtoxcore.a(TCP_client.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libmisc_tools.a(misc_tools.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC

run_afl.sh
old   
cmake -DCMAKE_C_COMPILER=afl-clang -DBUILD_MISC_TESTS=ON ..
new
cmake -DCMAKE_C_COMPILER=afl-clang -DCMAKE_C_FLAGS=-fPIC -DBUILD_MISC_TESTS=ON ..

**Comment by iphydf** [comment]
This script was reworked by @sudden6.
