### ISSUE TITLE
Error: sendpacket in send_onion_response  in onion.c 

### ISSUE THREAD

**Issue by zgfzgf** [TokTok/c-toxcore#1652]
if ((uint32_t)sendpacket(net, dest, packet, SIZEOF_VLA(packet)) != SIZEOF_VLA(packet)) {
        return -1;
 }
SIZEOF_VLA(packet)) != SIZEOF_VLA(packet)  
should be: 
SIZEOF_VLA(packet))

old onion.c: d46891c3
error sizeof != sizeof 
 if ((uint32_t)sendpacket(net, dest, packet, sizeof(packet)) != sizeof(packet))

**Comment by iphydf** [comment]
I don't understand what this is saying. Feel free to make a PR with the change you propose.
