### ISSUE TITLE
tcp_relay_ports = [443, 3389, 33445] can not open 443 when not root

### ISSUE THREAD

**Issue by tux19730** [TokTok/c-toxcore#1661]
when "tox-bootstrapd" is started as no root unprivileged user it
can and will not open privileged port such as 443.
best practice is not to listen to multiple ports but to redirect
privileged ports to unprivileged ones with "iptables".
in this case a unprivileged "tox-bootstrapd" can handle
incoming requests to port 443.
example

\#!/bin/bash

\# These are iptables rules for other SSL ports
\# for tox-bootstrapd
\# tox-bootstrapd can not listen to privileged
\# ports when running as a non privileged user

\## Interface and port that tox-bootstrapd is listening on
 TOX_BOOTSTRAPD_IF=eth0
 TOX_BOOTSTRAPD_PORT=33445
\## Additional Ports that we want to use for tox-bootstrapd
 REDIRECT_PORTS="53 443 3389"

\# Port redirection
for PORT in $REDIRECT_PORTS; do
 iptables -t nat -nvL PREROUTING|grep "dpt:$PORT redir ports $TOX_BOOTSTRAPD_PORT" >/dev/null 2>&1 || \\
 iptables -t nat -I PREROUTING --src 0/0 -i ${TOX_BOOTSTRAPD_IF} -p tcp --dport $PORT -j REDIRECT --to-ports $TOX_BOOTSTRAPD_PORT
done

**Comment by nurupo** [comment]
[The README mentions](https://github.com/TokTok/c-toxcore/blob/master/other/bootstrap_daemon/README.md) that to ind to ports below 1024 you can set [`CAP_NET_BIND_SERVICE`](https://man7.org/linux/man-pages/man7/capabilities.7.html) capability either in the `.service` file or on the binary itself (which is useful if you are not using systemd), but yes, port redirection with iptables/nftables/what-have-you works too.

**Comment by whoizit** [comment]
on distro without systemd:
one-time procedure, can be used in package build script

`# setcap cap_net_bind_service+ep /usr/bin/tox-bootstrapd`
