### ISSUE TITLE
Is it real Peer-to-peer (P2P) ?

### ISSUE THREAD

**Issue by Potracheno** [TokTok/c-toxcore#1662]
I just have  done a test audio call from Russia  to Germany. Both of us have linux and run the app from "qTox-v1.17.2.x86_64.AppImage"

My ip is 176.65.119.xxx
My friend's ip s 88.198.80.xxx

We monitored traffic by iftop and saw traffic and noticed that the traffic pass through 95.31.18.227 The only software we runs was qtox.

Could you please explain why p2p traffic goes trought some other server ? And what might be the reason ?

Sorry for being paranoid ;)

**Comment by zoff99** [comment]
@VoteForNavalny that depends on if you actually see the UDP traffic.
if tox can not make a direct UDP connection between both parties, then traffic will be routes via a TCP Relay Node.
qTox does not (yet) show this clearly in the friend list.
if you both use TRIfA with WLAN and UDP setting activates, you can see the connection status in the friendlist (the outer color ring of the avatar image)

**Comment by fcore117** [comment]
It would be really good to see status of p2p in every client(qTox, uTox and so on) on future per every friend, would be good to know if sending big file would be feasible or not for example.

**Comment by iphydf** [comment]
Toxcore supports this. Clients can in principle display this, if they want to.
