### ISSUE TITLE
Const-ify pointers

### ISSUE THREAD

**Issue by nbraud** [TokTok/c-toxcore#167]
Many pointers are only set once before going out-of-scope, and could be constified.

Example at https://reviewable.io/reviews/toktok/toxcore/143#-KRuxior-8qxWa2CFtp5

**Comment by iphydf** [comment]
What's special about pointers? Why should we only const-ify pointers? I understand you mean to make the pointers themselves const, not make them pointers to const.

**Comment by nbraud** [comment]
You have a point there: there is no reason not to `const`ify things that are constantm regardless of whether they are pointers.

However, that's pretty likely a large undertaking, and starting with pointers might make sense.

**Comment by iphydf** [comment]
If we want to go forward with this, we'll need a static analysis to tell us where to add `const`. There is https://github.com/TokTok/tokstyle that aims to provide some simple checks. This would involve checking that a name is only set once, so a simple heuristic would be:

1. for each function:
  1. vars = get all variable names
  1. get all assignment operators, including the initialiser if it exists (`int i;` is not assigned, `int i = 0;` is)
  1. group assignment operators by LHS
  1. for each group:
    1. if group size greater than 1, remove LHS from vars
  1. print out all the vars remaining as diagnostic "can be `const`"

**Comment by iphydf** [comment]
Pointers-to-nonconst are more important than local variables, and have a broader impact. I've randomly found some instances of ptrs-to-nonconst that should be ptrs-to-const.

**Comment by iphydf** [comment]
This is now mostly done. There's a non-blocking check provided by sonarcube that helps us find these.
