### ISSUE TITLE
What's the difference between toxcore and toxcore_c ?

### ISSUE THREAD

**Issue by Ylhp** [TokTok/c-toxcore#1671]
Hello there,

I'm new to Tox environment, and I've seen there is a repo named toxcore and one named toxcore_c (forked from the first). And it impresses to me that both are used (for clients by example).

Why are there these two libraries ?

Thanks a lot for all the work done, it's really promising and enjoyfull ! :)

**Comment by sudden6** [comment]
What repos (URL) are you talking about?

**Comment by iphydf** [comment]
irungentoo/toxcore is mostly not used anymore.
