### ISSUE TITLE
[Missing Feature] Creating and Inviting others to a group on Tox | Inviting others to groups is currently not possibly on the GUI

### ISSUE THREAD

**Issue by life777eternal** [TokTok/c-toxcore#1680]
Hello, I just created a new group on qTox though I don't see how I can invite friends or anyone not on Tox yet, to the group. When right-clicking on a new group, there's only three (3) options. "Open chat in new window," "Set title...," & "Quit group."

Whatsapp new tos is forcing it's users to share their personal data with facebook.

Thank you.

**Comment by anthonybilinski** [comment]
Hi, first off please use https://github.com/qTox/qtox for any qTox related issues.

In qTox you can invite friends to groups by right clicking their name in the friends list, then "Invite to group" -> <group name>. Anyone not on Tox would need to be added as a friend first, by clicking the plus sign in the bottom left and using their Tox ID, which they can obtain by clicking on the avatar top left.

**Comment by life777eternal** [comment]
> Hi, first off please use https://github.com/qTox/qtox for any qTox related issues.
> 
> In qTox you can invite friends to groups by right clicking their name in the friends list, then "Invite to group" -> . Anyone not on Tox would need to be added as a friend first, by clicking the plus sign in the bottom left and using their Tox ID, which they can obtain by clicking on the avatar top left.

Hi, does that also work for inviting Contacts on Antox? Because I just tried to invite a Contact on Antox (myself on my phone) and nothing happened.


Thank you.

**Comment by zoff99** [comment]
@life777eternal Antox has not been in active development for years.
please look at the current app:
https://f-droid.org/packages/com.zoffcc.applications.trifa/
https://github.com/zoff99/ToxAndroidRefImpl/tree/zoff99/dev003

**Comment by anthonybilinski** [comment]
Tox clients are generally compatible, but I don't think Antox supports groups. Trying to create a group in Antox from the play store for me causes a "Coming soon" notification. And as Zoff mentioned, Antox hasn't been supported in years, unfortunately.

To add to zoff's advertisement of his client, there are a couple other android clients also in active development, notably:
aTox: https://github.com/evilcorpltd/atox/
Protox: https://gitlab.com/Monsterovich/protox

Though I don't think either of them support groups yet.
