### ISSUE TITLE
Get rid of TOX_USER_STATUS_BUSY + 1

### ISSUE THREAD

**Issue by nbraud** [TokTok/c-toxcore#169]
- This is an invalid value for that enum type.
- All that code will silently break when the enum datatype is changed.

Do we have similar instances of that “idiom” in the current codebase?

**Comment by pranomostro** [comment]
`ag 'TOX_[0-9A-Z_]+ \+ 1' | grep -v LENGTH` returns only one occasion where a enum member is incremented.

**Comment by nbraud** [comment]
@pranomostro Yes, and fixing it requires, as far as I can see, an API-breaking change.
I guess that's why @iphydf set the v0.2 milestone

**Comment by GrayHatter** [comment]
This is just a few lines of code to set a new default.

The question is, do we simply use STATUS_NORMAL?

Or do we want to try to handle the invalid case again?
