### ISSUE TITLE
How to use c-toxcore inside my own java tox application

### ISSUE THREAD

**Issue by ashfik2000** [TokTok/c-toxcore#1690]
I am trying to use c-toxcore inside my own java android tox application (using android studio in windows pc) by doing the following:
1- trying to call the native functions in jni-c-toxcore.c by following the instructions mentioned in https://developer.android.com/ndk/samples/sample_hellojni and https://github.com/android/ndk-samples/tree/main/hello-jniCallback
3- when building my application by android sudio i get build errors like ( tox/tox.h file not found , tox/toxav.h file not found) which is normal because these files did not exist originally in (my_app_folder/jni) folder.

So my question is : How to use c-toxcore inside my own java tox application

**Comment by robinlinden** [comment]
Unless you want to write your own Tox jni wrapper, you can use these two repositories to use c-toxcore from Java:
https://github.com/TokTok/jvm-toxcore-c
https://github.com/TokTok/jvm-toxcore-api

It's what I do in [aTox](https://github.com/evilcorpltd/aTox/). There are build scripts for them [here](https://github.com/evilcorpltd/aTox/tree/master/scripts) which publish the Tox dependencies as regular maven packages to a local repository, then you can just [depend on them](https://github.com/evilcorpltd/aTox/blob/96de8d882a5495690c68d56879cd8a748df3fb0b/domain/build.gradle.kts#L103-L104) in Gradle the normal way.

If you want to write your own jni wrapper, I started doing that [here](https://github.com/robinlinden/tox4k/tree/master/tox4k), including building c-toxcore from Gradle and all that stuff.
