### ISSUE TITLE
Feature request: ability to specify tox-bootstrapd listen address/interface

### ISSUE THREAD

**Issue by cryptogospod** [TokTok/c-toxcore#1692]
Hi, I'm a maintainer of several `tox-bootstrapd` nodes. On servers with multiple IPs, it would be very useful to have the ability to specify an address or an interface for `tox-bootstrapd` to listen on. By default, it binds to all interfaces. It would make it simpler to run multiple nodes on different interfaces, as well as manage firewall rules.

**Comment by kurnevsky** [comment]
@cryptogospod you can check our tox node written in rust: https://github.com/tox-rs/tox-node - it has this feature :)

**Comment by iphydf** [comment]
Duplicate of #259.
