### ISSUE TITLE
Double unlocking in the ac_iterate

### ISSUE THREAD

**Issue by ryancaicse** [TokTok/c-toxcore#1694]
Hi, developers, it seems there could be a double unlocking error when **!reconfigure_audio_decoder(ac, ac->lp_sampling_rate, ac->lp_channel_count),** where the lock **ac->queue_mutex** is released twice. Should it be a bug?

https://github.com/TokTok/c-toxcore/blob/13cca6716d95719f30b21b66c0cea8008604bfd0/toxav/audio.c#L136-L179

Best,

**Comment by nurupo** [comment]
After eyeballing it for some time, it does indeed look like a double-unlock is possible here. Calling `pthread_mutex_lock(ac->queue_mutex);` right before that `continue;` should fix that.
