### ISSUE TITLE
File independent getter/setter methods for tox ID reconstruction

### ISSUE THREAD

**Issue by omani** [TokTok/c-toxcore#1696]
hi there,
correct me if Im wrong but I dont see any possibility to save/store my public address (my toxid) somewhere other than into a file.

I am dealing with other storage methods in my application. like a database (rdbms) for example.
I want to be able to store my toxid (which is made out of the public key, the nospam nonce and other stuff). and quickly be able to construct my toxid from those values. sure, I could use a blob or []byte in my db. but I think there should be at least some methods to pass the public key, private key, etc. to reconstruct the public address (tox id) with this.

afaiu, right now it is a do or die situation. either use a file or generate a new toxid with every spin up of your application. some getter/setter methods to reconstruct the same toxid over and over again would be nice.

any ideas?

**Comment by iphydf** [comment]
You can initialise your Tox instance with only a secret key, and it will generate a new nospam and checksum for you: https://github.com/TokTok/c-toxcore/blob/7f0395b746f5a8aa605165c453aa2271b74bc803/toxcore/tox.h#L456

**Comment by iphydf** [comment]
Reopen if you have any more questions.
