### ISSUE TITLE
Enforce braces around macros that compute a value

### ISSUE THREAD

**Issue by sudden6** [TokTok/c-toxcore#1719]
As seen in #1718 macros computing values but not having braces are dangerous. Can we add a rule to any of our code formatters/linters to disallow these?

**Comment by JFreegman** [comment]
I'm surprised that none of the static analyzers look for that. Not even any compiler warnings that I'm aware of.

**Comment by sudden6** [comment]
Enabling that: https://clang.llvm.org/extra/clang-tidy/checks/bugprone-macro-parentheses.html as a required check should fix it I think™

**Comment by iphydf** [comment]
This is done now.
