### ISSUE TITLE
TCP-only mode, IP exposure risk

### ISSUE THREAD

**Issue by lproperty** [TokTok/c-toxcore#1927]
Hi,
Could someone please advise me if there's a risk for my IP to be exposed to my connected friends when I'm using TCP-only (UDP disabled)?

As I understand, if TCP relay is used, my friends will only see the IP address of the TCP relay that they are connecting to, and will not be able to see the destination IP address. However, as my knowledge about the protocol is still shallow, will there be a possible scenario for my friend to somehow figure out my IP address?

You answer will be greatly appreciated.

**Comment by JFreegman** [comment]
You shouldn't rely on the implementation of the TCP relays to keep your IP hidden from your contacts. It may be the case that this works right now (which I believe it does though can't guarantee), but there is no effort to enforce it, and it may change at any time in the future without notice. Any degree of anonymity provided by using TCP-only mode is incidental and undocumented.

**Comment by kurnevsky** [comment]
> will there be a possible scenario for my friend to somehow figure out my IP address?

It's totally possible. Your friend can launch his own relay and send it to you via one of internal packages so you will connect to it and reveal your IP.

**Comment by fcore117** [comment]
Simpler rule, do not add friends who you afraid and btw ISP knows your IP always.

**Comment by emdee-is** [comment]
The best solution is to run over Tor which should eliminate the exposure risk.

**Comment by emdee-is** [comment]
I'm not sure this should be closed if there is an exposure risk from KCI
https://github.com/TokTok/c-toxcore/issues/426

@goldroom my question is: is there an IP exposure risk when using Tor because of KCI?

**Comment by goldroom** [comment]
@emdee-is not sure what you are asking. KCI is a post-compromise issue in case your static private Tox identity key is stolen.
This is completely unrelated to any IP addresses.

**Comment by emdee-is** [comment]
> @emdee-is not sure what you are asking. KCI is a post-compromise issue in case your static private Tox identity key is stolen. This is completely unrelated to any IP addresses.

I'm not sure what I'm asking either so the answer could be just NO, but i thought I read somewhere that the compromised key could then later be used to reveal the IP in later communications. I'll see if I can find a citation, otherwise I just take it as a NO. 

Thanks for the reply.

**Comment by fcore117** [comment]
Actually TCP only mode should get option(toggleable) to still make direct connection for calls and file transfer then Tox would be complete Skype replacement ideologically and could be huge benefit for those sitting behind weak internets or phones. It is proven problem tested by me when one router hosted 9-16 persons behind one router and Tox just jammed that router hardly. This would be holy grail of Tox and exact Skype(old true Skype) replacement where better connections acted as a Supernode(in Tox UDP mode).

**Comment by Green-Sky** [comment]
I somewhat agree with @fcore117 , being able to toggle direct-mode per contact would be great.

**Comment by emdee-is** [comment]
> using tor (except from DNS lookups).

i think a higher priority is to do DNS lookups over Tor when using Tor/SOCKS5. Naive users of Tor don't firewall their machines (which is hard) so then leak DNS lookups a lot.

The c-code to do a DNS lookup over Tor is tiny: IIRC you connect to 9050 and give a oneliner. I know I have python code that does it: if anyone is interested I'll look for it?

Is there an issue open for DNS lookups over Tor when using Tor/SOCKS5? If not I'll be glad to add one.

**Comment by emdee-is** [comment]
The five+ year old open issue on this is: https://github.com/TokTok/c-toxcore/issues/469
