### ISSUE TITLE
Crash on call while peer calling you

### ISSUE THREAD

**Issue by isotoxin** [TokTok/c-toxcore#198]
How to reproduce:
1. Alice begin call to Bob and Bob begin call to Alice simultaneously.
2. Alice pressed hangup button and get crash.
3. Bob pressed hangup button and get crash.

Root of problem:
in file msi.c, in function **handle_init** FAILURE occurred. This mean unexpected **kill_call** called. So, MSICall object suddenly destroyed. Now we get dead pointer: ToxAV->calls[friend_number].msi_call 
And final action: toxav_call_control get this pointer by **call_get** and crashed.

**Comment by iphydf** [comment]
Cool! Can you create a new file with a test case that triggers the error and make a PR? That test case should fail, so we can't merge it, but we can base the fix on that test.

**Comment by iphydf** [comment]
@isotoxin does this still occur?

**Comment by iphydf** [comment]
This seems to be fixed.
