### ISSUE TITLE
nospam value is reversed in array returned by tox_self_get_address()

### ISSUE THREAD

**Issue by pranomostro** [TokTok/c-toxcore#205]
I have written following example code:

```
#include <stdio.h>
#include <stdlib.h>

#include <tox/tox.h>

int main(void)
{
    size_t i;
    uint8_t addr[TOX_ADDRESS_SIZE];
    char* nns="AABBCCDD";
    uint32_t ns;
    Tox* t;
    struct Tox_Options to;

    tox_options_default(&to);
    t=tox_new(&to, NULL);

    ns=tox_self_get_nospam(t);
    tox_self_get_address(t, addr);

    printf("current addr: ");
    for(i=0; i<TOX_ADDRESS_SIZE; i++)
        printf("%02X", addr[i]);
    putchar('\n');
    printf("current ns: %08X\n", ns);

    ns=strtoul(nns, NULL, 16);

    tox_self_set_nospam(t, ns);

    ns=tox_self_get_nospam(t);
    tox_self_get_address(t, addr);

    printf("current addr: ");
    for(i=0; i<TOX_ADDRESS_SIZE; i++)
        printf("%02X", addr[i]);
    putchar('\n');
    printf("current ns: %08X\n", ns);

    return 0;
}
```

When compiled with
    gcc -o tns tns.c -ltoxcore

and executed, this prints

```
current addr: 5A9712242692889C310A7227CD78D3D9F0F9F5AE9608DDD3640175419093A33368C3A8A5173B
current ns: A5A8C368
current addr: 5A9712242692889C310A7227CD78D3D9F0F9F5AE9608DDD3640175419093A333DDCCBBAAB13B
current ns: AABBCCDD
```

As you can see, the checksum (the addresses last 4 bytes-2) is reversed, instead `AABBCCDD` they are `DDCCBBAA`.

I am running Arch linux, Kernel 4.8.1, gcc 6.2.1, toxcore-toktok-git 3911-1.
If this is intended behaviour, ignore this.

**Comment by iphydf** [comment]
Reason: https://github.com/TokTok/c-toxcore/blob/949ef785a4e7aa7868c9605b6bbed15c3f4beab9/toxcore/Messenger.c#L149

If we change this, it needs to be changed in various places. It is indeed a bug, because it depends on system endianness. On big endian systems, friend requests probably don't work.

**Comment by pranomostro** [comment]
How are your thoughts about using ntohl() and htnl() from arpa/inet.h for that? Or is it not portable enough?

**Comment by GrayHatter** [comment]
>  On big endian systems, friend requests probably don't work.

lol... OH FUCK

**Comment by iphydf** [comment]
Yes, htonl would be acceptable for this (for now). Ideally we would have a binary codec abstraction like @nurupo proposed. The htonl function is already used in various places. The concern is not around whether and how we can do it, but currently most (probably all) nospams in existing friend addresses in existence are written in little endian. Only those that were retrieved from a tox instance running on a big endian system would have big endian. To make it portable, we would need to enforce little endian. I would prefer to make it big endian, and when adding a friend, we could try adding both endiannesses in the transitional period while the old little endian friend addresses are phased out.

**Comment by nurupo** [comment]
>On big endian systems, friend requests probably don't work.

Turns out they work, it's just that the nospam set function was expecting nospam in big endian and the nospam get function was returning it in a big endian.

**Comment by GrayHatter** [comment]
Moved to v0.0.5 to follow the attached pull.
