### ISSUE TITLE
Toxcore auto_tests fail in imperfect network conditions

### ISSUE THREAD

**Issue by GrayHatter** [TokTok/c-toxcore#21]
In #13, the group chat tests were dropped For Travis-CI.

Group chats will 'split' unpredictably, while only occasionally during local tests. On Travis the fail 40-80% of the time, making the whole test system itself, unusable. 

IMO merging the new version of group chats, would by a better expenditure of time, rather than trying to fix these tests (or fix group chats in general because the reason they fail is problem.)

**Comment by iphydf** [comment]
This is not only a group chats issue. Many auto tests fail arbitrarily on travis (and also on people's home computers). The tests are extremely brittle, and "designed to be run in perfect network conditions". The fakenet library I proposed would mitigate this issue.

**Comment by iphydf** [comment]
See #113 for additional logs and some discussion. Post updates here instead of on #113.

**Comment by iphydf** [comment]
This is fixed in some release before 0.2.4, when we disabled LAN discovery on most tests.
