### ISSUE TITLE
Improve speed and stability of LAN discovery test

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#2121]
In particular, speed up the `lan_discovery_test`. It often takes 1.5 minutes, and in the appveyor (windows/msvc) build it often times out completely.

**Comment by zoff99** [comment]
last time i looked i think i found that LAN discovery happens per friend and not globally.
and also it happens after a friend is already online.
need to confirm if i made a mistake. but if so those would be nice to change those.

**Comment by iphydf** [comment]
Fixed in #2126.
