### ISSUE TITLE
Toxcore needs Optimistic Merging

### ISSUE THREAD

**Issue by isotoxin** [TokTok/c-toxcore#213]
Guys, I hope you will understand me correctly.
I really want to toxcore flourished.
I very sad to see how the project dies. (Do not argue! It is so indeed)
I was happy to know that TokTok continue toxcore developing, but the happiness was short-lived.
You guys make the same mistake that most of the dead opensource project: Pessimistic Merging
Please read this article and think about it.
http://hintjens.com/blog:106
I wish good
PS. That is why I don't want to make any PR's to toxcore.

**Comment by iphydf** [comment]
* *It tells new contributors, "guilty until proven innocent,"* - Yes, and for a security-sensitive project, this seems like the right approach, at least for code.
* * If they can keep out potential competitors by delaying and blocking their patches, they will.* - We have not historically, and will not intentionally delay or block patches. I think we are a welcoming community, and we add basically anyone who intends to contribute to the Contributors team, making it possible for them to work on issues (assign, close, assign labels, etc.), create branches (discouraged but possible). This open mindset has so far proven very useful. As you can see, @SkyzohKey has added a label to this issue. I do think "trusted until proven guilty" is good for all this kind of management stuff, but not for code.
* *It opens the door to discrimination* - We have been "aggressively inclusive", as described above. We actively counter-act any kind of discrimination, and expect respectful behaviour on all communication platforms.
* *It slows down the learning cycle* - Iterating on features and ideas can be done in forks. This is one of the things that makes github great. The master branch in the TokTok repository is where we put well-tested code that can ideally be shipped at any time. Indeed we do introduce bugs sometimes, and then quickly fix them. Versions are used to pin specific points in time when we are reasonably sure that everything works correctly. I think a staged approach like this makes sense: unstable experimental development on user forks; reviewed and tested code on master; carefully tested code in version tags/releases.
* *It gives outsiders the chance to troll the project* - Can you explain how this is related? I don't see the link between patch management and trolling.
* *It puts the burden of work on individual contributors* - What kind of work? Indeed, the burden of producing high quality code is on the contributor. It is not reasonable to expect the maintainer to merge a patch and then proceed to clean up the mess.

"Good contributors who know the rules and write excellent, perfect patches." - These don't exist. Nobody always writes perfect patches.

The above is my opinion. We can try a different approach, if someone proposes and implements an approach that lets us retain code quality requirements, keep the maintenance burden acceptable, and still apply "optimistic merging".

**Comment by GrayHatter** [comment]
The author of the blog is an idiot. (This and the following opinions are my own and do not reflect the views of anyone but me) This is a paragraph he started with

> I recommend to merge quickly, without waiting for Continuous Integration testing to finish, and without review of the code. 

He's advocating to make all projects world writable by default. If you dont understand why that could be problematic, perhaps a security focused project is not where you should start.

> Standard practice (Pessimistic Merging, or PM) is to wait until CI is done, then do a code review, then test the patch on a branch, and then provide feedback to the author. The author can then fix the patch and the test/review cycle starts again.

The assertion that there is good code, and bad code is a fact. If you want more evidence look at my #200 pull request. There were a lot of issues with my pull that have already been fixed, and a lot more that need to be fixed. I wrote a mess of imperfect code.

CI exists to be the bare minimum of code review, and ours take 5-15m if you're unwilling to wait 5-15m before adding code to a project that tens of thousands of people use monthly, a number of them who believe their lives depends on it's quality and security. Then I dont want your contributions. (Again my own opinions, other developers here will still support you)

Good code review takes time, our process allows anyone, be they experts with strict attention to detail @iphydf or people who are teaching themselves to write code @SkyzohKey @endoffile78 @Grayhatter. And with the requirements we have everyone learns what good code is, and their contributions are supported valued and improved. During the pull request phase.

> At this stage the maintainer can (and often does) make value judgments such as "I don't like how you do this" or "this doesn't fit with our project vision."

Yeah, and if they have good reasons, I'll support their value judgments. If they dont I'll likely mock them for it. If someone opened a pull request for a very impressive c# pathing algorithm. Should we merge that, even if it doesn't fit in with our project vision?

> "guilty until proven innocent," which is a negative message that creates negative emotions. 

Wer'e all adults here, code matters feelings not so much https://github.com/domgetter/NCoC


> It opens the door to discrimination. One can argue, a project belongs to its maintainers, so they can choose who they want to work with. My response is: projects that are not aggressively inclusive will die, and deserve to die. 

I'm not sure if the author knows this is a point in support of Pessimistic merging. either way see my previous point

> It slows down the learning cycle. Innovation demands rapid experiment-failure-success cycles. Someone identifies a problem or inefficiency in a product. Someone proposes a fix. The fix is tested and works or fails. We have learned something new. The faster this cycle happens, the faster and more accurately the project can move.

This is flatlly wrong. I dont have time to review whole files ar go commit by commit to provide feedback in a disjointed way. I do have tme to review pull requests. See my previous comments about how code review add to learning.


> It puts the burden of work on individual contributors, which is ironic and sad for open source. 

It's not ironic

> We want to work together yet we're told to fix our work alone.

No you're not. The recurring format we often use is 'why'? Why did you do it like this. See all of jfreegmans comments on #200 provide your rational here.

Must switch devices, will update this post now. 

Now let's see how this works when we use Optimistic Merge. To start with, understand that not all patches nor all contributors are the same. We see at least four main cases in our open source projects:

Good contributors who know the rules and write excellent, perfect patches.
Good contributors who make mistakes, and who write useful yet broken patches.
Mediocre contributors who make patches that no-one notices or cares about.
Trollish contributors who ignore the rules, and who write toxic patches.
PM assumes all patches are toxic until proven good (4). Whereas in reality most patches tend to be useful, and worth improving (2).

Let's see how each scenario works, with PM and OM:

PM: depending on unspecified, arbitrary criteria, patch may be merged rapidly or slowly. At least sometimes, a good contributor will be left with bad feelings. OM: good contributors feel happy and appreciated, and continue to provide excellent patches until they are done using the project.
PM: contributor retreats, fixes patch, comes back somewhat humiliated. OM: second contributor joins in to help first fix their patch. We get a short, happy patch party. New contributor now has a coach and friend in the project.
PM: we get a flamewar and everyone wonders why the community is so hostile. OM: the mediocre contributor is largely ignored. If patch needs fixing, it'll happen rapidly. Contributor loses interest and eventually the patch is reverted.
PM: we get a flamewar which troll wins by sheer force of argument. Community explodes in fight-or-flee emotions. Bad patches get pushed through. OM: existing contributor immediately reverts the patch. There is no discussion. Troll may try again, and eventually may be banned. Toxic patches remain in git history forever.
In each case, OM has a better outcome than PM.

In the majority case (patches that need further work), Optimistic Merge creates the conditions for mentoring and coaching. And indeed this is what we see in ZeroMQ projects, and is one of the reasons they are such fun to work on.

References:

ZeroMQ RFC 22, C4.1: the Collective Code Construction Contract.
My top tips were, for what it's worth:

People before code: build the right community and it will build the right code.
Progress before consensus: look for processes that work without upfront consensus (except on rules).
Problems before solutions: use a problem-driven process.
Contracts before internals: use contracts to test behavior, not inspection of internals.
Rules before hope: write down your development process or use C4.1.
Merit before power: treat everyone fairly and equitably.
Market before product: aim for a market of competing and interoperating projects, not a single product.

**Comment by GrayHatter** [comment]
@isotoxin I'm sorry if the requirement that only good code gets merged into toxcore makes it so you don't want to contribute. I really would like your support/code if you're willing to help. But if your expectation is that we merge what ever anyone shits out, only to HOPEFULLY fix it later... 

https://www.youtube.com/watch?v=6gLMSf4afzo

**Comment by optimumtact** [comment]
I'd like to think that toktok has set a strong foundation for a proper community to grow around tox and I have high hopes for the future of tox with them.

**Comment by iphydf** [comment]
@isotoxin I appreciate that you're proactively trying to avoid issues someone has seen in other communities, but as far as I can tell, our strategy works well for us at the moment. I am therefore reluctant to choose a different strategy at this time. Thanks for bringing this article to our attention, I think it has been good to discuss the ideas in them.

I will close this since there is no action we can take right now. Please reopen the issue or open a new one (or better yet: [come talk to us](http://webchat.freenode.net/?channels=toktok)) if you feel that our community is hostile to contributors.

**Comment by uToxingInTox** [comment]
>come talk to us

And link to irc. Tox devs use irc. Not Tox. Bye-bye Tox

> our community is hostile to contributors

Lol. Community?

>Lock, ban, delete. It's not censorship, 

Heh. If you are not with me, then you are my enemy

>Working with toxcore we do need developers, but only good developers. And as I said, all developers make mistakes, so a good developer is one who want's to learn, and fix every mistake they can.

But you don't have any devs and won't find. Just continue wasting time  on ~~pink~~ red teams and spending time discussing toxcore version system without real contributions

> I have high __hopes__ for the future of tox with them.

Hopes and nothing more. Sounds like "hope gentoo will fix gc one day"

Time to change something in tox development. If you want to know what - come talk to me on irc jajajaja

**Comment by SkyzohKey** [comment]
>And link to irc. Tox devs use irc. Not Tox. Bye-bye Tox

Currently Tox groups are not enough efficient to handle permissions, so yeah, IRC.

>If you are not with me, then you are my enemy

Typical American reaction. You can't be nor a friend nor a ennemy but something/someone else. People that thinks binary (black or white) are just stupid, gray also exists.

For the rest, I have no time to loose with people that doesn't use it real name to criticize.

**Comment by uToxingInTox** [comment]
>Currently Tox groups are not enough efficient to handle permissions, so yeah, IRC.

And I don't see any progress in last year in new groups. You need gc with possibility to ban everybody who disagree with toktok, am I right? New gc are good for this purpose

>Typical American reaction

Yes, typical american reaction. AFAIK GrayHatter is american. That's why he wants to

>Lock, ban, delete.

everybody who disagree with him.

For the rest, I have no time to loose with people that doesn't use their real name to criticize. As every Tox user I don't like anonymity!
