### ISSUE TITLE
When v0.1 release?

### ISSUE THREAD

**Issue by zetok** [TokTok/c-toxcore#216]
With a ~stable API for clients to use.

**Comment by iphydf** [comment]
I was hoping to get the required API changes in before 0.1, i.e. #40 (#203) is done. Given the complexity of that change, we may need to ship without that change.

**Comment by iphydf** [comment]
Tentative date set in the v0.1.0 milestone: 6 December.

**Comment by GrayHatter** [comment]
The answer seems to be today :D
