### ISSUE TITLE
Make the current tests exercise both ipv4 and ipv6.

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#22]
Disable ipv6 on travis if it breaks too often, but have at least one test that exercises both paths.

**Comment by GrayHatter** [comment]
@iphydf should we close this issue?

I'm leaning more towards your idea of a virtual network interface for testing. And then optionally, we can do profiling across IPv4/6 when/if needed?

**Comment by iphydf** [comment]
Sounds good. Network tests aren't unit tests anyway, and we should have integration tests for all network situations we can simulate or create at some point.
