### ISSUE TITLE
Option to disable local peer detection

### ISSUE THREAD

**Issue by Hasshu** [TokTok/c-toxcore#221]
Always-on local peer detection apparently can lead to a VPN leak, so having an option to disable it would be nice. (A warning in the tooltip might be a good idea, as well.)

See also qTox/qTox#2965 and irungentoo/toxcore#1530.

**Comment by GrayHatter** [comment]
I'm happy to help, but I haven't started on this yet. So if you can fix this before me... It's a race, READY GO!

**Comment by cleverca22** [comment]
related, i've found that the local peer detection partially breaks if you don't use port 33445, it can't detect the broadcast packets, but it will still send them out and be heard

**Comment by GrayHatter** [comment]
@endoffile78 do you wanna try this one?

**Comment by endoffile78** [comment]
@GrayHatter Sure.

**Comment by iphydf** [comment]
Done in #306.

**Comment by Hasshu** [comment]
Ah, finally. Thanks to all who participated!
