### ISSUE TITLE
Run strong fuzz tests against NGC

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#2302]
After https://github.com/TokTok/c-toxcore/pull/2291 is merged, we should add some setup code in protodump.cc to create/join a group and send+receive some messages. The protocol dump from that should then be used to run a longer term (several days) fuzz test against NGC.

**Comment by Green-Sky** [comment]
This was done manually https://github.com/TokTok/toktok-fuzzer/pull/19

(@iphydf can we consider this done?)

**Comment by iphydf** [comment]
That PR is only toxsave, not the protocol. But: I've done it manually for several months on my machine, and nothing came up, so we can consider it done although I should make a PR for the code and run it on CI and on cron.
