### ISSUE TITLE
third_party/cmp/cmp.c missing

### ISSUE THREAD

**Issue by almindor** [TokTok/c-toxcore#2315]
Trying to build from the .tar.gz sources I get

```
CMake Error at cmake/ModulePackage.cmake:67 (add_library):
  Cannot find source file:

    third_party/cmp/cmp.c
```

The `cmp` folder is empty. Shouldn't it be populated in the source archives?

**Comment by almindor** [comment]
Nvm. I was using github generated "source only" archive, switching to the manually made one now.

**Comment by Jongjan88** [comment]
Download with git. still no cmp.c only manually it works! third_party/**cmp**/cmp.c

CMP map contains numbers ( cmp @ e836703 ) 

https://github.com/TokTok/c-toxcore/tree/master/third_party

**Comment by Green-Sky** [comment]
@Jongjan88 cmp is included as a git submodule. so a simple git clone does not pull it. either add --recurse-submodules, or do a `git submodule update --init` after a clone.
