### ISSUE TITLE
toxcore LOGGER_TRACE messages don't say if it's a bug or a feature.

### ISSUE THREAD

**Issue by emdee-is** [TokTok/c-toxcore#2353]
toxcore LOGGER_TRACE messages don't say if it's  a warning/error/info
It would be nice if the started with a C/E/W/I/D to let you know.

For example, I don't know this is a bug or a feature (*s added):
```
TRAC> Messenger.c#2709:do_messenger Friend num in DHT 2 != friend num in msger 15
TRAC> Messenger.c#2723:do_messenger F[--: 0] 037C7E34FDCAD703F3AFFB46B0F978B84DD3B0B6E62365FBA71879C8ACDB58**
TRAC> Messenger.c#2723:do_messenger F[--: 1] 9C769350097D5F15C06FCC398F7F1036FD6F3DB82FACF6509A59CAC6B1EE13**
```

**Comment by JFreegman** [comment]
Trace messages are at the trace level. If it were a warning they would be at the warning level etc.

**Comment by nurupo** [comment]
Trace level just dumps everything about what toxcore is doing as much as possible. It's not a warning or an error. It's just to understand what toxcore is doing. For example, it logs the packets it sends and receives, logs when it's waiting on more data, etc.
