### ISSUE TITLE
resolve_bootstrap_node assert hit

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#2358]
https://github.com/TokTok/c-toxcore/blob/b8aa21cc447e866633fb5a2d26b0f86b3268055e/toxcore/tox.c#L1018

i have hit this assert in resolve_bootstrap_node on a box with DNS lookup timeouts.
do we need to fix something here?

**Comment by Green-Sky** [comment]
Going through https://github.com/TokTok/c-toxcore/blob/b8aa21cc447e866633fb5a2d26b0f86b3268055e/toxcore/network.c#L1768
after https://github.com/TokTok/c-toxcore/blob/b8aa21cc447e866633fb5a2d26b0f86b3268055e/toxcore/network.c#L1800
it might be that https://github.com/TokTok/c-toxcore/blob/b8aa21cc447e866633fb5a2d26b0f86b3268055e/toxcore/network.c#L1799 does not return an error, but not returning a ipv4 or ipv6 address
leading to https://github.com/TokTok/c-toxcore/blob/b8aa21cc447e866633fb5a2d26b0f86b3268055e/toxcore/network.c#L1825-L1828
