### ISSUE TITLE
Tox file transfers do not use available bandwidth

### ISSUE THREAD

**Issue by ovalseven8** [TokTok/c-toxcore#236]
Originally posted here -> https://github.com/irungentoo/toxcore/issues/1477:

**

> When I open two Tox instances (qTox) and make a file transfer between the two instances, I only get a speed maximum around 18 MiB/s. That's pretty slow for a direct connection. Much more should be possible, shouldn't it?

**

> **irungentoo wrote:**
> Can someone try a local transfer on windows and tell me what is the maximum speed that they get is.
> 
> **TheNain38 wrote:**
> @irungentoo It was around 30-40MiB/s for me with a 3.96GiB file
> 
> **LittleVulpix wrote:**
> @irungentoo It was about 24-28MB/s for me between two toxes for a 1.8GB file (gbit lan between two computers. In comparison, samba speed was at 100-110MB/s until disk i/o became an issue, then it went to about 80MB/s)
> 
> **towlie wrote:**
> Was it ever faster? You should remember that your computer has to encrypt the content which requires more CPU time compared to unencrypted content.
> 
> **LittleVulpix wrote:**
> @towlie It was faster on old toxcore, way back in the day. It didn't work at all on the recent toxcore so until now I didn't get to test it again. And I didn't notice some crazy CPU utilization on either side, these were somewhat powerful machines.

**Comment by hardhub** [comment]
I am not able to get more than ~43 Mb/s (5.38 MiB/s). It is always limited even we are using 1 GbE connection.

Client is qTox but I assume it is related to core.

Any news? How can I help to test issue?

**Comment by Green-Sky** [comment]
related pr: https://github.com/TokTok/c-toxcore/pull/1668

**Comment by fcore117** [comment]
Working solution for fast unlimited speed file transfers would be quite useful if it can done right without sacrificing anything.
