### ISSUE TITLE
LAN detection does not work

### ISSUE THREAD

**Issue by ovalseven8** [TokTok/c-toxcore#239]
Tox **should** work completely without internet access if two people are in the same LAN network.

@codedust [wrote](https://github.com/irungentoo/toxcore/issues/1215#issuecomment-124970246):
> I can confirm that two tox instances on a single computer without an internet connection (using qTox with UDP and IPv6 activated) won't connect to each other, too.

@alsternerd [wrote](https://github.com/irungentoo/toxcore/issues/1215#issuecomment-147346949):
> Can confirm this too.

@shalnoff [wrote](https://github.com/irungentoo/toxcore/issues/1215#issuecomment-254590157):
> confirmed. same problem. Two Tox instances running in the same subnet can't connect each other without WAN access (i.e. being disconnected from Internet)

**Comment by cleverca22** [comment]
lan detection relies on broadcast packet being sent to port 33445, so the remote peer has to bind to that port to detect it

**Comment by anthonybilinski** [comment]
LAN detection seems to rely on UDP being enabled, but I'm not sure if that's intentional.
In Messenger.c:
```
    if (options->udp_disabled) {
        m->net = new_networking_no_udp(log);
    } else {
        IP ip;
        ip_init(&ip, options->ipv6enabled);
        m->net = new_networking_ex(log, ip, options->port_range[0], options->port_range[1], &net_err);
    }
```
then that dht's passed into lan_discovery_send, where its net_family doesn't match IPv4 or IPv6, so it returns -1 and never sends a discovery packet.

**Comment by iphydf** [comment]
I think this is done. @Diadlo, you added some code to make LAN discovery work better, right? Can someone confirm?

**Comment by iphydf** [comment]
LAN detection works. If it doesn't, please reopen and let us know.
