### ISSUE TITLE
error in wiki , trouble with  tox_self_set_name

### ISSUE THREAD

**Issue by bialystok** [TokTok/c-toxcore#2411]
error: pointer targets in passing argument 2 of ‘tox_self_set_name’ differ in signedness [-Wpointer-sign]
   49 |     tox_self_set_name(tox, name, strlen(name), NULL);
      |                            ^~~~
      |                            |
      |                            const char *
In file included from techo.c:9:
/usr/include/tox/tox.h:1171:49: note: expected ‘const uint8_t *’ {aka ‘const unsigned char *’} but argument is of type ‘const char *’
 1171 | bool tox_self_set_name(Tox *tox, const uint8_t *name, size_t length, Tox_Err_Set_Info *error);
      |                                  ~~~~~~~~~~~~~~~^~~~
techo.c:52:38: error: pointer targets in passing argument 2 of ‘tox_self_set_status_message’ differ in signedness [-Wpointer-sign]
   52 |     tox_self_set_status_message(tox, status_message, strlen(status_message), NULL);
      |                                      ^~~~~~~~~~~~~~
      |                                      |
      |                                      const char *
/usr/include/tox/tox.h:1204:59: note: expected ‘const uint8_t *’ {aka ‘const unsigned char *’} but argument is of type ‘const char *’
 1204 | bool tox_self_set_status_message(Tox *tox, const uint8_t *status_message, size_t length, Tox_Err_Set_Info *error);

**Comment by Green-Sky** [comment]
you need to cast form `const char*` to `const unsigned char*` (aka `const uint8_t`)

eg: `tox_self_set_name(tox, (const uint8_t*)name, strlen(name), NULL);`



https://github.com/TokTok/c-toxcore/blob/24b54722aed65b02f1e921f08f8d31d68f92a45a/toxcore/tox.h#L1162-L1173

**Comment by bialystok** [comment]
Hello,   You probably not testing Your answer ;)   ---------  to1.c: In function ‘main’:  to1.c:57:29: error: initialization of ‘const unsigned char *’ from incompatible pointer type ‘int *’ [-Wincompatible-pointer-types]     57 | const unsigned char *name = L&#34;Nazwa&#34;;        |                             ^~~~~~~~  to1.c:69:38: error: pointer targets in passing argument 1 of ‘strlen’ differ in signedness [-Wpointer-sign]     69 |  tox_self_set_name(tox, name, strlen(name), NULL);        |                                      ^~~~        |                                      |        |                                      const unsigned char *  In file included from to1.c:6:  /usr/include/string.h:407:35: note: expected ‘const char *’ but argument is of type ‘const unsigned char *’    407 | extern size_t strlen (const char *__s)        |                       ~~~~~~~~~~~~^~~   ---------piece of to1.c----  #include &lt;sodium/utils.h&gt;  #include &lt;tox/tox.h&gt;   #include &lt;stdio.h&gt;  #include &lt;stdlib.h&gt;  #include &lt;string.h&gt;  #include &lt;ctype.h&gt;   typedef struct DHT_node {      const char *ip;      uint16_t port;      const char key_hex[TOX_PUBLIC_KEY_SIZE*2 + 1]; // 1 for null terminator  } DHT_node;   void bootstrap(Tox *tox)  {  DHT_node nodes[] =  {      {&#34;85.143.221.42&#34;,                      33445, &#34;DA4E4ED4B697F2E9B000EEFE3A34B554ACD3F45F5C96EAEA2516DD7FF9AF7B43&#34;},      {&#34;205.185.115.131&#34;,                       53, &#34;3091C6BEB2A993F1C6300C16549FABA67098FF3D62C6D253828B531470B53D68&#34;},      {&#34;188.214.122.30&#34;,                     33445, &#34;2A9F7A620581D5D1B09B004624559211C5ED3D1D712E8066ACDB0896A7335705&#34;},      {&#34;tox4.plastiras.org&#34;,                 33445, &#34;836D1DA2BE12FE0E669334E437BE3FB02806F1528C2B2782113E0910C7711409&#34;}  };   for (size_t i = 0; i &lt; sizeof(nodes)/sizeof(DHT_node); i ++)     {     unsigned char key_bin[TOX_PUBLIC_KEY_SIZE];     sodium_hex2bin(key_bin, sizeof(key_bin), nodes[i].key_hex, sizeof(nodes[i].key_hex)-1,                         NULL, NULL, NULL);     tox_bootstrap(tox, nodes[i].ip, nodes[i].port, key_bin, NULL);     }  }   int main()  {  TOX_ERR_NEW err_new;  const unsigned char *name = L&#34;Nazwa&#34;;   Tox *tox = tox_new(NULL, &amp;err_new);  if(err_new != TOX_ERR_NEW_OK)     {     fprintf(stderr, &#34;tox_new :: Nie powiodło się uruchomienie [%d]\n&#34;, err_new);     exit(1);     }     bootstrap(tox);     //print_tox_id(tox);  tox_self_set_name(tox, name, strlen(name), NULL);   tox_kill(tox);   return 0;  }    Dnia 19 września 2023 17:09 Erik Scholz &lt;  ***@***.*** &gt; napisał(a):   you need to cast form  const char*  to  const unsigned char*  (aka  const uint8_t )  eg:  tox_self_set_name(tox, (const uint8_t*)name, strlen(name), NULL);  github.com https://github.com/TokTok/c-toxcore/blob/24b54722aed65b02f1e921f08f8d31d68f92a45a/toxcore/tox.h#L1162-L1173   —  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .  You are receiving this because you authored the thread. Message ID:  ***@***.***&gt;

**Comment by Green-Sky** [comment]
1. your message is almost unreadable on github :laughing: 

2. you still need to define strings as `const char*` and then cast them at the appropriate call sites.

```
const char *name = "Nazwa";
tox_self_set_name(tox, (const uint8_t*)name, strlen(name), NULL);
```

i think the compiler disliked the `const unsigned char *name = ""` very much.

**Comment by nurupo** [comment]
@Green-Sky don't waste your time, this must be some sort of elaborate trolling. They are following [the echo bot example](https://wiki.tox.chat/developers/client_examples/echo_bot?s[]=echo#complete_code), but instead of following the instructions and using the provided compilation command they go out of their way to purposefully enable a bunch of warnings, probably with something like `-Wall -Wextra -pedantic`, and then turn them into errors with `-Werror` -- they do this to themselves and complain of why this is happening. They even sent me an email reporting these "errors" and also went to report them on IRC.

**Comment by bialystok** [comment]
@nurupo
 No one wants to be challenged and insulted.
No one wants to work with idiots either.
