### ISSUE TITLE
include in project

### ISSUE THREAD

**Issue by Allespro** [TokTok/c-toxcore#2423]
Hi, can someone please help to know how to import this in my project without linking to precompiled .a library file. I just want to include them like `#include "toxcore/tox.h"` but that doesn't work

**Comment by iphydf** [comment]
`#include <tox/tox.h>` is where it's installed.

**Comment by Allespro** [comment]
> `#include <tox/tox.h>` is where it's installed.

yes, I do that, and this work, but for this I need to add static library to gcc command when build my code. And I want to include Tox code direct in project without static lib

**Comment by nurupo** [comment]
Well, toxcore is not a header-only library, of course including just the header file without linking to the library won't work.

I think you might be on your own on this one. Normally one would just either statically of dynamically link a library. You will have to make your build system compile toxcore and how this is done would depend on the build system you use. Then toxcore further depends on other libraries: libsodium, libopus, libvpx, etc., so you would need to link against their library files too, unless you also want to include them in your project in entirety?

**Comment by Allespro** [comment]
I understand you. but I need only sending messages, receiving and friend request from all the functionality, all the rest is unnecessary, I would like to reduce the size of the source file by compiling only the necessary functions

**Comment by Green-Sky** [comment]
You could try the amalgamation script https://github.com/TokTok/c-toxcore/blob/master/other/make_single_file . Not sure if it still works.

**Comment by iphydf** [comment]
That script should work, yes. It's used in CI to run whole-program static analysis.

**Comment by Allespro** [comment]
Wow that's magic.
I run 
`./c-toxcore/other/make_single_file ./c-toxcore/toxcore/{*.c,*.h} ./c-toxcore/toxcore/events/{*.c,*.h} ./c-toxcore/toxencryptsave/{*.c,*.h} ./c-toxcore/third_party/cmp/{*.c,*.h} myfile.c > myfile_tox.c`
then
`gcc -o bot myfile_tox.c -Bstatic -Bdynamic -lc -lm -ldl -lpthread -pthread -Og -Wall -DNDEBUG /usr/local/lib/libsodium.a`
and this reduce final file size from 1,7M to 899K and to 312K with UPX

Thanks for help!

**Comment by Green-Sky** [comment]
You are also optimizing for debug, use `-O2` or `-O3`, or when size is your major concern, `-Os`
