### ISSUE TITLE
create_extended_keypair should use Random and be made deterministic for fuzzing

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#2649]
crypto_sign_keypair generates random numbers and then derives a key. We should use `Random` for random numbers and derive the key from that. It's exactly the same in production builds, but in fuzzing this ensures that we can fuzz NGC properly.

**Comment by JFreegman** [comment]
Do you mean write fuzzer-only re-implementation of the libsodium function? I wouldn't want to be re-implementing libsodium internals in production. Even if it's a copy-paste job there are numerous issues with that.

**Comment by iphydf** [comment]
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_sign/ed25519/ref10/keypair.c#L39

Yes, use the "seed" version of the API instead of the unseeded version where it seeds via internal random.
