### ISSUE TITLE
Friend requests with very long messages are ignored

### ISSUE THREAD

**Issue by JFreegman** [TokTok/c-toxcore#2719]
If you send a friend request through the onion with a message over a certain threshold but still under `TOX_MAX_FRIEND_REQUEST_LENGTH`, the request will succeed on the sender's side, but be dropped on the receiving side. This is because the length of the request packet is too large for the onion data packet handler.

The fix: Reduce [MAX_FRIEND_REQUEST_DATA_SIZE](https://github.com/TokTok/c-toxcore/blob/master/toxcore/friend_requests.h#L17) and [TOX_MAX_FRIEND_REQUEST_LENGTH](https://github.com/TokTok/c-toxcore/blob/master/toxcore/tox.h#L286) so that the maximum possible packet size received by [handle_data_response()](https://github.com/TokTok/c-toxcore/blob/master/toxcore/onion_client.c#L1133C18-L1133C39) is <= [MAX_DATA_REQUEST_SIZE](https://github.com/TokTok/c-toxcore/blob/master/toxcore/onion_announce.h#L42). The length check in [send_friend_request_packet()](https://github.com/TokTok/c-toxcore/blob/master/toxcore/friend_connection.c#L875) also needs to be adjusted to match the new value.

The bigger fix: The onion shouldn't be able to send packets that are too large to be handled.

**Comment by Green-Sky** [comment]
Should this be considered done?
