### ISSUE TITLE
v0.2.19 release?

### ISSUE THREAD

**Issue by javierinojosa** [TokTok/c-toxcore#2723]
Hello,

I am relatively new to the Tox protocol, I thank you in advance for your kind help. I am working on a project that uses Tox as one of multiple protocols to exchange information with another peer.

We are using version v0.2.18 #2300. However, we noticed that several patches and fixes have been implemented since the last release.
Is there an estimated release date for v0.2.19?

Thank you for your help!

**Comment by iphydf** [comment]
Any day now :). Only #2713 needs to be merged (it's reviewed now, I'll let @nurupo issue the merge manually), then @robinlinden will make a release.

**Comment by javierinojosa** [comment]
Amazing @iphydf! We will wait for the release to use it as soon as it comes out.

Thank you very much to you and @nurupo and @robinlinden as well!

**Comment by zoff99** [comment]
@javierinojosa what project are you working on? can you link to it?

**Comment by robinlinden** [comment]
Release is released.
