### ISSUE TITLE
error compiling on fedora

### ISSUE THREAD

**Issue by bialystok** [TokTok/c-toxcore#2734]
```bash
$cmake ..
all ok
$make
...
[ 85%] Linking CXX executable unit_rtp_test
[ 85%] Built target unit_rtp_test
[ 85%] Building CXX object CMakeFiles/unit_DHT_test.dir/toxcore/DHT_test.cc.o
/home/oooo/c-toxcore/toxcore/DHT_test.cc:3:10: fatal error: gmock/gmock.h: Nie ma takiego pliku ani katalogu
    3 | #include <gmock/gmock.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by nurupo** [comment]
Can you run `export LC_ALL=C` in your shell, which would make the programs output in English, and then provide the full cmake command invocation you used and the full cmake output? You can then do `unset LC_ALL` to undo the export command.  Also, which version of toxcore you are building and what is your OS version?

**Comment by iphydf** [comment]
I'd recommend installing gmock or uninstalling gtest. In some cases, if gtest is installed, we assume that gmock is also available. You can also disable the unit tests by removing all the `unit_test` calls from `CMakeLists.txt` (we don't have an option for that, yet).

**Comment by iphydf** [comment]
I'm adding a `UNITTEST` flag in #2742 which you can use.
