### ISSUE TITLE
Some new features for better privacy and security 

### ISSUE THREAD

**Issue by NiKola-UE** [TokTok/c-toxcore#2737]

**Comment by NiKola-UE** [comment]
Thanks for the correction. 


If it absolutely necessary, I can send the same message again, or forward it to the true e-mail address, but I don't think there is any need for that. 

The most important thing is that my proposals still got where they should be. 

Maybe I'm exaggerating, but let me suggest one more thing: it wouldn't be bad if I could have separate user IDs (or whatever it's called in Tox) for private and business conversations. For example, if I use Tox both for communication with friends and for business meetings, I definitely don't want to have everything on the same list, if you know what I mean. 

I would like to mention that SnapChat, probably in an attempt to gain more users, has even included its own chatbot in its application, but the question is how wise it is... 

Close this issue when you judge that everything that needs to be said has been said.

**Comment by NiKola-UE** [comment]
Here, let me refresh this issue a bit. 


Although it serves mainly for video conferences and is primarily used for that, I think that Jitsi has many interesting things that can be integrated, but of course exclusively in Tox itself. All their repositories are 
[here, ](https://github.com/jitsi/)
so let's add what is deemed appropriate. 


Being able to secretly chat with multiple people at the same time is great, but the grouping that exists on centralized apps (Whatsapp, Viber, Telegram, Revolt, etc.) is something I don't like and should be avoided. 


Since Tox will certainly be used by activists, journalists, whistleblowers, dissidents, etc., enabling Wi-Fi and Bluetooth can be sometime useful even when the internet is blocked. 

Although it should not be rushed and it is not necessary, creating a chatbot can be an interesting option in communication as well, but it should be based exclusively on FOS chatbots and models and preferably with the also FOS speech synthesizers like ESpeak and RHVoice that would be used for voice responses.
 


That's all from me for now. Come on, join the dialogue while this issue is still open.

**Comment by zoff99** [comment]
@NiKola-UE you mentioned that you are a blind person. do you use tox now? if so what tox client are you using? and how does it work for blind persons?

**Comment by NiKola-UE** [comment]
Thanks for responding. 


I will definitely try it when I have more time and report my observations here. 


But it will still be a little more difficult because I don't know if anyone here in Serbia, and even more widely, has heard of Toks. My friends first heard about it from me...

**Comment by NiKola-UE** [comment]
Here, I still set aside some time to test UTox version for Windows. 

It's nice that it doesn't need installation and that no anti-malware programs have reacted as something suspicious, but that's all I can say. Simply, the application is not adapted for the keyboard at all, and whatever key I press, nothing happens; except that pressing Alt brings up that basic system menu for moving, resizing and closing. But you have to be careful here too, because when I used Signal's application for Windows earlier, it was of no use, because although it was nicely adapted for the keyboard, it still lacked some key functions, and in addition, it caused me some trouble on the system . 

I'm also going to try the Android version of Tox, but that will have to wait until I check out the interface and get my friends to do the same, so we'll see what happens. 

I will report when there are results. 

Considering how many issues have been opened here in the meantime, it promises a lot, so I have no doubt that Tox will get better and better. Let it be.

**Comment by zoff99** [comment]
just a quick note, please do not use utox anymore. it has not been updated in many years, and has some memory issues.

**Comment by NiKola-UE** [comment]
I apologize for not mentioning my experience with Tox earlier, but I couldn't. 

I can say that the app is very easy to use and has a lot of promise, but it looks unfinished and still needs a lot of patient work. Downloading it, entering the necessary information and forwarding the ID is really easy, and adding someone into contacts is also simple. However, although the call option is easy to find, it doesn't seem to work. For example, I invited a friend or (s)he invited me. We both get a notification about accepting and receiving calls (mostly voice calls because we couldn't find where the video calls are), but there is no sound and it is not possible to talk at all. Messages arrive without problems (I don't know if there is an option to make them self-destruct), but we couldn't find how to send voice and video messages. So the interface is nice even for those with minimal technical knowledge looking for simplicity and with some better automatic translator you can get good translations in most languages, but it still lacks a lot. 







Now I would like to return to the beginning of this issue. Since the Tor and Lokinet can have problems with exit nodes, and the other networks I mentioned are mostly not even intended for anonymity, maybe the Whonix's core could be used for exit nodes even though it is an OS, and possibly N2N, but well... 


When I referred to Jitsi, I was primarily thinking about the Jigasi which can be used for making phone calls. The ability to change the voice can be useful, for example, when some  human rights, anti-corruption fighters and other activists need to send a secret voice message from Tox in which their natural voice must be protected for reasons that we can easily guess. That's why it can be intuitive to support Bluetooth, use without a SIN card and create temporary IDs. Someone will use it to joke with their friends, but that's their job. 




And speaking of that, how to preserveID is very important. Thus, copying and saving the ID in the PDF, EPUB, ODF and some other FOSS cross-platform formats can help if I need to log in on multiple devices and especially if I have changed my mobile phone, phone number or computer. If, in spite of everything, I was clumsy and didn't save anywhere, I'll have to create new ID again and again add friends to my contacts, but that's my own fault because I wasn't responsible, right? The only question that remains is what can be done if someone else tries to log in with my user account, i.e. how to protect my data from theft if it happens. As I already said, the authors of SimpleXChat claim that they do not need any IDs, which supposedly makes their application more secure and private than all the others, but the question is how it really looks in practice. 




And the slow development of a Tox does not have to be so bad in itself, among other things, because the more and longer new possibilities are tested, the greater the chances are that they will be more secure and private, and errors and bugs can be more easily discovered and removed, and add additional patches and new protective layers. You just need to work hard and dedicate yourself. 





I believe that I can contribute to the further development and improvement of the Tox, which can certainly become much better and stronger, although I am not a programmer.

**Comment by NiKola-UE** [comment]
Is it possible that there are still no any reactions? 



Okay, I thought of some more seemingly unimportant, but still important things that can be implemented. 

I want to mention the OnionCat which encrypt  traffic across Tor, che client apps VPNHood! and the N3N that appeared recently. 

It is also important that Tox has its own sounds for incoming and outgoing messages, calls and all other notifications, like most, predominantly  centralized applications that already have that, but if possible some kind of protection against malwares, where I mean Pegasus and Predator, which are increasingly dangerous, so it is easy for them to capture the content of communication applications because they are spyware that is installed without the user's knowledge and serious anti-malware are difficult to deal with, let alone chat applications. 



Anyway, I expect an improved versions of Tox, in which everything that is missing will be compensated and corrected, and of course a lot of new things will be added.
