### ISSUE TITLE
File transfer stuck at queue 

### ISSUE THREAD

**Issue by vehosah** [TokTok/c-toxcore#2740]
On android 12,13 on both Android toxs

**Comment by zoff99** [comment]
@vehosah this is the repository of the tox core library. what android tox client are you using?
i would be nice if you could post your issue there

**Comment by vehosah** [comment]
Oh I put it already, should I close this? oh by the way I'm using toxandroidreflmpl

**Comment by zoff99** [comment]
yes close this one.
https://github.com/zoff99/ToxAndroidRefImpl/issues/445
