### ISSUE TITLE
meybe add https://radicle.xyz/ repo

### ISSUE THREAD

**Issue by bialystok** [TokTok/c-toxcore#2746]
Spam deleted

**Comment by bialystok** [comment]
? seriosly? social p2p network is clasyfied as spam?

**Comment by JFreegman** [comment]
> ? seriosly? social p2p network is clasyfied as spam?

Please don't post unsolicited links to random websites. Moreover, your request makes no sense. We don't manage third party repositories or have any lists to add them to.
