### ISSUE TITLE
Tox Multi-hop routing

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [TokTok/c-toxcore#2802]
The biggest mistake Tox made 😮‍💨
It's okay to expose your IP in a free country.
It's fatal to expose your IP in a non-free country.

Onion routing is only used for friend requests, not for establishing communication. Once a user accepts a friend request, the communication between the two users will be direct peer-to-peer, minimizing latency. This will have the side effect of exposing their IPs to each other

# Tox  Multi-hop routing
> This is an optional option: the user can enable or disable.

Will not leak user IP

```
Bob ---> Bootstrap Nodes 1 ---> Bootstrap Nodes 2 ---> Bootstrap Nodes 3 ---> Alice

Bob <--- Bootstrap Nodes 2 <--- Bootstrap Nodes 1 <--- Bootstrap Nodes 3 <--- Alice
```

If I need to use an http socks proxy to be anonymous, why would I use Tox instead of SimpleX?

**Comment by JFreegman** [comment]
Complaining about Tox not providing anonymity is a bit like picking up a hammer and complaining that it can't cut your 2x4 in half. Our goal is to provide private/secure communications and censorship resistance - to allow people the ability to have conversations with their friends and family members without having to worry about third parties eavesdropping or preventing them from communicating. For further elaboration, see: https://toktok.ltd/mission

Having reliable anonymity built-in would severely degrade network performance, particularly for audio/video and file transfers, and for most people it's simply unnecessary. For those who do require it, it's very easy to use proxies over-top.

**Comment by nurupo** [comment]
That's the intended behavior. Use Tox over Tor if you want anonymity.

**Comment by iphydf** [comment]
The moment tox becomes tor (by replicating its functionality), it will be blocked all the same. Implementing this in tox won't solve any longer term problems. Thanks for the suggestion.
