### ISSUE TITLE
Offline peers in public group chats cannot rejoin password protected groups without losing credentials

### ISSUE THREAD

**Issue by JFreegman** [TokTok/c-toxcore#2806]
If a founder sets or changes the password of a group, all peers who are offline at the time of this state change will be unable to rejoin the group when they come back online even if they know the password, unless they manually exit the group and join it again with the `tox_group_join` function (e.g. `/close` and then `/join <ID> <password>` in toxic). This causes them to lose their credentials (group identity and group role). 

To properly address this we need to add an optional password parameter to the `tox_group_reconnect` function.

**Comment by iphydf** [comment]
Can we change "join" to also handle reconnect?

**Comment by JFreegman** [comment]
> Can we change "join" to also handle reconnect?

We could possibly make it so that if a client calls the join function on a group that it's already in it will reconnect. Will have a deeper look into that when I get a chance.
