### ISSUE TITLE
Tox cannot connect

### ISSUE THREAD

**Issue by tobiasBora** [TokTok/c-toxcore#283]
Hello,

First, thank you, Tox is a great program ! I'm using (u/q)Tox with a friend, and since a few weeks (she didn't do any update) she cannot be connect to the Tox network anymore from her flat using both uTox and qTox (the internet provider provides internet for students, I'm not aware of the network architecture, but basically she needs to authenticate from a web page in order to get internet). The strange think is that it works elsewhere (at home), and that it worked a few month ago, so I think that the internet provider changed it's policy, or the network map... The "bug" is that utox and qtox never get connected, the (usually green) dot stay grey. So here are my questions:

- is it possible to change the port used by tox ? Maybe the internet provider choose to close the corresponding port, and it would be nice to change the port to test
- how could I debug it to know why it doesn't work anymore ? Do you have any idea ?

Thank you in advance for your help, 

tobiasBora.

**Comment by GrayHatter** [comment]
What is the operating system it's running on?

**Comment by tobiasBora** [comment]
It's Xubuntu 16.04. Installed from the tox repositories.

**Comment by GrayHatter** [comment]
Assuming you're on uTox... Can you run it from the terminal with `-vvvv` and past the output somewhere?

You may want to redact the output, as it will include your ToxID if you want that to remain private.

**Comment by tobiasBora** [comment]
Yes, here is the output. She also tried with UDP/IPv6 off.

```
me@mycomputer:~$ utox -vvvv
Setting theme to:	0
have GTK
Using unencrypted save file; this is insecure!

CORE:	Creating New Toxcore instance.
		IPv6 : 1
		UDP  : 1
		Proxy: 0  0
Avatars:	Unable to get saved avatar from disk for friend 0
History:	Unable to access file provided by native_load_chatlog_file()
If there's a friend history,there should be an error here...
Tox ID: <my TOX ID>
Avatars:	Unable to get saved avatar from disk for friend 4294967295
Toxav thread init
desktop: 1366 768
uToxAudio:	frame size: 960
uToxAudio:	input device list:
	Audio interne Stéréo analogique
	Monitor of Audio interne Stéréo analogique
uToxAudio:	output device list:
	Audio interne Stéréo analogique
AL lib: (WW) alcCloseDevice: Releasing context 0x7fd11000ac70
Video size: 640 480
uToxVideo:	video init done!
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data 
[20:36:34] <pseudo>: written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
Toxcore:	Unencrypted save data written
uTox:	Writing uTox Save
Toxcore:	Unencrypted save data written
XLIB main:	Clean exit
```

Thank you for your help !

**Comment by tobiasBora** [comment]
Do you know what could be the reason of the bug ?

**Comment by GrayHatter** [comment]
I don't other than to say it's being blocked by the network. 

If you're able to compile from source, I can give you an update nodes list to try (I'm just going to remove all the nodes that don't run on port 443) And see if they're just using simple packet shaping.

**Comment by tobiasBora** [comment]
Yes, I think I can compile it from source. Which version should I compile ?

The nodes are on port 443 ? I don't see how the network can block this port since most website use it...

And I don't understand what you mean with "See if they're just using simple packet shaping".

**Comment by GrayHatter** [comment]
The vast majority of nodes are not on port 443, that's why I'm hopeful that if you are able to compile a version of uTox with only nodes on port 443, and TCP only, it will work.

Compile the development branch of uTox https://github.com/uTox/uTox/ once you're able to compile, ping me, and I'll give you a file to replace, before you recompile.

**Comment by tobiasBora** [comment]
I can compile it without any problem, I made a docker that compile & run it here: https://github.com/tobiasBora/docker-tox-git-pulseaudio. What should I do next ?

**Comment by GrayHatter** [comment]
sorry for the delay, replace the file `src/tox_bootstrap.h` with the following data

```c
#ifndef TOX_BOOTSTRAP_H
#define TOX_BOOTSTRAP_H

struct bootstrap_node {
    char *   address;
    uint16_t port;
    uint8_t  key[32];
} bootstrap_nodes[] = {
    {   "185.14.30.213", 443,
        {0x25, 0x55, 0x76, 0x3C, 0x8C, 0x46, 0x04, 0x95, 0xB1, 0x41, 0x57, 0xD2, 0x34, 0xDD, 0x56, 0xB8, 0x63, 0x00, 0xA2, 0x39, 0x55, 0x54, 0xBC, 0xAE, 0x46, 0x21, 0xAC, 0x34, 0x5B, 0x8C, 0x1B, 0x1B }
    },
    {   "2a00:1ca8:a7::e8b", 443,
        {0x25, 0x55, 0x76, 0x3C, 0x8C, 0x46, 0x04, 0x95, 0xB1, 0x41, 0x57, 0xD2, 0x34, 0xDD, 0x56, 0xB8, 0x63, 0x00, 0xA2, 0x39, 0x55, 0x54, 0xBC, 0xAE, 0x46, 0x21, 0xAC, 0x34, 0x5B, 0x8C, 0x1B, 0x1B }
    },
    { "104.219.184.206", 443,
      {0x8C, 0xD0, 0x87, 0xE3, 0x1C, 0x67, 0x56, 0x81, 0x03, 0xE8, 0xC2, 0xA2, 0x86, 0x53, 0x33, 0x7E, 0x90, 0xE6, 0xB8, 0xED, 0xA0, 0xD7, 0x65, 0xD5, 0x7C, 0x6B, 0x51, 0x72, 0xB4, 0xF1, 0xF0, 0x4C,}
    },
    { "194.249.212.109", 443,
      {
          0x3C, 0xEE, 0x1F, 0x05, 0x40, 0x81, 0xE7, 0xA0, 0x11, 0x23, 0x48, 0x83, 0xBC, 0x4F, 0xC3, 0x9F,
          0x66, 0x1A, 0x55, 0xB7, 0x36, 0x37, 0xA5, 0xAC, 0x29, 0x3D, 0xDF, 0x12, 0x51, 0xD9, 0x43, 0x2B,}
    },
};

#endif
```

**Comment by tobiasBora** [comment]
Great, thank you a lot for your help. Now I'll give that to my friend to try it, I'll let you know if it works.

Thank you !

PS: If someone wants to try it, I put the docker file in the branch "bootstrap_443" of https://github.com/tobiasBora/docker-tox-git-pulseaudio/.

**Comment by palikacska** [comment]
Two of the mentioned nodes **104.219.184.206** and **194.249.212.109** don't work anymore (or at the moment) and I don't see **46.101.197.175** anywhere. By the way, how can the third field (the byte array) be extracted from [this node list](https://wiki.tox.chat/users/nodes)?

What is the `{0x??, 0x??, ...` part for **46.101.197.175** with public key `2555763C8C460495B14157D234DD56B86300A2395554BCAE4621AC345B8C1B1B`?

**Comment by GrayHatter** [comment]
That's the public key of the node. In the hex format that toxcore needs.

**Comment by palikacska** [comment]
Good. Thanks. I just messed up my perl script that converted it into C-style byte array and it confused me because the result was much shorter. :P

**Comment by tobiasBora** [comment]
Sorry for the time I spent to give you the feedback, but indeed when I run uTox on ports 443 it works great. So if it was possible to set up a way to connect to port 443 first, or only allow only a subset of ports it would be great !

Thank you !
