### ISSUE TITLE
User Feed

### ISSUE THREAD

**Issue by abueide** [TokTok/c-toxcore#290]
Opening this issue for discussion of a user feed (something akin to a facebook wall).

**Comment by abueide** [comment]
Some spitball ideas:
1) It might make sense to be implemented via torrents somehow. This way users could help seed popular user feeds/pages, rather than just the host.
2) An option to respond to feed requests only if the requester is in the friend list. (Of course friends would also then be able to leak the wall to other people)
3) Option to sign the feed so users can verify the feed came from a certain tox id, and was not tampered, even if you didn't receive the feed directly from the original tox id.

**Comment by SkyzohKey** [comment]
I can only approve that idea as I'm wanting to add something like that to Ricin, i guess it could make Tox more "social".

The way i see it would simply be a welcome screen with latest friends status updates and events (ie. birthdays, etc)

**Comment by abueide** [comment]
@SkyzohKey There was discussion in irc that this wouldn't belong in toxcore.

**Comment by Renha** [comment]
there are ZeroNet and many others for such functions
