### ISSUE TITLE
Don't build nTox by default with CMake

### ISSUE THREAD

**Issue by zetok** [TokTok/c-toxcore#292]
There should be an opt-in option instead, just like with autotools.

**Comment by robinlinden** [comment]
There is a cmake flag for it, actually. 
https://github.com/TokTok/c-toxcore/blob/master/CMakeLists.txt#L483

**Comment by zetok** [comment]
Good, then someone with knowledge how to enable CMake options should make a PR to

* switch it to `OFF` by default
* test scripts should enable it
* add docs in INSTALL.md on how to enable it using CMake
