### ISSUE TITLE
network test (Failed)

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#300]
93% tests passed, 1 tests failed out of 15

Total Test time (real) = 209.03 sec

The following tests FAILED:
	  7 - network (Failed)
Errors while running CTest
make: *** [test] Error 8

make test returned exit code 2

**Comment by zoff99** [comment]
test 7
      Start  7: network

7: Test command: /home/ubuntu/c-toxcore/auto_network_test
7: Test timeout computed to be: 0
7: Running suite(s): Network
7: 50%: Checks: 2, Failures: 1, Errors: 0
7: /home/ubuntu/c-toxcore/auto_tests/network_test.c:66:F:addr_resolv_localhost:test_addr_resolv_localhost:0: Expected family AF_INET6 (10), got 2.
 7/15 Test  #7: network ..........................***Failed    0.01 sec

**Comment by zoff99** [comment]
adding the missing entry to /etc/hosts did fix the test:
```
sudo bash -c "echo '::1             localhost ipv6-localhost ipv6-loopback' >> /etc/hosts"
```


      Start  7: network

7: Test command: /home/ubuntu/c-toxcore/auto_network_test
7: Test timeout computed to be: 0
7: Running suite(s): Network
7: 100%: Checks: 2, Failures: 0, Errors: 0
 7/15 Test  #7: network ..........................   Passed    0.00 sec

**Comment by GrayHatter** [comment]
we've chosen not to enable `sudo` on most of our Travis-CI builds to save everyone time and resources.

**Comment by zoff99** [comment]
just as info. i think maybe there should be an extra test for IPv6 ?
the test fails because localhost can't be resolved via IPv6

**Comment by GrayHatter** [comment]
Travis has many IPv6 issues. But I don't see the test failure you're referencing here.

**Comment by zoff99** [comment]
i never said "travis". it's an info to argue that there should be an IPv6 test.
i am closing the issue.

**Comment by iphydf** [comment]
> i am closing the issue.

I'm doing this on behalf of @zoff99. Please reopen and give it a better title if there is anything left to do here.
