### ISSUE TITLE
Review TES and port it to APIDSL

### ISSUE THREAD

**Issue by nurupo** [TokTok/c-toxcore#308]
As mentioned in #307, TES seems to be somewhat poorly written, for example, `tox_get_salt()` function doesn't check if `salt` has enough space to store the entire salt, nor does the documentation to `tox_get_salt()` mention anything about the salt being `TOX_PASS_SALT_LENGTH` in size. We should really consider reviewing the TES module and porting its interface to APIDSL.

**Comment by iphydf** [comment]
#310 adds an initial apidsl file. Doc changes still need to happen. We probably also need to change apidsl a bit to better support the TES use case.

**Comment by iphydf** [comment]
Fixed in #310.
