### ISSUE TITLE
Improving security through better use of nonces

### ISSUE THREAD

**Issue by arucard21** [TokTok/c-toxcore#356]
As requested, this is a summary of https://github.com/irungentoo/toxcore/issues/1313. More details can be found there. Keep in mind that the discussion was held a while back so some details may no longer match against the current protocol/codebase. 

*Basic idea*
The basic idea is that security can be improved through a better use of nonces. Specifically, the nonce can be used to prevent replay attacks, if used correctly. To do this, a nonce must be different for every message between a sender and receiver. This is currently done on the sender's side, but it isn't verified on the receiver's side, which still makes replay attacks possible. A common tactic that allows clients to verify that a nonce is only used once, is to use strictly increasing nonces. This means the sender will always increase the nonce value, so the receiver can verify that the received nonce is larger than the previously received nonce value from this sender. Note that the sender and receiver for a request message have their roles reversed for the corresponding response message, as the sender of the response is the receiver of the request and the receiver of the response is the sender of the request. These responses will also need their own nonce value which must be different from the nonce value in the request, and should in fact belong to an entirely different strictly-increasing set of nonce values. 

*Proposed implementation*
The proposal is to have the receivers verify that the nonce values are unique, e.g. by making them strictly increasing. The Ping messages can be used as nonce announcements and acknowledgements, which allows for optimizing the communication between the sender and receiver. These nonce announcements will be used to send the full nonce value to a receiver. The nonce values will be predictably incremented on both the sender and receiver's side (e.g. +1). Each encrypted message will then only need to carry a nonce_offset value or the last few bytes of the nonce value, to allow the client to verify that it has calculated the correct new nonce value for this encrypted message. 

*Plan for implementation*
* Make the sender send strictly increasing nonce values and have the receiver verify that the current nonce value in each encrypted message is larger than the last known nonce value for this sender (this will prevent replay attacks, the rest is just optimization)
* Use the ping messages to send the full nonce value as announcement and acknowledgement
* Reduce the size of the nonce values in each encrypted message to just an offset or last few bytes.

**Comment by iphydf** [comment]
Thanks. If I understand correctly, this is a protocol breaking change. As such, I have assigned it to the preliminary 0.3.0 milestone, as I doubt we can implement this before 0.2.0.

**Comment by arucard21** [comment]
Closing since this no longer seems relevant.
