### ISSUE TITLE
Network settings can't be changed without creating new Tox instance 

### ISSUE THREAD

**Issue by GrayHatter** [TokTok/c-toxcore#358]
Clients should be able to modify network settings without toxcore needing to reload 'everything'.

**Comment by nurupo** [comment]
Changing [network options](https://github.com/TokTok/c-toxcore/blob/a096c71db867ac83fc3e01e0fbe98573d20f9286/toxcore/tox.h#L494-L591) would require Tox to disconnect from the network in most (all?) of the cases, which is very close to re-creating Tox instance with the desired network options using the savedata of the previous Tox instance. Proper implementation of changing network options without the need to recreate Tox instance sounds like a difficult change.

**Comment by iphydf** [comment]
What things concretely would you like to see not be reloaded? Assigning to "the far future" for now.

**Comment by iphydf** [comment]
Reload through reinit simplifies code a lot. I'd rather not make it more complex.
