### ISSUE TITLE
Unused shared libraries

### ISSUE THREAD

**Issue by NicoHood** [TokTok/c-toxcore#359]
If I try to compile c-toxcore on archlinux I get the following warnings from namcap:

```
toxcore W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/bin/DHT_bootstrap')
toxcore W: Unused shared library '/usr/lib/libm.so.6' by file ('usr/lib/libtoxcore.so.0.0.0')
toxcore W: Unused shared library '/usr/lib/libm.so.6' by file ('usr/lib/libtoxdns.so.0.0.0')
toxcore W: Unused shared library '/usr/lib/librt.so.1' by file ('usr/lib/libtoxdns.so.0.0.0')
toxcore W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/libtoxdns.so.0.0.0')
toxcore W: Unused shared library '/usr/lib/libm.so.6' by file ('usr/lib/libtoxencryptsave.so.0.0.0')
toxcore W: Unused shared library '/usr/lib/librt.so.1' by file ('usr/lib/libtoxencryptsave.so.0.0.0')
toxcore W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/libtoxencryptsave.so.0.0.0')
toxcore W: Unused shared library '/usr/lib/librt.so.1' by file ('usr/lib/libtoxav.so.0.0.0')
toxcore W: Unused shared library '/usr/lib/libsodium.so.18' by file ('usr/lib/libtoxav.so.0.0.0')
toxcore W: Unused shared library '/usr/lib/libm.so.6' by file ('usr/lib/libtoxav.so.0.0.0')
```

The libpthread one can be ignored, but the rest can possibly fixed.

**Comment by NicoHood** [comment]
Looks like autotools to me:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/toxcore

cc @farseerfc

**Comment by farseerfc** [comment]
@NicoHood we might need to pass arguments to cmake to specifically enable tests, as we did with autoconf. I will try rebuild c-toxcore with cmake.

**Comment by farseerfc** [comment]
I just find out with cmake, the tests will be automatically enabled when `check` is installed. And we have to use `make test` instead of `make check` for cmake generated Makefile.

I have successfully passed `make test`, but there are still some warnings from namcap:
```
toxcore W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/libtoxcrypto.so')
toxcore W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/libtoxfriends.so')
toxcore W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/libtoxmessenger.so')
toxcore W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/libtoxgroup.so')
toxcore W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/libtoxcore.so')
toxcore W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/libtoxdns.so')
toxcore W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/libtoxencryptsave.so')
```

The full build log is here: https://cfp.vim-cn.com/cbcNr

**Comment by iphydf** [comment]
Ok, this will be resolved when we get to fix #14. In the meantime, pthread will be linked unnecessarily. I'm happy if it's only pthread.

**Comment by farseerfc** [comment]
Thanks for the explanation. 
A following question, with autotools I get so files with soname like:
```
toxcore /usr/lib/libtoxcore.so
toxcore /usr/lib/libtoxcore.so.0
toxcore /usr/lib/libtoxcore.so.0.0.0
```
but with cmake, only so file is generated:
```
toxcore /usr/lib/libtoxcore.so
```
Is this expected?

I am asking this because all other tox clients (toxic, qtox, tuntox) seems to linked against soname file currently. I will need to rebuild all of them if I switch to cmake.

**Comment by jin-eld** [comment]
Can't comment on cmake, but just to clarify: autotools uses the libtool versioning scheme, i.e.: .so.X.X.X where the X numbers provide information on ABI compatibility between different library versions.

I do not know if something like that exists for cmake, but imho it's a good thing to have.

**Comment by cebe** [comment]
> but with cmake, only so file is generated:

CMake needs to be configured for this:

> https://cmake.org/cmake/help/v3.0/command/install.html
>  See the VERSION and SOVERSION target properties for details on creating versioned shared libraries.

> https://cmake.org/cmake/help/v3.0/prop_tgt/SOVERSION.html#prop_tgt:SOVERSION

**Comment by cebe** [comment]
Sent a PR to add it.

**Comment by iphydf** [comment]
@cebe after accepting your invitation, please assign this issue to yourself.

**Comment by iphydf** [comment]
Also, close it once you've submitted the PR.

**Comment by cebe** [comment]
@iphydf My PR is not about the original issue but about this comment: https://github.com/TokTok/c-toxcore/issues/359#issuecomment-270710463

**Comment by iphydf** [comment]
@jin-eld are you interested in fixing this on the autotools side?

**Comment by jin-eld** [comment]
OK I'll have a look

**Comment by iphydf** [comment]
@NicoHood does this still happen? We've added shared library versioning by now and redone some of the build system.

**Comment by NicoHood** [comment]
@farseerfc Should be able to answer that, he is maintaining the toxcore for archlinux. Could you please help?

**Comment by farseerfc** [comment]
@iphydf Currently on Archlinux we are using cmake to make c-toxcore.
The symbol links are correctly generated:
```
toxcore /usr/lib/libtoxcore.so
toxcore /usr/lib/libtoxcore.so.1
toxcore /usr/lib/libtoxcore.so.1.11.0
```

So I think this issue is now fixed.

**Comment by NicoHood** [comment]
@farseerfc I tried to rebuild toxcore myself but some tests failed. Those must have been working when you compiled toxcore. Since I am building in a chroot it must work idential. Any ideas what is wrong?
```
70% tests passed, 6 tests failed out of 20

Total Test time (real) = 460.57 sec

The following tests FAILED:
	  3 - conference (Failed)
	  4 - crypto (Failed)
	  8 - network (Failed)
	 13 - tox (Failed)
	 14 - tox_many (Failed)
	 15 - tox_many_tcp (Failed)
Errors while running CTest
make: *** [Makefile:95: test] Error 8
```

**Comment by farseerfc** [comment]
@NicoHood Yes, tests fail (randomly?) on my machines too. I suspect the result depends on the network environment. Running the exact same PKGBUILD with `extra-x86_64-build` again and again will eventually success. My experience is that putting the machine into an idle state with no extra network programs will increase the possibility of success.
This problem may belong to a new issue.

**Comment by iphydf** [comment]
Reopen if this is still an issue.
