### ISSUE TITLE
Detect availability of weak symbols and use it in `crypto_mem*`

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#365]
See https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/utils.c#L125

Also see https://github.com/jedisct1/libsodium/blob/master/configure.ac#L629-L640

**Comment by GrayHatter** [comment]
Is this suggestions just to prevent the compiler from dropping these functions if lto are enabled?

If so, wouldn't it be better to write a conditional that generates an error if memzero didn't take place? In other libs, I say throwing an error in this case wouldn't be acceptable, but I think in ours it's something we might want to do. Given that (unless I'm mistaken), it'll also have the nice side effect of restricting the compiler from omitting the memzero() function?
