### ISSUE TITLE
Invalid bit rate prevents call

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#375]
https://github.com/TokTok/c-toxcore/blob/master/toxav/toxav.c#L273

if i call toxav_call to initiate a call, and i do not specify a valid audio bit rate, then it will not even ring.
it will fail with TOXAV_ERR_CALL_INVALID_BIT_RATE

video bit rate checking is totally disabled: https://github.com/TokTok/c-toxcore/blob/master/toxav/toxav.c#L1016

is that ok? seems strange.
i think i should be able to make a call without audio (audio_bit_rate=0)

**Comment by GrayHatter** [comment]
You're trying to start a call without audio or video... https://github.com/TokTok/c-toxcore/blob/master/toxav/toxav.h#L229 

Can you describe a case in which anyone would need to do that?

**Comment by zoff99** [comment]
when you dont have audio. then a bitrate > 0 would in fact be wrong.
also i don't see why this should be checked at this point.
why is it not allowed to ring the other person, without bitrate?

and here also is (at least) a documentation bug:
https://github.com/TokTok/c-toxcore/blob/master/toxav/toxav.h#L229
if you set to 0 to disable toxav_call will fail.

**Comment by GrayHatter** [comment]
Right, you can start a toxav call, with audio and/or video. You can not start a toxav call with audio and/or/neither video.

When would you want to start a toxav call without audio, and without video?

**Comment by zoff99** [comment]
no. you dont understand!
now you can not start a call with only video. it will fail.

also that's not the point :-)

https://github.com/TokTok/c-toxcore/blob/master/toxav/toxav.h#L229
says it should work. so either the documentation is wrong or the implementation.

also nobody knows what valid bitrates are. there should be a TOXAV_BITRATE_AUDO_MINIMUM
or something like that. otherwise everybody has to look at the source what is valid.
and if it changes client apps will not know it
