### ISSUE TITLE
Roadmap toxcore

### ISSUE THREAD

**Issue by alexeysvrv** [TokTok/c-toxcore#382]
Guys, I would like to discuss how development involves toxcore to its full functional release 1.0? Interested especially how to develop the functionality in the transition from one major version to another? What plans are built? For example, what will be the changes in versions 0.2.x or 0.3.x? I wish that there were published plans to develop. Thank you

**Comment by GrayHatter** [comment]
@alexeysvrv we don't have any sort of long planned out roadmap past the next few versions here => https://github.com/TokTok/c-toxcore/milestones 

We certainly any help, if you want to create a full length roadmap anyone on IRC can help you sort out the bigger points on the map.

**Comment by iphydf** [comment]
We have a published automatic roadmap consisting of github issues and pull requests: https://toktok.ltd/roadmap/c-toxcore.
