### ISSUE TITLE
TODO: add cmake instructions in README.md

### ISSUE THREAD

**Issue by zetok** [TokTok/c-toxcore#383]
Aside from the default autotools instructions there should be docs on building toxcore with cmake.

Given that currently cmake build isn't as easy to use as autotools one, cmake instructions should be added without removal of autotools instructions and mention that cmake might not yet provide same level of functionality as autotools.

**Comment by Zer0-One** [comment]
@zetok currently, what is the difference in functionality?

**Comment by iphydf** [comment]
@nurupo this is done, right?
