### ISSUE TITLE
Stateless callbacks in toxcore's public API

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#40]
**What are we doing?**

We are moving towards stateless callbacks. This means that when registering a
callback, you no longer pass a user data pointer. Instead, you pass a user data
pointer to tox_iterate. This pointer is threaded through the code, passed to
each callback. The callback can modify the data pointed at. An extra indirection
will be needed if the pointer itself can change.

**Why?**

Currently, callbacks are registered with a user data pointer. This means the
library has N pointers for N different callbacks. These pointers need to be
managed by the client code. Managing the lifetime of the pointee can be
difficult. In C++, it takes special effort to ensure that the lifetime of user
data extends at least beyond the lifetime of the Tox instance. For other
languages, the situation is much worse. Java and other garbage collected
languages may move objects in memory, so the pointers are not stable. Tox4j goes
through a lot of effort to make the Java/Scala user experience a pleasant one by
keeping a global array of Tox+userdata on the C++ side, and communicating via
protobufs. A Haskell FFI would have to do similarly complex tricks.

Stateless callbacks ensure that a user data pointer only needs to live during a
single function call. This means that the user code (or language runtime) can
move the data around at will, as long as it sets the new location in the
callback.

**How?**

We are doing this change one callback at a time. After each callback, we ensure
that everything still works as expected. This means the toxcore change will
require 15 Pull Requests.

**Comment by iphydf** [comment]
All planned toxcore callbacks are now stateless. Still left to do are the toxav callbacks. @mannol and/or @cleverca22, who wants to take them on?

**Comment by alexeysvrv** [comment]
Stateless is done?

**Comment by nurupo** [comment]
Only in toxcore, stateless in toxav part was reverted because it introduced a bug. See #203.

**Comment by iphydf** [comment]
Closing this, as the toxcore callbacks are done. We are tracking toxav progress in #203.
