### ISSUE TITLE
Remove all¹ uses of global state in toxcore

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#405]
There are many instances of global data being used for computations in toxcore. Most of them can cause undefined behaviour when two tox instances run in parallel. We should avoid this and change all of them to use local per-instance state.

¹ Except maybe one.

**Comment by nurupo** [comment]
```
$ readelf -s libtox* | grep OBJECT | awk '{print $8}' | sort | uniq | grep -v '__' | grep -v '^_' | grep -v '@' | grep -v '\.'
addresstext
at_startup_ran
base32
broadcast_count
broadcast_ip_port
cmp_public_key
IDString
lastdump
unix_base_time_value
unix_time_value
```

This seems to list names of global variables, not sure if all of them though. Just grep for them in code and remove them.

**Comment by zugz** [comment]
There's also:
  last_monotime
  add_monotime
both in network.c, inside an #ifdef WIN32.

**Comment by iphydf** [comment]
@zugz is this done?

**Comment by zugz** [comment]
* Tuesday, 2018-01-16 at 11:30 -0800 - iphydf <notifications@github.com>:

>@zugz is this done?

Not quite. There's a TODO in LAN_discovery.c about the globals there. 
Maybe someone who's familiar with that module wants to look at that?

Then there are the timing-related globals which will be dealt with if we 
move to libev. Finally there's at_startup_ran, which I think we want to 
keep.
