### ISSUE TITLE
Remove ToxDNS and related stuff from toxcore

### ISSUE THREAD

**Issue by ovalseven8** [TokTok/c-toxcore#42]
I am not sure if I should post issues here now, but I guess it makes sense because it's the only active repository.

---

There has been the consensus that toxcore should remove ToxDNS at all.

In general, the goal of toxcore is to provide a lighweight, reliable and secure codebase for the clients. The current solution with ToxDNS isn't both secure and decentralized.
Moreover, to use Tox IDs is not such a problem as it probably seems in my opinion. Nonetheless, the clients can of course implement HTTPS lookup services - but that's something that shouldn't be in toxcore.

Here the old issue -> https://github.com/irungentoo/toxcore/issues/1491

---

Added by iphy:
- [x] Antox
- [x] qTox
- [x] Ricin
- [ ] Toxic
- [ ] uTox

**Comment by iphydf** [comment]
@tux3 would qTox mind if toxdns were gone?

**Comment by ovalseven8** [comment]
qTox is using HTTPS lookup, so it shouldn't be a problem.

**Comment by iphydf** [comment]
I'll remove it when qTox removes its use of the toxdns library.

**Comment by tux3** [comment]
Since qTox supports the HTTPS "toxme" API, we should be able to remove toxdns3 support without problems. 
The HTTPS system still suffers from the same centralization and trust issues (it's arguably worse since we don't support key-pinning), I think we'd all be happy to have a secure replacement without sacrificing the convenience.

**Comment by iphydf** [comment]
Specifically, I will remove toxdns when no actively maintained client and library uses it anymore. It has very low maintenance cost, so we can avoid breaking people's code. It would be good if stakeholders were to write in this bug if and when their application stops depending on toxdns, so I know when we can remove it.

**Comment by GrayHatter** [comment]
I have no plans to author support for HTTP[S] name lookups in uTox. 

That said, I do plan to write a name lookup API into toxcore when possible. And develop uTox concurrently with that feature. Once that is done, I plan to drop DNS name support from uTox.

**Comment by ovalseven8** [comment]
No, name lookup shouldn't be handled by toxcore.

**Comment by Diadlo** [comment]
@GrayHatter Why you think, that toxcore, and not a client should provide lookup feature?

**Comment by JFreegman** [comment]
If name lookups can leverage the DHT and be done in a fully distributed way then it's obvious why it would belong in toxcore. However toxcore shouldn't go anywhere near dealing with servers/third party services.

**Comment by GrayHatter** [comment]
I'll agree with @ovalseven8 when he says name lookups shouldn't be handled by toxcore. If he also agrees that Messenger shouldn't be handled by toxcore.

First: Messenger as an application needs to be easy to use.
And: ToxIDs aren't easy to use. 
Thus: Messenger needs to make them easy.

I think simple name lookup/resolution is a familiar and useful solution.

**Comment by geromueller** [comment]
The lookup will be vital for tox when adressing non technical people. To convince more people to use tox, especially on phones, a phone number/book -> tox id solution is required. Otherwise any in my family or any friend will switch.
And leaving that to the clients would end in desaster.
