### ISSUE TITLE
Bandwidth reduction (remove onion)

### ISSUE THREAD

**Issue by fcore117** [TokTok/c-toxcore#421]
Quite critical for first time Tox users who has bandwidth limit by ISP. Grayhatter, comments please as onion removal is your idea.

**Comment by GrayHatter** [comment]
For the record, I don't actually want to remove the onion.

But I do have a plan to reduce data usage, by not using the onion for friend finding.

**Comment by SkyzohKey** [comment]
This issue is more a discussion, and discussions of this type has no reason to stay indefinitely here. Thus closing. You can continue this on IRC.
