### ISSUE TITLE
Cannot build on Windows using MinGW

### ISSUE THREAD

**Issue by Talkless** [TokTok/c-toxcore#429]
Hi,

I am trying to produce buildable qTox on Windows using MinGW (for quite some time actually), and it worked fine until switch to c-toxcore.

Previously, I was building toxcore with automake like this:
```
        autoreconf -i
        ./configure --prefix="${QTOX_DIR}/libs" \
                --disable-ntox \
                --disable-tests \
                --disable-testing \
                --with-dependency-search="${QTOX_DIR}/libs" \
                --disable-shared \
                --enable-static \
                OPUS_CFLAGS="-I${QTOX_DIR}/libs/include/vpx" \
                OPUS_LIBS="-lopus" \
                VPX_CFLAGS="-I${QTOX_DIR}/libs/include/opus" \
                VPX_LIBS="-lvpx
        make
```
It worked find, produced .a libs and working qTox.

Now  autmake build does not produce number of libraries such as toxfrieds, toxdht and others, so I assume automake builds are obsolete?

So, I tried to build with CMake and got this error:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindPkgConfig.cmake:36 (find_package_handle_standard_args)
  cmake/ModulePackage.cmake:13 (find_package)
  CMakeLists.txt:25 (include)
```

Earlier, with automake, I could specify `--with-dependency-search=` and it worked, provided I specified paths where to find dependencies.

Is there a way to avoid pkgconfig using new CMake build setup on Windows?

**Comment by iphydf** [comment]
Automake should still work. What's the error you get there?

**Comment by iphydf** [comment]
Also, cmake is still under construction. In particular, cross compilation is undocumented and possibly more painful than with automake, so that use case should probably be served by automake.

**Comment by Talkless** [comment]
@iphydf I haven’t noticed errors with Automake, will check shortly.

**Comment by Talkless** [comment]
I can see linker warnings such as:
```
libtool: link: warning: library `/c/myqTox/windows/../libs/lib/libsodium.la' was moved.
copying selected object files to avoid basename conflicts...
  CC     ../toxdns/libtoxdns_la-toxdns.lo
  CCLD   libtoxdns.la
```
I am pretty sure that that `.la` file exists, but libtoxdns.a (and others depending on libsodium?) is not linked.

**Comment by Talkless** [comment]
By the way I'm building from 0.1.4 tag.

**Comment by iphydf** [comment]
That means it was intended to be located elsewhere in the file system, and it has a path in the binary that is not equal to the one it's located in. You can probably ignore it.

**Comment by Talkless** [comment]
Here's complete build log: https://gist.github.com/Talkless/53dbfd967e60e86e751cd5003c21f098

File that are created:
```
libtoxav.a
libtoxav.la
libtoxcore.a
libtoxcore.la
libtoxdns.a
libtoxdns.la
libtoxencryptsave.a
libtoxencryptsave.la
```

qTox is still missing (from linker output):

```
ltoxgroup
ltoxmessenger
ltoxfriends
ltoxnetcrypto
ltoxdht
ltoxnetwork
ltoxcrypto
```

**Comment by iphydf** [comment]
Can you build qtox with cmake?

**Comment by Talkless** [comment]
Can't build qTox with CMake, I get `Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`.

Not sure how that would help though, these libs are nowhere to find:
```
bash-3.1$ /usr/bin/find /c/myqTox/libs/ -name "*tox*.a"
/c/myqTox/libs/c-toxcore-0.1.4/build/.libs/libtoxav.a
/c/myqTox/libs/c-toxcore-0.1.4/build/.libs/libtoxcore.a
/c/myqTox/libs/c-toxcore-0.1.4/build/.libs/libtoxdns.a
/c/myqTox/libs/c-toxcore-0.1.4/build/.libs/libtoxencryptsave.a
/c/myqTox/libs/lib/libtoxav.a
/c/myqTox/libs/lib/libtoxcore.a
/c/myqTox/libs/lib/libtoxdns.a
/c/myqTox/libs/lib/libtoxencryptsave.a
```
I just can't find out why toxfriends, toxnetwork and others are not built.

**Comment by iphydf** [comment]
Ok, you may need to edit qtox.pro and remove the friends, network, dht, etc.

**Comment by iphydf** [comment]
@tux3 can qtox.pro be made to try both styles as well, like cmake does?
@jin-eld should we make autotools build those sub-libs as well, or should cmake stop doing that?

**Comment by Talkless** [comment]
OK so you are saying that qTox might not actually need to link to group/messenger/friends/netcrypto/dht/network/crypto libraries?

**Comment by nurupo** [comment]
libtoxcore internally consists of several layers: messenger, friends, etc. The cmake build produces a separate library for each of libtoxcore layers and also libtoxcore library missing all those layers -- you have to link to each of those layer libraries and libtoxcore. The autotools build embeds all those layers inside the libtoxcore library, producing just libtoxcore library -- you have to link just against libtoxcore, as it contains all those layers in it. Now, the qTox build system was written assuming you build toxcore with cmake, assuming you have an empty shell libtoxcore library and all its layers as separate libraries. If you want to use autotools toxcore build, you can modify the qTox build system to remove all those libtoxcore layers and link against just libtoxcore, libtoxav, libtoxencryptsave and libtoxdns (if qTox uses it).

**Comment by jin-eld** [comment]
> should we make autotools build those sub-libs as well, or should cmake stop doing that?

@iphydf I think our overall view was, that both builds should produce exactly the same output, so the remaining question is - which one of them need to be adapted?

I think it's a design decision. Do those separate libraries make sense alone? Or do you always need all of them in order to get somewhere?

I think with libtoxav the separation is pretty clear, you have libtoxcore and if you want to use AV features you link an additional library. What is the case with libtoxencryptsave and libtoxdns? Are these libraries optional? Does it make sense (from the end-user perspective) to use libtoxocore without libtoxencryptsave and/or libtoxdns?

I am not so deep in the project right now to be able to judge that, so please give the above a thought and decide how it should be, I'll then either adapt the autotools build or someone will have to make the changes to cmake. 

It's a pity we don't have a dedicated cmake maintainer whom I could sync with, because ultimately we should decide what build output we want to have and then make sure that both build systems produce it as specified.

**Comment by Talkless** [comment]
Could CMake build be made to work without PKG_CONFIG_EXECUTABLE, by specifying paths manually when building on Windows? It's quite some time passed since I was into this task, but I imagine that's the core issue compared with original toxcore build system.

Also, new qTox seems moved to CMake from QMake, I guess I should check is there changes there...

**Comment by iphydf** [comment]
This should work now.
