### ISSUE TITLE
repo mess

### ISSUE THREAD

**Issue by grinapo** [TokTok/c-toxcore#439]
Since there is no network display for Tox* repos on github due to the large amount of forks there seems to be no way to see which repo merges which one and which one should be, well, used and why.

Would it be possible to update the top of the readme to clarify where this repo stands within the 1039 (and counting) forks and the bunch which are updated periodically? Do you merge any of them here or does yours get merged into the "main" (irungentoo?)? 

(If they don't get merged - is there any reason you don't merge all the changes around, "forcing" others to use your repo as the most complete? :-))

**Comment by GrayHatter** [comment]
This repo is the most up to date, and no one is forced to use this repo, any more than someone is force to drive a Honda instead of a Toyota. Any repo can pull the commit from this one into their own. For all the other repos, only the owner can merge it. TokTok can't force other developers to accept new code.

**Comment by iphydf** [comment]
@grinapo can you file an issue on https://github.com/TokTok/github-tools/issues about generating a repo graph that considers "recently updated"? We can probably just generate that graph once a day. It would also be useful for discovering new, active forks.

**Comment by iphydf** [comment]
Please file an issue on github-tools.

**Comment by grinapo** [comment]
@GrayHatter just to clarify:

- by "forcing" I mean my experience that if there are 50+ repos, and I merge all of their changes into one repo of mine, and I actively keep pulling in others' changes then people start using my repo and they start to create PRs for my repo, since people want to use one with all the fixes instead of picking one with 1/10th of the fixes. :-)
- by pulling I meant to merge foreign changes into this repo (I understand you've already done that)
