### ISSUE TITLE
toxcore continuously disconnects from the network and tries to connect again

### ISSUE THREAD

**Issue by zetok** [TokTok/c-toxcore#440]
Reproducible with higher number of contacts. Initially I could reproduce only on a single profile that had >150 contacts, but it also became a problem even with lower number of contacts (~40-50). Although profile with lower number of contacts doesn't disconnect as often, it still is frequent enough to render tox unusable.

Reproducible when upload bandwidth is ~saturated.

After toxcore disconnects, it tries to connect again, attempting to send a large amount of stuff. This only worsens the network conditions when upload is already saturated.

I didn't have the issue on older (irungentoo's) toxcore.

**Comment by zetok** [comment]
Btw, I think that it's quite big issue, given that after years of using tox I'm now unable to use it.

**Comment by iphydf** [comment]
Does this require those 40-50 friends to be online?

**Comment by iphydf** [comment]
How often does it happen? Is there a way to reliably reproduce this?

**Comment by zetok** [comment]
>Does this require those 40-50 friends to be online?

No. There are usually only ~10% of friends online for both friendlist sizes.

>How often does it happen?

Almost all the time. The time period between "connecting" to the DHT and disconnecting is usually less than 30s. Sometimes it takes a minute or 2 to disconnect.

>Is there a way to reliably reproduce this?

It happens when upload bandwidth is saturated.

----
Regarding "bisect", I've started with toxcore 755f084e8720b349026c85afbad58954cb7ff1d4, issue is still present, although to a lesser degree.

On old toxcore time required to reconnect to the DHT is usually less than 30s, often less than 10s.

New toxcore (v0.1.4) requires >30-60s, often minutes.

On old toxcore, there are contacts that are shown as online, and I can just use it although it disconnects fairly frequently from DHT.

On new toxcore almost all contacts are shown as offline even though they are online; it's not usable.

**Comment by GrayHatter** [comment]
@zetok are you able to install and run wireshark as root?

**Comment by zetok** [comment]
>@zetok are you able to install and run wireshark as root?

Yes.

**Comment by zetok** [comment]
update: turning UDP off ~works around the issue.

TCP-only mode still suffers from contacts being shown as offline (#231) though.

**Comment by zetok** [comment]
update: turning UDP off helps only to lessen the problem, in the end it just takes longer for the problem to occur.

**Comment by iphydf** [comment]
Can't reproduce this right now. If this is still an issue, please reopen.
