### ISSUE TITLE
Can't open profile

### ISSUE THREAD

**Issue by Sorunome** [TokTok/c-toxcore#455]
So, I already mentioned this on IRC a few weeks ago, but i thought i'd open an issue about it: I have an older tox profile which i can't open anymore. It still opens fine with https://github.com/TokTok/c-toxcore/commit/82515f92eecde2dffc0659519317d00459a09239

I am happy to help with any kind of debugging, due to obvious privacy reasons i don't want to share my profile file, though

**Comment by iphydf** [comment]
You've pointed at a commit that can still open it. Have you found the commit that is no longer able to open it? What system are you on (x86, x86_64, Linux, Windows)?

**Comment by Sorunome** [comment]
This one is broken: https://github.com/TokTok/c-toxcore/commit/029c4fb83f66de62428593d86a6493400a8f4b27
I tried those specific ones because they were the ones @robinlinden suggested me via IRC

I use Arch Linux x86_64

**Comment by Sorunome** [comment]
After a lot of debugging and stuff the issue currently appears to be due to running outdated clients......latest toxic and latest qtox both seem to load the profile just fine.

**Comment by SkyzohKey** [comment]
The issue appears to **not** be related with ToxCore. Thus closing. :)
