### ISSUE TITLE
Tox.h doesn't expose the size of the nospam.

### ISSUE THREAD

**Issue by GrayHatter** [TokTok/c-toxcore#456]

**Comment by iphydf** [comment]
In what form should it be exposed? It's a `uint32_t`, and therefore the size is `sizeof(uint32_t)`.

**Comment by gjedeer** [comment]
There's `TOX_PUBLIC_KEY_SIZE` and `TOX_ADDRESS_SIZE`. The latter is defined as

```
#define TOX_ADDRESS_SIZE               (TOX_PUBLIC_KEY_SIZE + sizeof(uint32_t) + sizeof(uint16_t))
```

I guess 
```
#define TOX_NOSPAM_SIZE (sizeof(uint32_t))
```
would do it
