### ISSUE TITLE
Submit toxcore to homebrew

### ISSUE THREAD

**Issue by endoffile78** [TokTok/c-toxcore#463]

**Comment by SkyzohKey** [comment]
@dvor Assigned you as you own a Mac (just guessing since you develop for iOS). I might be wrong so feel free to unassigne yourself if i did shit :)

**Comment by dvor** [comment]
There is already formula for toxcore in homebrew (see https://github.com/Tox/homebrew-tox), I guess we it should be updated to use c-toxcore. There is even a pull request for that https://github.com/Tox/homebrew-tox/pull/34

**Comment by SkyzohKey** [comment]
@dvor so this issue can be closed ?

**Comment by dvor** [comment]
Yes, I think so. Now it is up to @stal888 to merge the pull request.

**Comment by nurupo** [comment]
It won't hurt to have an additional homebrew maintainer, @stal888 could use some help.
