### ISSUE TITLE
P2P offline messaging feature?

### ISSUE THREAD

**Issue by icmtfk** [TokTok/c-toxcore#467]
Let's say Alice(online) sent a message to Bob(offline), but Alice has to stay online in order to deliver that message until they are both online, which is the Pseudo-Offline messaging method. And that is very inconvenient. But what if the message Alice(online) sent to Bob(offline) was forwarded to Carl(online), and when Bob was online again, Carl will send the message to Bob, as a relay. Therefore the sender don't have to stay online to deliver the offline message if there are online friends.
It would be really great if you can add this feature.

**Comment by dvor** [comment]
Proposal for that is under discussion. See https://github.com/anoadragon453/tox-offline-messaging-prop/pull/2

**Comment by SkyzohKey** [comment]
@dvor Linked to the valid proposal, thus closing.
