### ISSUE TITLE
TOX_VERSION_PATCH isn't in sync with the version

### ISSUE THREAD

**Issue by yurivict** [TokTok/c-toxcore#474]
TOX_VERSION_PATCH=5 when the version is 0.1.6

**Comment by cebe** [comment]
@SkyzohKey I think this should be fixed in the next version already, not one after :)

**Comment by nurupo** [comment]
This should have been caught by tests on Travis, but Travis build for some reason doesn't fail when tests fail: https://travis-ci.org/TokTok/c-toxcore/jobs/195715912#L2207-L2230. Don't really understand why it doesn't fail, it's being included into `phase` which has `set -e`.

**Comment by cebe** [comment]
phase has `set -e` but as far as I see the script it calls does not have `set -e`: https://github.com/TokTok/c-toxcore/blob/b2d04eae9d9b76523b877a9e5efd5989f83b143d/other/travis/toxcore-script
