### ISSUE TITLE
CMake can't detect and compile ToxAV on OSX

### ISSUE THREAD

**Issue by GrayHatter** [TokTok/c-toxcore#482]
CMake thinks VPX or OPUS can't be found on OSX so it ignores and/or over-rides `-DBUILD_TOXAV=ON`.

Either way, the CMake file shouldn't ignore it's instructions, when -DBUILD_TOXAV is set to ON, it shouldn't decide it doesn't want to. Regardless of if it thinks VPX and OPUS is available.

**Comment by cebe** [comment]
#483 should fix that.

**Comment by cebe** [comment]
The finding issue is not fixed, just the error message got better.

**Comment by GrayHatter** [comment]
@cebe I was able to fix the issue by forcing a working version of pkg-config.

Up to you if you want to leave this issue open, per the comment in #483, I still think we should be able to override cmake from the cmdline

**Comment by GrayHatter** [comment]
this is fixed
