### ISSUE TITLE
Status callbacks called before status updated

### ISSUE THREAD

**Issue by almindor** [TokTok/c-toxcore#484]
Status callbacks like `tox_friend_status_cb` are called with the new value before the toxcore's internal status for given friend is updated.

This breaks any kind of "generic update" polling logic where all the callbacks might eventually result in a "refresh" call where the user re-queries all the friend status values from toxcore.

It's not strictly a bug but it is a bit surprising.
You can close this issue if there's a logical reason to call the callbacks before updating internal status.

**Comment by iphydf** [comment]
Could you write a test case that exhibits this and add it to this repo? We can then look into fixing that test case.

**Comment by iphydf** [comment]
Callbacks will be reworked.
