### ISSUE TITLE
[suggestion] Tox should allow to recombine split large messages back into a single message

### ISSUE THREAD

**Issue by yurivict** [TokTok/c-toxcore#485]
* PROBLEM

When I paste in a larger text, it gets split in qTox into fixed sized chunks.

This is an obviously undesirable behavior, because it damages larger texts. Users should be able to send messages of any size.

Tox should be able to recombine pieces and present the message the way it was sent.

* SUGGESTION

```tox_friend_send_message``` should accept messages with 64-bit client-generated messageId, 32-bit partNo and 32-bit partCount so that clients will be able to keep track of the individual split messages, and display them as a single message when all parts arrived.

**Comment by Renha** [comment]
> and display them as a single message when all parts arrived.

what to do if not all parts arrived?

**Comment by yurivict** [comment]
> what to do if not all parts arrived?

It should keep such message in the partially arrived state. R out of N parts transmitted.

I am trying to implement this in qTox on the client level using the special marker that the particular Tox message is a part of the larger message. The client will recombine them into one.

**Comment by Renha** [comment]
so, i could send you message
2/2: "deal",
then get bitcoins from you, then send you message
1/2: "no ",
so you will see single message saying "no deal"?

**Comment by yurivict** [comment]
You will sent the message "no deal". It will be split into 1/2 "no "  and 2/2"deal", It will be displayed as a whole only when all sub-messages have arrived.

**Comment by Renha** [comment]
You don't get it. I wouldn't use same client as you, because I am evildoer after all. I will split it by myself, and send parts like I have noted, second first (partCount=2, partNo=2 then partNo=1).

**Comment by Renha** [comment]
> It will be displayed as a whole only when all sub-messages have arrived.

do you mean that message wouldn't be displayed at all until all parts will come?

**Comment by yurivict** [comment]
yes

**Comment by Renha** [comment]
so, I could send you gigabytes of messages without you ever know about it, and with client keeping all of them, all I need to do is never send final message in each sequence?

**Comment by yurivict** [comment]
What prevents you from doing this today?

**Comment by Renha** [comment]
Now you will see all messages I sent to you and block me, in proposed solution you wouldn't ever know someone is sending to you something

**Comment by Renha** [comment]
I'm not against main idea, but it for sure need to be accurately designed and to be in core, not clients

**Comment by yurivict** [comment]
Only if I am looking at Tox. What if I am not here?

**Comment by yurivict** [comment]
You are right, there should be limits set. But they should be set with or without defragmentation.

**Comment by yurivict** [comment]
Now I don't think this should be done on the toxcore level, because it doesn't store anything persistently. This should be done on the client level. That's what I am doing in qTox.

**Comment by yurivict** [comment]
I am 99% done implementing it in qTox, so closing this here.

**Comment by zoff99** [comment]
maybe we should consider writing an mid level library for things like this?
* resumable filetransfers even after restart
* recombine large message

otherwise every client needs to implement those, and it will just create x*times the work and x*times bugs

**Comment by yurivict** [comment]
This would have been ideal to have a mid-level library.

**Comment by yurivict** [comment]
I am going to submit the PR to qTox soon for message defragmentation. It should be possible to move this code into a midlevel library later.
