### ISSUE TITLE
pack_ip_port() does not match the spec

### ISSUE THREAD

**Issue by cebe** [TokTok/c-toxcore#508]
As it has been reported on IRC today:

The [spec](https://github.com/TokTok/spec/blob/228e1c8b10fb3662bfcbd0ad4a37875062d23485/spec.md#onion) says:

> "If IPv4 the format is padded with 12 bytes of zeroes so that both IPv4 and IPv6 have the same stored size. The IP_Port will always end up being of size 19 bytes. This is to make it hard to know if an ipv4 or ipv6 ip is in the packet just by looking at the size."

So this is what should happen:

- an IPv4 is stored as: 1byte for the type + 4 byte for the address + 12byte zeros + 2byte for the port
  1+4+12+2=19
- an IPv6 is stored as: 1byte for the type + 16 byte for the address + 2byte for the port
  1+16+2=19

however the definitions in the [header file](https://github.com/TokTok/c-toxcore/blob/c1e3358dcd144c83579287b34daba4ba5a7b22ff/toxcore/network.h#L177-L181) look like what is in the spec but implementation does not use IP_SIZE but IP4_SIZE:
https://github.com/TokTok/c-toxcore/blob/c1e3358dcd144c83579287b34daba4ba5a7b22ff/toxcore/DHT.c#L343-L345

Which results in IPv4 packets to be 7 bytes instead of 19.

As far as I see, this can not be changed without breaking the protocol.

**Comment by nurupo** [comment]
@irungentoo IPv4 is not being padded by the additional 12 bytes.

**Comment by Diadlo** [comment]
As far as I can see, we can add non-zero (port + zeroes) 12 bytes. It will not break the protocol. I.e. we will have same size for IPv4 and IPv6. But old and new implementation will be able to unpack it

 - Spec: 1byte for the type + 4 byte for the address + 12byte zeros + 2byte for the port
 - Current: 1byte for the type + 4 byte for the address + 2byte for the port
 - New: 1byte for the type + 4 byte for the address + 2byte for the port + 10byte zeros + 2byte for the port

**Comment by cebe** [comment]
@Diadlo This does not help as `unpack_ip_port()` would still return 7 bytes and outer code will try reading the next thing after the port in the padding section.

**Comment by nurupo** [comment]
>\<nurupo\> irungentoo: https://github.com/TokTok/c-toxcore/issues/508
>\<nurupo\> this also affects irungentoo/toxcore
>\<nurupo\> fixing it seems to break the protocol backwards compatibility though
>\<irungentoo\> that's not the same part of the code
>\<irungentoo\> the constant size ip port is for onion packets
>\<irungentoo\> the pack ip port function is for when the ip port is being transmitted like in DHT packets

Sounds like that part of the spec applies only to onion?
