### ISSUE TITLE
Loosing connectivity with all contacts forever, being online

### ISSUE THREAD

**Issue by UralZima** [TokTok/c-toxcore#516]
Hello. I use latest toxic-9999 and tox-9999 on gentoo. Toxic is connected through Tor with udp disabled.
Toxic reports v0.7.2_r1747

After long use, it loose any connectivity with all contacts, but toxic showing it is online. People on qtox seeing me offline forever, me too.

Right after I restart toxic, connectivity is immediately restored and I see online people, and they see me.

This happens every day (or once per 2 days) for long time. Now when people started reaching me by phone, saying WTF where are you on tox? I decided to create this issue.

Please help.

P.S. I created this issue on toxic, they said it is known toxcore bug and they wait while it will be fixed.

**Comment by iphydf** [comment]
If this still happens, please reopen.
