### ISSUE TITLE
tox.h is missing documentation.

### ISSUE THREAD

**Issue by SkyzohKey** [TokTok/c-toxcore#518]
See these lines: https://github.com/TokTok/c-toxcore/blob/master/toxcore/tox.h#L629-L687

**Comment by SkyzohKey** [comment]
@iphydf @nurupo @grayhatter You wrote and pushed these lines, please document them.

**Comment by GrayHatter** [comment]
They're self documenting.

If you can't work out what each function does, crypto libraries aren't for you...

**Comment by SkyzohKey** [comment]
@GrayHatter Everything that is in tox.h aka. THE public API **needs** to be documented. e.e

**Comment by GrayHatter** [comment]
Per IRC; no, that's stupid, and there's nothing that says that. 

And to quote myself...

> If you can't work out what each function does, crypto libraries aren't for you...

**Comment by iphydf** [comment]
These are all generated declarations. I'll add some code to apidsl to generate documentation for them.

**Comment by iphydf** [comment]
Didn't get to it. Apidsl is now dead. At some point we'll have apidsl v2 and generated documentation for all those things.
