### ISSUE TITLE
Add ability to go invisible for some contacts

### ISSUE THREAD

**Issue by UralZima** [TokTok/c-toxcore#522]
Hello. Thank you for great work.
Please add an ability to go invisible for some contacts. I know tox is p2p etc, and it is acceptable to not able to send messages to these contacts. They just must see 'offline' status, and when you unblock them, you are able to chat.
There is some discussion in https://github.com/qTox/qTox/issues/826  and https://github.com/qTox/qTox/issues/2602  so not only  me who need this.

Thanks

**Comment by SkyzohKey** [comment]
:+1: on this. Or implement `tox_self_block_contact` and `tox_self_unblock_contact`. :)

**Comment by iphydf** [comment]
Being invisible in tox is effectively the same as deleting the friend. Clients can implement this by deleting friends and keeping a separate list of friends to be re-added. I'm not wildly opposed to adding this in toxcore, but I'd rather shrink the toxcore api and move logic like that elsewhere.

**Comment by Diadlo** [comment]
@iphydf Unfortunately, client can't readd friend without ToxId, which сould be changed. Will be possible after #264

**Comment by iphydf** [comment]
Clients can implement this.
