### ISSUE TITLE
toxcore cannot bootstrap with UDP when connected to DNS64/NAT64

### ISSUE THREAD

**Issue by dvor** [TokTok/c-toxcore#527]
Cloned from here https://github.com/irungentoo/toxcore/issues/1620

I've tried to submit Antidote to the AppStore but it was rejected by Apple because it doesn't work on NAT64 network.

How to reproduce:
- one computer creates NAT64 wifi network ([instruction for macOS](https://derflounder.wordpress.com/2015/10/05/enabling-an-ipv6-only-network-using-internet-sharing-on-el-capitan/))
- connect other computer (or phone) to this network
- launch tox with installed fresh profile, IPv6 enabled, UPD doesn't matter
- observe
- toxcore cannot connect.

Same issue was observed when using latest uTox and qTox.

If you will switch to normal network, let tox to connect, switch back to NAT64, try to connect again - _sometimes_ it may work, but quite often it doesn't.

-----

Eventually I make it work using TCP only mode. However UDP is still broken. At the moment Antidote is using TCP by default to pass Apple review.

**Comment by GrayHatter** [comment]
@dvor is TCP only an apple thing? Or is TCP only because "don't use insane amounts of bandwidth" is an apple thing?

Also, IIRC this issue exists because apple's implementation of NAT64 is broken? Have you, (or can you) tried to duplicate the issue with a known working implementation of NAT64?

**Comment by dvor** [comment]
> is TCP only an apple thing? Or is TCP only because "don't use insane amounts of bandwidth" is an apple thing?

Yes, TCP is enabled by default because it is required to make Antidote work on NAT64 => pass Apple review and go to the App Store.

I don't think that bandwidth usage is a huge issue as Antidote doesn't run in background for more than few minutes (then it is suspended by iOS). IMO with UDP app works better - on TCP relay there may be small delays in delivering messages, friend goes offline after some time, not immediately, etc.

> Also, IIRC this issue exists because apple's implementation of NAT64 is broken? Have you, (or can you) tried to duplicate the issue with a known working implementation of NAT64?

I haven't tried duplicating the issue on non-apple computer as I don't have one. It would be nice if someone could test it.

**Comment by iphydf** [comment]
Antidote (iOS client) is working now.
