### ISSUE TITLE
c-toxcore on Windows can be compiled using MSYS2 (with modern MinGW-w64)

### ISSUE THREAD

**Issue by DX37** [TokTok/c-toxcore#528]
So... I'm not creating a PR yet, but I have to say - we can build c-toxcore natively and very simple by installing and using [MSYS2](http://www.msys2.org/).

It's very easy to set up environment for compiling. For example, I just install opus, vpx and libsodium (in separated console with pacman as a package manager) from their repo and compiling toxcore just like on Linux. And it's generating static libraries, just like on Linux.

I'm using this modern way to [compile qTox on Windows](https://github.com/qTox/qTox/pull/4291).

**Comment by nurupo** [comment]
Cool. We know that it can be built in MSYS2 with MinGW, but it would be nice to have someone update the build instructions as they are likely severely outdated.

By the way, [you can even compile it in cmd.exe with MSVC](https://ci.appveyor.com/project/iphydf/c-toxcore/build/1.0.425), it will work out of the box for libtoxcore, libtoxdns and libtoxencryptsave, but you'd need to tweak CMakeLists.txt for libtoxav dependencies to get libtoxav to build.
