### ISSUE TITLE
Unable to cross compile (Customizing c-toxcore for audio call only support).

### ISSUE THREAD

**Issue by blprasad** [TokTok/c-toxcore#529]
Hi All,

I am trying to customise c-toxcore, I got error while compiling c-toxcore using cmake,while customizing.
As I don't know where to seek for help, I am trying here. Please guide me .
My objective is to cross compile c-toxcore for Arm architecture.I am trying to remove video call support,but audio call support is needed ,this is my customization.I am trying to modify CMakeList.txt to achive this.So far I could not succeed , I am knew to cmake. I placed libs like libsodium, opus,libsndfile in same path (directory),but cmake has picked only libsodium but its unable to pick OPUS.
Any help is appreciated ,thanks in advance.

here is the error message I get
-- Checking for one of the modules 'libsodium'
-- Checking for one of the modules 'opus'
-- Checking for one of the modules 'vpx'
-- Checking for one of the modules 'libconfig'
-- Checking for one of the modules 'check'
-- Checking for one of the modules 'msgpack'
-- Checking for one of the modules 'opencv'
-- Checking for one of the modules 'portaudio-2.0'
-- Checking for one of the modules 'sndfile'
libsodium: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/usr/lib/libsodium.so
CMake Error at CMakeLists.txt:180 (message):
  Option BUILD_TOXAV is enabled but required library OPUS was not found.

**Comment by blprasad** [comment]
this is where and how i modified CMakeLists.txt ,the following is my only modification and its content 

if(BUILD_TOXAV)
  apidsl(
    toxav/toxav.api.h)
  add_module(toxav
    toxav/audio.c
    toxav/audio.h
    toxav/bwcontroller.c
    toxav/bwcontroller.h
    toxav/msi.c
    toxav/msi.h
    toxav/ring_buffer.c
    toxav/ring_buffer.h
    toxav/rtp.c
    toxav/rtp.h)
  target_link_modules(toxav toxcore ${OPUS_LIBRARIES})
endif()

you may observed I trimmed all neccesary names related video support  

and my toolchain.cmake is attached please have a look and suggest if anything is wrong
[toolchain.txt](https://github.com/TokTok/c-toxcore/files/881761/toolchain.txt)

**Comment by zoff99** [comment]
@blprasad look here how to cross compile c-toxcore for rapberry PI:
https://github.com/zoff99/ToxDoorspy/blob/master/circle.yml

**Comment by nurupo** [comment]
@zoff99 that's irrelevant. the issue he was having is not with cross-compiling, but with removing video support from libtoxav.

**Comment by zoff99** [comment]
hhh?

"My objective is to cross compile c-toxcore for Arm architecture."

**Comment by nurupo** [comment]
@zoff99 The issue was not cross-compiling, but removing video support from libtoxav.

>Customizing c-toxcore for audio call only support


>I am trying to customise c-toxcore


>I am trying to remove video call support


>I am trying to modify CMakeList.txt to achive this

**Comment by blprasad** [comment]
@zoff99 
thanks for your inputs, I will follow your suggestions.one more doubt ,I got the following message at the end of error messages ,along with the messages mentioned above,do they signify anything.

-- Looking for explicit_bzero
-- Looking for explicit_bzero - not found
-- Looking for memset_s
-- Looking for memset_s - not found
-- Configuring incomplete, errors occurred!
See also "/home/prasad/orangepi/c-toxcore-master/build-orangepi/CMakeFiles/CMakeOutput.log".
See also "/home/prasad/orangepi/c-toxcore-master/build-orangepi/CMakeFiles/CMakeError.log".

**Comment by blprasad** [comment]
I could not figure out ,why error log shows OPUS not found,

here is the path to libsodium and other libs i compiled and placed in same location,where libopus is also found, 

cd /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/usr/lib/
root@prasad-laptop:lib# ls
bin        libopus.la        libsndfile.a     libsndfile.so.1.0.27  libsodium.so.18      libtoxcore.so  libtoxencryptsave.a
include    libopus.so        libsndfile.la    libsodium.a           libsodium.so.18.2.0  libtoxdns.a    libtoxencryptsave.la
lib        libopus.so.0      libsndfile.so    libsodium.la          libtoxcore.a         libtoxdns.la   libtoxencryptsave.so
libopus.a  libopus.so.0.5.3  libsndfile.so.1  libsodium.so          libtoxcore.la        libtoxdns.so   pkgconfig
root@prasad-laptop:lib# file libopus.so
libopus.so: symbolic link to `libopus.so.0.5.3' 
root@prasad-laptop:lib# file libopus.so.0.5.3 
libopus.so.0.5.3: ELF 32-bit LSB  shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=35daea98c1b2d4003cb5b86e0df8f699643694c5, not stripped
root@prasad-laptop:lib# file libsodium.so
libsodium.so: symbolic link to `libsodium.so.18.2.0' 
root@prasad-laptop:lib# file libsodium.so.18.2.0 
libsodium.so.18.2.0: ELF 32-bit LSB  shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=a6328c04f8adc6754d4b5b781fce30504b8de832, not stripped

I tried to compile libvpx but i could not succeeds, as i dont need the video support i ignored to try further compile libvpx after several attempts of failure. I tried to build the toxcore without libvpx.If I comment the libvpx related content in CMakeLists.txt ,why it is complaining about libopus which already there inplace.

my CMakeError.log shows something else, as follows , I am attaching my CMakeError.log file
Linking C executable cmTC_f57a5
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f57a5.dir/link.txt --verbose=1
/home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc --sysroot=/home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/arm-linux-gnueabihf/libc  -std=c99 -pedantic -Wall -Wextra -Wno-cast-align -Wno-conversion -Wno-covered-switch-default -Wno-disabled-macro-expansion -Wno-documentation-deprecated-sync -Wno-format-nonliteral -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-padded -Wno-parentheses -Wno-return-type -Wno-sign-compare -Wno-sign-conversion -Wno-tautological-constant-out-of-range-compare -Wno-type-limits -Wno-undef -Wno-unreachable-code -Wno-unused-macros -Wno-unused-parameter -Wno-vla -Wno-assign-enum -Wno-bad-function-cast -Wno-double-promotion -Wno-gnu-zero-variadic-macro-arguments -Wno-packed -Wno-reserved-id-macro -Wno-shadow -Wno-shorten-64-to-32 -Wno-unreachable-code-return -Wno-unused-but-set-variable -Wno-used-but-marked-unused     -rdynamic CMakeFiles/cmTC_f57a5.dir/CheckSymbolExists.c.o  -o cmTC_f57a5
CMakeFiles/cmTC_f57a5.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0xe): undefined reference to `pthread_create'
CheckSymbolExists.c:(.text+0x12): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[1]: *** [cmTC_f57a5] Error 1
make[1]: Leaving directory `/home/prasad/orangepi/c-toxcore-master/build-orangepi/CMakeFiles/CMakeTmp'
make: *** [cmTC_f57a5/fast] Error 2

 
[CMakeError.log.txt](https://github.com/TokTok/c-toxcore/files/901489/CMakeError.log.txt)

**Comment by zoff99** [comment]
@blprasad i don't understand what you are doing?
why don't you FIRST try it the way it works, and only after that start playing around?

**Comment by blprasad** [comment]
@zoff99
Ok, I will try ,thanks

**Comment by zoff99** [comment]
@blprasad what i mean, first fork this repo, login to circleci.com and activate the build there.
now you should have raspberry ARM binaries built. then just start tweaking cricle.yml in your repo until you have what you need.

**Comment by blprasad** [comment]
@zoff99 
It's been a while to be here again,I tried to follow your suggestion ,as I am very new to work with .yml,I am bit worried to follow your way , though ,I tried to observe the commands in of circle.yml to find if I missed anything , and continued with my old procedure,after I used a command from circle.yml
apt-get install libopus-dev on my ubuntu machine , compilation proceeds further, now it's not complaining about "Option BUILD_TOXAV is enabled but required library OPUS was not found." ,though it's bit weird to me .Now I hope I am almost nearing my objective, if I fail in this way, I will definitely follow yours, as I am new to use .yml I am not using it now. I am also new to login to https://circleci.com/ ,I am postponing it.

Now I am trying to modify the CMakeLItst.txt to omit the video call support.Now I get some errors related to header files not found, which I hope can be resolved easily.I will let you know my progress,thanks any way for your help.

**Comment by zoff99** [comment]
@blprasad well, have it your way. you should have started with circleci.com

**Comment by blprasad** [comment]
Some how I compiled the c-toxcore with some modifications ,now it's the time to test it,but I dont know how? how do I get test examples compiled , I found auto_tests directory how to build these examples,
If someone knows how to please guide me , I wish to test it on my target embedded linux board,what files from c-toxcore need to be compied to target and how to test simple call application.

**Comment by blprasad** [comment]
here is the output of make install command
$make install
[  3%] Built target toxcrypto_shared
[  7%] Built target toxnetwork_shared
[ 12%] Built target toxdht_shared
[ 21%] Built target toxnetcrypto_shared
[ 24%] Built target toxfriends_shared
[ 26%] Built target toxmessenger_shared
[ 28%] Built target toxgroup_shared
[ 31%] Built target toxcore_shared
[ 33%] Built target tox_sync
[ 35%] Built target toxdns_shared
[ 37%] Built target dns3_test
[ 39%] Built target Messenger_test
[ 41%] Built target irc_syncbot
[ 44%] Built target DHT_bootstrap
[ 46%] Built target toxdns_static
[ 48%] Built target toxmessenger_static
[ 51%] Built target toxcore_static
[ 54%] Built target toxfriends_static
[ 56%] Built target tox_shell
[ 58%] Built target toxencryptsave_shared
[ 60%] Built target toxgroup_static
[ 67%] Built target toxav_static
[ 70%] Built target toxcrypto_static
[ 74%] Built target toxnetwork_static
[ 79%] Built target toxdht_static
[ 81%] Built target toxencryptsave_static
[ 83%] Built target DHT_test
[ 92%] Built target toxnetcrypto_static
[100%] Built target toxav_shared
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxcrypto.so.1.7.0
and so on is there I am trimming it here.

I wish to build auto_tests where there are some more useful examples but when I make install it doesn't build what is there in auto_tests directory how to achieve that.
and to run toxcore on target machine what need to be copied from host to target and run.please help if anyone tried this earlier.

**Comment by blprasad** [comment]
I couldn't find tox-bootstrapd compiled , I think it should be part make install ,please correct me if I am wrong.

**Comment by blprasad** [comment]
here is the complete output of make install
build-orangepi# make install
[  3%] Built target toxcrypto_shared
[  7%] Built target toxnetwork_shared
[ 12%] Built target toxdht_shared
[ 21%] Built target toxnetcrypto_shared
[ 24%] Built target toxfriends_shared
[ 26%] Built target toxmessenger_shared
[ 28%] Built target toxgroup_shared
[ 31%] Built target toxcore_shared
[ 33%] Built target tox_sync
[ 35%] Built target toxdns_shared
[ 37%] Built target dns3_test
[ 39%] Built target Messenger_test
[ 41%] Built target irc_syncbot
[ 44%] Built target DHT_bootstrap
[ 46%] Built target toxdns_static
[ 48%] Built target toxmessenger_static
[ 51%] Built target toxcore_static
[ 54%] Built target toxfriends_static
[ 56%] Built target tox_shell
[ 58%] Built target toxencryptsave_shared
[ 60%] Built target toxgroup_static
[ 67%] Built target toxav_static
[ 70%] Built target toxcrypto_static
[ 74%] Built target toxnetwork_static
[ 79%] Built target toxdht_static
[ 81%] Built target toxencryptsave_static
[ 83%] Built target DHT_test
[ 92%] Built target toxnetcrypto_static
[100%] Built target toxav_shared
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxcrypto.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxcrypto.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxcrypto.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxcrypto.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxnetwork.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxnetwork.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxnetwork.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxnetwork.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxdht.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxdht.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxdht.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxdht.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxnetcrypto.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxnetcrypto.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxnetcrypto.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxnetcrypto.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxfriends.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxfriends.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxfriends.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxfriends.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxmessenger.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxmessenger.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxmessenger.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxmessenger.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxgroup.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxgroup.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxgroup.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxgroup.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxcore.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxcore.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxcore.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxcore.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxav.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxav.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxav.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxav.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxdns.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxdns.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxdns.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxdns.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxencryptsave.so.1.7.0
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxencryptsave.so.1
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxencryptsave.so
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/libtoxencryptsave.a
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/pkgconfig/libtoxcore.pc
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/pkgconfig/toxcore.pc
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/pkgconfig/toxdns.pc
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/pkgconfig/toxencryptsave.pc
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/include/tox/tox.h
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/include/tox/toxdns.h
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/include/tox/toxencryptsave.h
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/pkgconfig/libtoxav.pc
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/lib/pkgconfig/toxav.pc
-- Up-to-date: /home/prasad/orangepi/zero/gcc-linaro-6.2.1-2016.11-i686_arm-linux-gnueabihf/sysroot/include/tox/toxav.h
root@prasad-laptop:build-orangepi#
