### ISSUE TITLE
Understand and discuss "Tox specification" and rebuild it better!!

### ISSUE THREAD

**Issue by selay01** [TokTok/c-toxcore#531]
### About "Tox specification"：
* **The significance doc "Tox specification" is a goog way to understand the 'Tox Protocol'.**
* web: https://toktok.github.io/spec or https://toktok.ltd/spec
github: https://github.com/TokTok/spec
**_For the two web links,they are all the same at present.But the github is more detailed than the web..._**

## What do we do here?
* discuss the explanation of any thing in "Tox specification" for anyone who want to understand it better
* discuss parts that "Tox specification" should adds
* discus the order and structure of "Tox specification"
* **rebuild it better:**
link things that is related to "Understand and discuss "Tox specification" and rebuild it better!!" to and from here so that people can get more information to understand it better;
contribute to https://github.com/TokTok/spec if you are glad to

## For now:
**the two missing part in "Tox specification":**
* part “terminology definition”:definition of all terminologies,and an alias table;
* part "overall",give a comprehensive description in brief and friendly to an ordinary/advanced users

**order and structure of "Tox specification":**
* what's the best 'order and structure' that it should be?

**Comment by selay01** [comment]
## Resources:
* **Other doc**
[https://zetok.github.io/tox-spec/](https://zetok.github.io/tox-spec/) :similar to ["Tox specification"](https://github.com/TokTok/spec)

**Comment by iphydf** [comment]
Reopen on https://github.com/TokTok/hs-toxcore.
