### ISSUE TITLE
Could it be more stable and fast?

### ISSUE THREAD

**Issue by selay01** [TokTok/c-toxcore#532]
* **_So far, tox client can just send message when both are online._**
* **_It's unstable_**(might because the NAT am I in),**_and not fast enough especially sending a picture or big file, A/V is failed_** so far for me...

### Could it be more stable and fast?
* To answer this quesion,I have opened the issue [https://github.com/irungentoo/toxcore/issues/1638](https://github.com/irungentoo/toxcore/issues/1638).(**_Notice:It has been closed!_**)
* And gived a simple and leaky answer(that you might need to read).

## Notice:
* Because @SkyzohKey sugessests me to open issues about "toxcore" here(@SkyzohKey:Toxcore as moved to a newer repository. ),so I opened the new one.
* Because that just is a simple and leaky answer,I didn't copy anything,but you might need to read that first,in case people talk about it here.

**Comment by Dako300** [comment]
I made a merged PR a while ago that allows audio bitrate to be changed on the fly. Which client are you using? qTox defaults to 64kbps, but voice sounds good down to 6kbps (minimum).

@agrecascino fixed a pretty major audio bug in audio groupchats in qTox after this issue was submitted

**Comment by iphydf** [comment]
Yes, it could be more stable and fast. We're working on it, slowly :).
