### ISSUE TITLE
[WIP] Yet another Java bindings for c-toxcore

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#543]
https://github.com/zoff99/ToxAndroidRefImpl/tree/master/jni-c-toxcore

**not 100% complete yet**, but most stuff is working.

see the "test client" development snapshot that's using it:
https://circleci.com/api/v1/project/zoff99/ToxAndroidRefImpl/latest/artifacts/0/$CIRCLE_ARTIFACTS/ToxAndroidRefImpl.apk?filter=successful&branch=master

**!! Use at your own risk !!**

**Comment by zoff99** [comment]
![CircleCI](https://circleci.com/api/v1/project/zoff99/ToxAndroidRefImpl/latest/artifacts/0/$CIRCLE_ARTIFACTS/capture_app_running.png?filter=successful&branch=master)

**Comment by zoff99** [comment]
no comments at all? not even a small shitstorm?

**Comment by SkyzohKey** [comment]
I tried your implementation, everything works well except the... design xD.
I'm gonna make some mockups for the design and put that in form of view/fragments files if you wish.

Anyway, great job. I'll try to compile it soon, once i succeeded at compiling another android app (NewPipe) ^^

**Comment by nurupo** [comment]
Well, firstly, what you have there is not a reference implementation of toxcore, it's java binding to c toxcore.

Secondly, [we already have java bindings to c toxcore](https://github.com/TokTok/jvm-toxcore-c), so what is the point of making yet another one?

**Comment by zoff99** [comment]
@nurupo if you mean jvm-c-toxcore. its not really usable without scala.
i tried making a test app with it and did not succeed. also i wanted to know where the problems with Antox are. in toxore, in jvmtoxcore or in antox.

and then by accident i wrote a whole damn app

**Comment by zoff99** [comment]
@SkyzohKey 
compile: it gets compiles on circleci, also if you make a PR it will be compiled.
call: it crashes on Android 7.x (still tracking down the issue), can you test with android 6.x or less?

**Comment by zoff99** [comment]
@SkyzohKey dont make mockups please, just tweak the files in "res/" and do it for real.

**Comment by nurupo** [comment]
>@nurupo if you mean jvm-c-toxcore. its not really usable without scala.

No, I meant what I said -- jvm-toxcore-c. You are confusing jvm-toxcore-api and jvm-toxcore-c. jvm-toxcore-c has no Scala code. Did you not look into existing Java bindings before writing your own?

**Comment by zoff99** [comment]
@nurupo yes it did, i compiled it and talked to iphy alot. no matter now, its done

**Comment by SkyzohKey** [comment]
I'm running Android 7.0 too, my laptop isn't enough powerful to run 1 virtual device, sorry. 

@nurupo At least this one compiles on my laptop, where it never was the case with Antox 😂

**Comment by nurupo** [comment]
>i tried making a test app with it and did not succeed. also i wanted to know where the problems with Antox are. in toxore, in jvmtoxcore or in antox.

Ok, just making sure you know that we already have java bindings to c toxcore. It would suck if you didn't know they exist and wasted your time on writing them.

>@nurupo At least this one compiles on my laptop, where it never was the case with Antox :joy:

Yeah, sadly not all software is easy to compile.

**Comment by Diomas** [comment]
Finally there is a scala-free binding to c-toxcore, woohoo! Please, keep going

**Comment by zoff99** [comment]
@Diomas can you help with testing?

**Comment by zoff99** [comment]
@SkyzohKey can you try it now (same link above), it should work on android 7.0
audio is only sent for now (not recevied yet!)

**Comment by SkyzohKey** [comment]
Works!

**Comment by nurupo** [comment]
>No, I meant what I said -- jvm-toxcore-c. You are confusing jvm-toxcore-api and jvm-toxcore-c. jvm-toxcore-c has no Scala code. Did you not look into existing Java bindings before writing your own?

My mistake, looks like jvm-toxcore-c does have scala code, I wasn't looking in the right place.

**Comment by msteinbeck** [comment]
What do you think about generating a Java interface using Swig? Furthermore, Swig would be appropriate to generate bindings for Python, C#, Ruby, Lua, PHP, and other languages as well.

**Comment by iphydf** [comment]
Looks like this is done now.
