### ISSUE TITLE
If Tox already does onion routing, why use Tox over Tor?

### ISSUE THREAD

**Issue by Geremia** [TokTok/c-toxcore#544]
The section "[What is stopping people from tracking me through the public DHT?](https://wiki.tox.chat/users/techfaq#what_is_stopping_people_from_tracking_me_through_the_public_dht)" of the [Technical FAQ](https://wiki.tox.chat/users/techfaq) page says:

> Tox generates a temporary public/private key pair used to make connections to peers in the DHT. Onion routing is used to store and locate Tox IDs, to make it more difficult to, for example, associate Alice and Bob together by who they are looking for in the network. [1](https://github.com/irungentoo/toxcore/blob/5ea703c844b12e86702c35b53b0b798fe5f86634/docs/Prevent_Tracking.txt)

If Tox already uses onion routing, then why use [Tox over Tor](https://wiki.tox.chat/users/tox_over_tor_tot)? What's the difference?

<sup>[cross-posted here](https://github.com/qTox/qTox/issues/4386#issue-227455562)</sup>

**Comment by SkyzohKey** [comment]
Cuz Tox is made for secure instant messaging while Tor is for secure/anonymous browsing.

**Comment by zoff99** [comment]
@Geremia because usually your tox friend does know your ip address. with Tox over Tor he does not

**Comment by nurupo** [comment]
The onion routing is done only within DHT. Once you get the address of your friend from DHT, Tox connects to them directly*.

*unless you have specified to use a proxy or tox couldn't connect directly and used a relay.

**Comment by Geremia** [comment]
@SkyzohKey @zoff99 @nurupo thanks
