### ISSUE TITLE
[Regression] toxcore no longer bootstraps

### ISSUE THREAD

**Issue by zetok** [TokTok/c-toxcore#545]
https://github.com/qTox/qTox/issues/4385#issuecomment-300776499

**Comment by yurivict** [comment]
But qTox-1.9.0 works fine. I thought this was a qTox problem.

**Comment by nurupo** [comment]
Can't reproduce on master head. My test case: https://gist.github.com/nurupo/98e949ad35a5f5615a268edb2c937767

**Comment by nurupo** [comment]
Identified as qTox issue.
