### ISSUE TITLE
toxcore removes message receipts and filetransfers from memory, when client has short network outage

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#548]
when on a mobile phone you can be offline rather often (elevator, parking garage, bad cell service, tunnel ...) then you go offline and online again.
but now you will not receive message read notifications and you lose all FT numbers.
i don't think this is good

https://github.com/TokTok/c-toxcore/blob/master/toxcore/Messenger.c#L930

```
break_files(m, friendnumber);
clear_receipts(m, friendnumber);
```

what if we removed these 2 lines?
(or maybe add a timespan, only when offline for more than 5 minutes lose these values.)
keep the data in memory, like you were online the whole time.

comments?

**Comment by iphydf** [comment]
It's by design. @irungentoo for comments on this design decision.

**Comment by zoff99** [comment]
@iphydf for multidevice and offline messages we need:
peristent msg ids, msg sent date, persistent FT numbers
