### ISSUE TITLE
Invalid tox ID. I get 64 symbols instead of 76

### ISSUE THREAD

**Issue by UralZima** [TokTok/c-toxcore#549]
#Hello. I am tired with that bug. I can't add nobody and always sending them my full tox id to add me. 
Now I received a toxID from _latest_ qtox in windows, and it is again 64 length. 
I use toxic and qtox, both don't accept them. latest toxcore built a few days ago.

Maybe it is possible to add some random data in the end or how else to add these IDs?  Some simple C++ app that calculates rest parts? Why this happens?
Please help.

**Comment by sudden6** [comment]
How do you obtain these ToxIDs? I think you just got a public key, which is not enough to add someone as a friend.

In qTox you have to click on your avatar and click on the Tox ID to copy your own ID.

**Comment by SkyzohKey** [comment]
This is a qTox related issue and has nothing to do with toxcore. Please feel free to reopen this issue on the correct issues tracker => [the qTox issue tracker](https://github.com/qTox/qTox/issues/new)
