### ISSUE TITLE
LAYER #: modules for static linking - build issue

### ISSUE THREAD

**Issue by Axaprj** [TokTok/c-toxcore#566]
Platform: MSYS2 32/64 Windows
Unable to build following static libs:
**toxgroup, toxmessenger, toxfriends, toxdht, toxnetcrypto, toxcrypto, toxnetwork**

What should I do to build them? Will be useful recommendations for any host platform.

PS I successfully make **uTox** static build using toxencryptsave, toxdns, toxav, toxcore only

PSS c-toxcore\CMakeLists.txt:
> what's added to the Libs: line in toxcore.pc. It needs to contain all the libraries a program using toxcore should link against if it's statically linked.

**Comment by SkyzohKey** [comment]
Issue should be fixed once this gets merged: https://github.com/TokTok/c-toxcore/pull/442

**Comment by robinlinden** [comment]
If you want to build all libs you need to use autotools to do it. Our current CMake setup merges most of them together.

**Comment by iphydf** [comment]
@Axaprj does this still occur? #442 is merged. Reopen the issue if it's not fixed.
