### ISSUE TITLE
Run autogen.sh before releases

### ISSUE THREAD

**Issue by josuah** [TokTok/c-toxcore#569]
This would be easier to get started quick with c-toxcore and build the clients if a `./configure` script was already present.

This could be done either by removing [`configure`](https://github.com/TokTok/c-toxcore/blob/master/.gitignore#L51) and keeping it in the tree in master or another "release" branch ?

Even uploading the `./configure` script along with the release, this would also be helpful.  :)

**Comment by nurupo** [comment]
Are you talking about the state of the repository at release tags, or about tarballs, or about both?

I'm not knowledgeable about the gnu die autotools, historically @jin-eld was the one who was supporting it, so I don't know whether it even makes sense to run `autogen.sh` on developer's machine before making a release, but as far as I see, it's common to have `autogen.sh` script and no `configure`, e.g.

```sh
git clone git://git.opus-codec.org/opus.git
cd opus
git checkout v1.2.1
./autogen.sh
```

```sh
git clone https://github.com/jedisct1/libsodium
cd libsodium
git checkout 1.0.12
./autogen.sh
```

**Comment by josuah** [comment]
It is true that it is rare to have autotools's .`/configure` shipped with the git repository.

The `./autogen.sh` is here to ease the *developpers* to build the configure script with the help of the autotools to prepare a release.

1. The autotools (with help of `configure.in` and `Makefile.in`) build a shell script that only uses POSIX tools, that is specific to the *project*.
2. On the user side, this script is executed, which detects the configuration of the user to produce a *user-specific* `Makefile`.
3. The `Makefile` is being executed as you know.

**Comment by josuah** [comment]
So as long as the structure of the project remains the same (libraries used, location of the files and whatnot), the configure script does not change.  That is why it is often shipped in releases (tarballs) and that only `autogen.sh` is kept in git HEAD.

 ```
wget -O - https://archive.mozilla.org/pub/opus/opus-1.2.1.tar.gz | tar -xzf -
cd opus-1.2.1
./configure
...
```

**Comment by nurupo** [comment]
Ok, makes sense.

@robinlinden @iphydf sounds like we need to add yet another item to the pre-release check-list. The `tar.gz` and `zip` tarballs in Releases are automatically generated by GitHub, we don't modify them, we just sign them. But apparently it's a good practice to release tarballs with `autogen.sh` already being ran and removed from the source tree. So, before releasing, we'd need to download those `tar.gz` and `zip`, run `autogen.sh` in them, compress them back and replace GitHub's tarballs with ours. Don't forget the signing. Can't you wait to ditch autotools in favor of cmake? : P Though cmake has it's own cons and pros: it's developer-friendly, but not very user-friendly (while I find autotools being the opposite).

**Comment by josuah** [comment]
Thank you for such reactivity.  :)

If the project structure is highly complex (lot of libraries used), if a lot of OS-specific (BSD/linux/... functions) or toolchain-specific (gnu extensions...), the code will not be easily portable, and to fix it easily, the configure script or cmake manages everything for the user: find the path to the OS libraries and set proper compilation flags.

> Though cmake has it's own cons and pros: it's developer-friendly, but not very user-friendly (while I find autotools being the opposite).

That is my impression as well, as with cmake, the user needs to build/install cmake.

As long as the code is written to be portable.  In this case, everything boils down to finding the right location for the libraries and set the `CPPFLAGS` (`-DVERSION=1.2.3`), `CFLAGS` (`-I/path/to/library/include`) and `LDFLAGS` (`-L/path/to/library/lib`).  This is what [ffmpeg](https://github.com/FFmpeg/FFmpeg/blob/master/configure)) does.

Having a configure script already makes packaging/local compilation easy, so running `./autogen.sh` will fix my use case (compiling http://ratox.2f30.org).

Thank you a lot! :)  Do not hesitate to mail me at `echo nbjm@kptvbi.ofu | tr b-za a-z` or ping me on freenode!

**Comment by robinlinden** [comment]
@josuah Happy with release 0.1.10?

**Comment by josuah** [comment]
Sorry for the delayed answer, it compiles like a charm with libsodium!

**Comment by robinlinden** [comment]
Glad we got it sorted. Thank you for opening the issue!
