### ISSUE TITLE
tests fail on openbsd 6.1

### ISSUE THREAD

**Issue by xcko** [TokTok/c-toxcore#570]
No tox instance running.
A few segfaults, followed by timeouts.

[toxcore-test.txt](https://github.com/TokTok/c-toxcore/files/1166985/toxcore-test.txt)

**Comment by nurupo** [comment]
Toxcore having poor BSD support is a known issue. I don't think any of the developers use a BSD system, so it's unlikely this will get fixed any time soon. Especially for OpenBSD. Majority of BSD support that toxcore has comes from contributors who run FreeBSD. There was [some work](https://github.com/TokTok/c-toxcore/pull/424) done on [improving FreeBSD support](https://github.com/TokTok/c-toxcore/pull/473) not that long ago (we are even [setting up FreeBSD CI](https://github.com/TokTok/c-toxcore/pull/505)), but OpenBSD is a quite different beast and FreeBSD fixes don't necessarily apply it.

**Comment by nurupo** [comment]
It would be nice if you could run toxcore in dbg and figure out  why it's crashing, so that we could fix it, or even open a PR fixing it yourself if you feel like it.

**Comment by xcko** [comment]
Running TCP_test through gdb, I discovered that the first failure, "../../build/../auto_tests/TCP_test.c:32:F:basic:test_basic:0: Failed to create TCP relay server"
fails at the c-toxcore/auto_tests/TCP_test.c:31 when calling new_TCP_server.
When trying to continue after this point, the process is killed with a SIGKILL, and I'm not sure why, nor how to debug it further.

**Comment by nurupo** [comment]
Sorry, I have went AFK on IRC and didn't get a chance to reply on your messages. This should be an appropriate place for this.

>\<xcko\> in toxcore/tox.api.h under the Numeric constants section, many values state the units as bytes. I think that's a mistake, and should be bits instead - anyone want to double check?
>\<xcko\> nvm that's too much work for no benefit.

Bytes are the correct units. I'm curious, what made you think that they were supposed to be in bits?

And yes, porting a library to a platform that it doesn't support would require some work, it's not an easy one-line fix.

**Comment by xcko** [comment]
sorry the units were an unrelated issue. I was referring to changing them as not worth the effort. I came to that conclusion based on the return type, eg uint32_t has 32 bits not bytes

**Comment by nurupo** [comment]
That is correct, `uint32_t` is 32 bits or 4 bytes. I'm still confused though, all the units in `tox.api.h` seem to be correct, I don't see why would something about them need change, could you link to the problematic line of code directly?

**Comment by xcko** [comment]
Here is one example c-toxcore/toxcore/tox.h:234,239
/**
 * The size of a Tox Public Key in bytes.
 */
#define TOX_PUBLIC_KEY_SIZE            32

uint32_t tox_public_key_size(void);

Through out that section,  :: Numeric constants, that pattern is repeated.

**Comment by Diadlo** [comment]
@xcko If I understood your question correct, `tox_public_key_size()` will return 32. This value can be placed fine in `uint32_t`

**Comment by xcko** [comment]
right, but 32 bytes can't fit in 32 bits - or am I confused?

**Comment by Diadlo** [comment]
@xcko No, 32 bytes can't fit in 32 bits. But where you get 32 bytes?
Probably, you mixed up with function [tox_self_get_public_key](https://github.com/TokTok/c-toxcore/blob/master/toxcore/tox.h#L1034), which return public key itself

**Comment by xcko** [comment]
The comment specifies the Tox Public Key is in bytes, yet tox_public_key_size returns a type of uint32_t. If the TOX_PUBLIC_KEY_SIZE is 32, that unit (by my understanding) must be bits, so the comment is incorrect.

**Comment by Diadlo** [comment]
@xcko Can we go to IRC?

**Comment by Diadlo** [comment]
@xcko Public key size is 32 bytes, so comment is correct

**Comment by xcko** [comment]
okay I'll look at the code some more and figure out where I went wrong. Thanks for clarifying.

**Comment by xcko** [comment]
It appears that many, if not all of the tests fail from attempting to accept IPv4 and IPv6 traffic on the same socket. Running TCP_test through ktrace, there are many calls to setsockopt that fail with errno 22 - invalid argument. TCP_test includes TCP_server.h, which includes onion.h, which includes DHT.h with includes network.h and in network.c, getsockopt and setsockopt are used.
Quoting from an openbsd man page: 
     For security reasons, OpenBSD does not route IPv4 traffic to an AF_INET6
     socket, and does not support IPv4 mapped addresses, where IPv4 traffic is
     seen as if it comes from an IPv6 address like ::ffff:10.1.1.1.  Where
     both IPv4 and IPv6 traffic need to be accepted, listen on two sockets.

I rebuilt c-toxcore with more logging, test-suite attached. 
 I think TCP_test fails silently as it does not call 
c-toxcore/toxcore/network.c:581
new_networking_ex
which contains the LOG_DEBUG functions.

It seems the errors are handled in other parts of the code, and clients can specify if they want to use IPv4 or IPv6 only. From my basic testing with a tox client, I think toxcore works even though the tests fail.

**Comment by nurupo** [comment]
`tox_public_key_size()` returns the size of the public key in bytes. The size of a public key is always 32 bytes. Number 32 fits into `int32_t`, in 32 bits, just fine. In fact, even `int8_t` would be enough, but we decided to use `int32_t` in the API.

**Comment by nurupo** [comment]
Anyway, it seems that you have some misunderstanding about C language. You don't realize that an int data type is enough to return a size of an array.

**Comment by xcko** [comment]
yes yes, I'm sorry I introduced two discussions in this thread, that was a mistake. For the key sizes, I quickly realized that the values are used for initiallizing byte arrays and so the number itself fits fine in the stated variables, as you pointed out. 

My last comment was concerning the original issue about the tests failing on openbsd. I was never concerned that the variables were causing the failure and I should have opened a new issue for that instead, or just reached out on irc to clarify.

**Comment by iphydf** [comment]
@xcko do tests still fail? How do they fail? Could you join `#toktok` on freenode to help investigate?

**Comment by xcko** [comment]
I have an openbsd 6.3 install, here are the results of building and testing.
libsodium, opus, libvpx, and libconfig are installed.
100 seconds for testing timeout.
DEBUG=ON
TRACE=ON
v0.2.4 of toxcore via git clone ; git checkout v0.2.4
[CMakeCache.txt](https://github.com/TokTok/c-toxcore/files/2244210/CMakeCache.txt)
[build.log](https://github.com/TokTok/c-toxcore/files/2244211/build.log)
[test.log](https://github.com/TokTok/c-toxcore/files/2244274/test.log)
[CTestCostData.txt](https://github.com/TokTok/c-toxcore/files/2244275/CTestCostData.txt)
[LastTest.log](https://github.com/TokTok/c-toxcore/files/2244277/LastTest.log)
[LastTestsFailed.log](https://github.com/TokTok/c-toxcore/files/2244278/LastTestsFailed.log)

**Comment by iphydf** [comment]
Reopen if you have OpenBSD and it's still failing. We have a FreeBSD test running on PRs now.
