### ISSUE TITLE
int32_t may be not large enough as a argument for video_bit_rate of vp8/9 codec

### ISSUE THREAD

**Issue by xhebox** [TokTok/c-toxcore#572]
toxav.h:
```
bool toxav_bit_rate_set(ToxAV *av, uint32_t friend_number, int32_t audio_bit_rate, int32_t video_bit_rate,   TOXAV_ERR_BIT_RATE_SET *error);
```
All the *bit_rate is uint32_t except these two, i think it's a typo, if not, just close the issue :)

EDIT: found when i try to make a go binding.

**Comment by agrecascino** [comment]
@Dako300
?

**Comment by Dako300** [comment]
my bad, you can change that

**Comment by agrecascino** [comment]
ABI breakage?

**Comment by Dako300** [comment]
Nah, implicit casts should handle it fine. It is tested to work in another PR (toxic /bitrate)

**Comment by nurupo** [comment]
@mannol

**Comment by mannol** [comment]
@nurupo @iphydf

**Comment by Dako300** [comment]
It shouldn't be unsigned, since setting to -1 allows for only changing one of the variables.

**Comment by xhebox** [comment]
@Dako300 yeah, but uint32_t has a wider range than int32_t, that's what i am considering, sorry for late explanation:
```
toxav.c:

bool audio_bit_rate_invalid(uint32_t bit_rate)
{
    /* Opus RFC 6716 section-2.1.1 dictates the following:
     * Opus supports all bit rates from 6 kbit/s to 510 kbit/s.
     */
    return bit_rate < 6 || bit_rate > 510;
}
bool video_bit_rate_invalid(uint32_t bit_rate)
{
    (void) bit_rate;
    /* TODO(mannol): If anyone knows the answer to this one please fill it up */
    return false;
}
```

Opus claims the limits of bitrate, according to the discussion between me and 1796(if i recall it correctly) in #Chinese group managed by GroupBot, setting audio_bit_rate to int32_t does not really hurt, since, 2^31/(1024^3) == 2Gbps, this has beyond 510kbit/s much. But we may beyond the limit in case of libvpx:
```
ffmpeg -i output.mp4  -c:v libvpx-vp9 -b:v 4G out.webm
[libvpx-vp9 @ 0x7f6dbe4d1a80] v1.6.1
Output #0, webm, to 'out.webm':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.71.100
    Stream #0:0(und): Video: vp9 (libvpx-vp9), yuv444p, 1024x768, q=-1--1, 4000000 kb/s, 25 fps, 1k tbn, 25 tbc (default)
```

You see, i set bitrates to 4Gbit/s, nothing went wrong. Besides, i've check the code of libvpx by keywords like bit_rates or bitrate..etc.. No codes for limiting the bitrates. we have a risk here, I've changed a proper title.

And yes, my patch made the -1 flag unusable, or at lease inconvenient to use, so:
1. let's break the api, add one more arguments, through a separate flag, we could solve this problem elegantly.
2. let's limit the bitrates to around 2Gbit/s, assume nobody will set such a high bitrate, just add it in video_bit_rate_invalid(), add more warnings in docs.

Which to chose? What rules do i need to follow if i need to break the api? Or simply set a upper limit for video bitrates? Let me know

**Comment by xhebox** [comment]
@Dako300 could someone give me a reply about, how do we deal with '-1' flag? i've gave two options, please check it! :)

**Comment by zoff99** [comment]
vpx clearly defines it as "unsigned int":

https://www.webmproject.org/docs/webm-sdk/structvpx__codec__enc__cfg.html#ab8339685175d66710f482706cc9f0aed

so c-toxcore needs to use a value that can hold this on any system supported.
so maybe use int64_t then?

**Comment by iphydf** [comment]
We can fix the "set only one of them" by splitting the function into two: one for video, one for audio. We're breaking the API for 0.2.0, so we can do this now.

**Comment by nurupo** [comment]
Yes, splitting it into two functions would be better.

**Comment by xhebox** [comment]
@nurupo @iphydf @zoff99 thanks for your replies, guys, :)
I failed to find the specification due to my poor experience, thx, zoff99.
So, i splitted it into set_video() and set_audio(). There was some spelling mistakes, i pushed more than one time. Sorry for my poor english.
