### ISSUE TITLE
Need help in Understanding Toxcore test example.

### ISSUE THREAD

**Issue by blprasad** [TokTok/c-toxcore#579]
Please help in Understanding toxcore
Hi all, I have two basic questions of understanding the working of some test examples.
Q1:
I am trying to run a simple toxcore example test..I am trying with av_test.c from c-toxcore-master/testing/av_test.c ,prior to this I tried to understand the basics of toxcore , I found a pdf explaining simple test program echo_bot.c very well documented.https://wiki.tox.chat/developers/client_examples/echo_bot

I compared echo_bot.c with av_test.c for basic call flow echo_bot document explains that a tox_bootstrap() call is a must to connect to network.But I don't see any such call in av_test.c ,why?!!
I tried to ask the question here because ,I don't know where to ask .

Q2:
Regarding Bootstrap daemon, Is it compulsory to run bootstrap node(i.e., bootstrap daemon)? inorder to make any test example that wants to estabilsh communication with a remote friend, for message sending ,video or audio call using toxcore, 
Thanks in advance

**Comment by zoff99** [comment]
you can have a look at this:
https://github.com/zoff99/ToxCam/tree/master/toxcam

**Comment by nurupo** [comment]
>I compared echo_bot.c with av_test.c for basic call flow echo_bot document explains that a tox_bootstrap() call is a must to connect to network.But I don't see any such call in av_test.c ,why?!!

`av_test` is a program for local testing of toxav, it doesn't connect to the Internet, which is what you's use `tox_bootstrap()` for, instead it runs on localhost. By default, `Tox_Options` has LAN discovery set to enabled, so it automatically connects to the other Tox instances running on the same computer and within the LAN.

>Regarding Bootstrap daemon, Is it compulsory to run bootstrap node(i.e., bootstrap daemon)? inorder to make any test example that wants to estabilsh communication with a remote friend, for message sending ,video or audio call using toxcore,

Running a bootstrap node is optional, if you want to connect to the main Tox network, you can join the network using any of the community-run bootstrap nodes from https://nodes.tox.chat. Also, if your friend is on the same LAN as you, the LAN discovery should work just fine with need to connect to any bootstrap nodes.

**Comment by blprasad** [comment]
I appreciate your inputs
@zoff99 thanks for very useful reference.
I got  more clarity on boostrap node,we don't need to run bootstrap node at toxclient end to operate ,it just only need to connect to atleast any one of the bootstrap nodes that is somewhere in the network.

**Comment by nurupo** [comment]
Security-wise it's better to connect to several different random nodes.

You can read more on [DHT](https://en.wikipedia.org/wiki/Distributed_hash_table), [Kademlia](https://en.wikipedia.org/wiki/Kademlia) and [bootstrap nodes](https://en.wikipedia.org/wiki/Bootstrapping_node) on wiki or other sources.
