### ISSUE TITLE
[INFO]: network graphs 0.1.9 vs 0.1.10

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#584]

**Comment by zoff99** [comment]
![v0 1 9__wlan](https://user-images.githubusercontent.com/6833516/29713281-24fa497c-899e-11e7-9e54-dee422706727.png)

**Comment by zoff99** [comment]
![v0 1 10__wlan](https://user-images.githubusercontent.com/6833516/29713289-2e6615e0-899e-11e7-8150-7691d80436fa.png)

**Comment by nurupo** [comment]
Nice. This is not the final result though, based on what @zurg has said in https://github.com/TokTok/c-toxcore/pull/542, we will start to see the difference once majority of the network switches to 0.1.10, which didn't happen yet.

**Comment by zugz** [comment]
Interesting. Thanks. Was this using UDP or a TCP relay? How many offline 
friends did you have? Is 0m0s when you started up tox in each case?

**Comment by zoff99** [comment]
tcp relay. 4 friends (online)

**Comment by zugz** [comment]
* Saturday, 2017-08-26 at 02:49 -0700 - Zoff <notifications@github.com>:

>tcp relay. 4 friends (online)

OK. If you're using TCP, so not forming part of the onion, it shouldn't 
matter what version other people on the network are using.

But are these graphs from soon after you start tox up? The bandwidth use 
should go down significantly after a few minutes of operation, once 
announce nodes become considered "stable".

**Comment by zoff99** [comment]
about 10 minutes in

**Comment by zoff99** [comment]
anybody with good knowledge about tcp relay code get in touch with me please

**Comment by zugz** [comment]
* Saturday, 2017-08-26 at 10:54 +0000 - Zoff <notifications@github.com>:

>about 10 minutes in

OK, then I believe almost all the traffic you're still seeing in 0.1.10 
should be DHT traffic. I expect that could be reduced quite a bit too.

**Comment by zugz** [comment]
Actually no, I've idea what the traffic is...

**Comment by iphydf** [comment]
@zugz what is the idea?

**Comment by zugz** [comment]
* Tuesday, 2018-01-16 at 11:55 -0800 - iphydf <notifications@github.com>:

>@zugz what is the idea?

That was a typo - I meant "I've no idea what the traffic is"!

That's still the case. But I think we can close this issue.

**Comment by dingosan** [comment]
Whilst this is a great reduction what I don't get is why don't we use a reactive system where a node coming up send an update to all it's contacts and conversely sends a down update to all it's contacts and does no polling other than if it has a message in it's out queue for a node that is not responding.. This would make a seriously large impact to idle traffic and cpu loads. What do you all think? I mean if all the polling is just to let someone know if people at online - which in most case we do not give a hoot about until we want to communicate with them, is a huge waste of data allowance and battery energy. I know that currently there is no outbound  queue but yeah we need it big time.
