### ISSUE TITLE
running a normal tox node as tcp relay is not possible

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#589]
i tried and it did not work. i can't see why. nothing in the logs.
when using bootstapd on the same server that works fine.

did anybody successfully run a normal toxnode as tcp relay?

**Comment by zoff99** [comment]
according to my info this is all you need to activate TCP relay:
https://github.com/zoff99/ToxTCP-RelayNode/blob/master/tox_tcp_relay/tox_tcp_relay.c#L531

**Comment by nurupo** [comment]
1. Do you have the tcp relay option enabled in tox-boostrapd's the configuration file?

2. How do you detect that it's not working?

3. What is the output of `netstat -nltup` when ran as root?

4. Do you have any firewall configured on the machine you run tox-bootstrapd on, potentially locking it? What is the output of `iptables -vL` and `ip6tables -vL`?

**Comment by zoff99** [comment]
@nurupo not tox-boostrapd. tox-boostrapd  is working fine as tcp relay.
but a normal tox node (client) should also work as TCP relay. and that i can not get to work.
so i am wondering: is it really possible to use a regular tox node (client) as tcp relay?
if so: exmaple code? proof?

**Comment by zoff99** [comment]
as stated:
i used this code https://github.com/zoff99/ToxTCP-RelayNode/blob/master/tox_tcp_relay/tox_tcp_relay.c
compiled like this https://circleci.com/gh/zoff99/ToxTCP-RelayNode/26

then used the IP/port and pubkey as a tcp relay in another client. the other client tried to connect but did never go online. there was no useful logging output on both nodes what the problem was

**Comment by zoff99** [comment]
use pubkey from the logout:
```
cd tox_tcp_relay ; cat ./tox_tcp_relay.log

E:TCP relay port: 33447
E:setting UDP mode
D:tox_new2:TOX_ERR_NEW = 0
D:local discovery enabled = 1
D:tox = 0x2340fc0
D:nodeslist:1
I:--MyToxID--:E2373460CC671F7C2A7DD63BB3EB05B9DD8FBEDB9FA517E64B58D0B083BF131BCF354BB62B80
I:avatar_set:001
D:avatar_set:002
D:avatar_set:003
D:avatar_set:004
D:avatar_set:099
I:Tox online, took 9 seconds
I:new Tox AV
I:AV iterate Thread successfully createdI:AV video Thread successfully createdI:av_thread_lock created successfully
I:AV Thread #-1331329280: starting
I:av_thread_lock video created successfully
I:AV video Thread #-1339721984: starting
```
this is just an exmaple log output. not running now!

**Comment by zoff99** [comment]
@nurupo does the TCP relay node need to be in TCP mode? i used UDP mode.
and i saw (with netstat) that is was listening on port 33447

**Comment by nurupo** [comment]
Can you provide a minimal example? 3000 lines of code is a bit too much.

**Comment by zoff99** [comment]
its echobot code basically. i can strip it down. the code works fine as normal node.
has anybody ever used a normal node as tcp realy, is basically what i am asking?

**Comment by nurupo** [comment]
>@nurupo does the TCP relay node need to be in TCP mode?

No, specifying a `tcp_port` in `Tox_Options` should be enough.

**Comment by zoff99** [comment]
hmm. i will make a test setup on CI. to make it reproduceable

**Comment by nurupo** [comment]
Make sure you are using the correct public key when calling `tox_add_tcp_relay()`. It should be the same as your DHT key, which is not exposed through the public API.

**Comment by zoff99** [comment]
tcp        0      0 0.0.0.0:33447           0.0.0.0:*               LISTEN      47007/tox_tcp_relay

**Comment by zoff99** [comment]
what publickey should i use? where do i see it? i only the have normal pubkey of the node.

**Comment by nurupo** [comment]
DHT and TCP server public keys are not exposed in public API. You'd need to dig into toxcore's private internals if you want to access them, similarly to what tox-boostrapd does.

**Comment by zoff99** [comment]
so then my issue is valid.
at the moment it is NOT possible to use a normal tox node as TCP relay (because you are not able to get the needed pubkey)

**Comment by nurupo** [comment]
I don't think it's meant to be used like that. It's true that you can't get DHT and TCP server public key though API, so you can't tell someone to use your node as DHT bootstrap node or TCP relay server. But if you could, it would be very inconvenient, because every time you restart a client, your DHT and TCP server public keys change, so whoever was using you as a DHT or TCP relay server node won't be able to connect anymore. That's why we have a tox-boostrapd, which has unchanging DHT and TCP server keys.

As far as I understand, when you enable a tcp server in a client, all it does is telling other DHT nodes that your node supports TCP relaying, so that they could connect to it if they wanted.

**Comment by nurupo** [comment]
Here is how you could get TCP server public key from toxcore's internals

```
#include <ctype.h>
#include <stdio.h>
#include <stdint.h>

#include <unistd.h>

#include <sodium/utils.h>
#include <tox/tox.h>

#include "toxcore/Messenger.h"
#include "toxcore/TCP_server.h"

void self_connection_status_cb(Tox *tox, TOX_CONNECTION connection_status, void *user_data)
{
    switch (connection_status) {
        case TOX_CONNECTION_NONE:
            printf("Offline\n");
            break;
        case TOX_CONNECTION_TCP:
            printf("Online, using TCP\n");
            break;
        case TOX_CONNECTION_UDP:
            printf("Online, using UDP\n");
            break;
    }
}

void print_bin2hex(const uint8_t *binary, size_t length)
{
    char hex[length*2 + 1];
    sodium_bin2hex(hex, sizeof(hex), binary, length);
    for (size_t i = 0; i < sizeof(hex)-1; i ++) {
        hex[i] = toupper(hex[i]);
    }
    printf("%s\n", hex);
}

int main()
{
    struct Tox_Options options;
    tox_options_default(&options);
    tox_options_set_tcp_port(&options, 4444);

    Tox *tox = tox_new(&options, NULL);

    uint8_t tox_id_bin[TOX_ADDRESS_SIZE];
    tox_self_get_address(tox, tox_id_bin);
    printf("Tox ID: ");
    print_bin2hex(tox_id_bin, sizeof(tox_id_bin));

    printf("TCP server public key: ");
    print_bin2hex(tcp_server_public_key(((Messenger *)tox)->tcp_server), 32);

    tox_callback_self_connection_status(tox, self_connection_status_cb);

    while (1) {
        tox_iterate(tox, NULL);

        usleep(tox_iteration_interval(tox) * 1000);
    }

    tox_kill(tox);

    return 0;
}
```

Save it as `tcp_server.c` in the root of this repository and compile with something like `gcc -o tcp_server tcp_server.c -std=gnu99 -I /usr/local/include/ -lsodium -ltoxnetcrypto -ltoxcore`.

**Comment by zoff99** [comment]
@nurupo
*"As far as I understand, when you enable a tcp server in a client, all it does is telling other DHT nodes that your node supports TCP relaying, so that they could connect to it if they wanted.*"

so is this actually used by and DHT node? or just theory?

**Comment by nurupo** [comment]
I don't know, I'm not familiar with details of how toxcore works and it's spec very much. If you want to know, check the spec.

**Comment by zoff99** [comment]
the spec does not matter. we just proofed it does not work now.

**Comment by nurupo** [comment]
What does not work?

**Comment by zoff99** [comment]
it proofs that you can not run a normal tox node and use that as TCP relay in the settings of your other tox client. but the kind of what the docs suggest.

**Comment by fcore117** [comment]
This feature definitely would give even more power to users of making strong Tox network and new nodes = harder to ban certain IP-s by countries who censor internet. If not by default then maybe global command that can be enabled by passing command to client like --node or something similar for example.

**Comment by nurupo** [comment]
Huh, I'm sorry, apparently I have missed `void tox_self_get_dht_id(const Tox *tox, uint8_t *dht_id);` function in the API, so there is a way to get DHT key from the API. TCP server and DHT keys are the same, so you can use this key for your TCP server needs.
