### ISSUE TITLE
toxencryptsave api info typo?

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#590]
https://github.com/TokTok/c-toxcore/blob/master/toxencryptsave/toxencryptsave.h#L375

is this line correct? or should it say *"If data is NULL, this function returns false."*

**Comment by Diadlo** [comment]
If I understand code correct, it will segfault :/
https://github.com/TokTok/c-toxcore/blob/master/toxencryptsave/toxencryptsave.c#L333

**Comment by zoff99** [comment]
i mean *"cipher text pointer"* does not occur in that function, that is the typo is think.
it should refer to *"data"*
