### ISSUE TITLE
add easy encryption of savedata to toxcore

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#591]
https://github.com/TokTok/c-toxcore/blob/master/toxcore/tox.h#L412

TOX_SAVEDATA_TYPE --> add
TOX_SAVEDATA_TYPE_TOX_SAVE_ENCRYPTED

and make tox_options_get_savedata_data transparently use encryption

**Comment by nurupo** [comment]
Savedata encryption is provided by libtoxencryptsafe, and it is rather simple, just `tox_pass_encrypt()` for encryption and `tox_pass_decrypt()` for decryption.
