### ISSUE TITLE
We hope that Tox can write blog

### ISSUE THREAD

**Issue by abcd99** [TokTok/c-toxcore#600]
Briar has a built-in blog. You can use it to post news and updates about your life. Your blog is automatically shared with your contacts, and their blogs are shared with you. so we hope that Tox can write blog too. Tox's number of users more than 100 million, like WeChat or Skype. In the near future, people are in love with Tox, every day habitual look at friends blog. This will turn the authoritarian state into a country of freedom of expression. For example China, Please help us without freedom of speech,please.

**Comment by hemee** [comment]
Tox still may be blocked because of ToxDNS. And it still cannot keep persistent group chats, so there will not be any telegram-like channels until resolving this issue.

**Comment by SkyzohKey** [comment]
This is out of scope for now. Thus closing.

**Comment by robinlinden** [comment]
@abcd99 It's possible to use Tox as a backend for a blog platform. There has already been a VPN and a filesystem-type client developed and I'm using Tox as a backend for a system that while not a blog makes information available in a similar fashion. This isn't something we're planning on adding to the core at this point though.

**Comment by nurupo** [comment]
@ethylmorphine it sounds like you completely misunderstand what ToxDNS is.
