### ISSUE TITLE
groupId is int whereas friendId is uint32_t, reason?

### ISSUE THREAD

**Issue by sudden6** [TokTok/c-toxcore#606]
In https://github.com/TokTok/c-toxcore/blob/master/toxav/toxav.api.h#L595 the groupId is an `int` whereas throughout the rest of the API friendId's are `uint32_t` like in https://github.com/TokTok/c-toxcore/blob/master/toxcore/tox.h#L1293

I don't think it's of much relevance right now, but is this a mistake? Or am I overlooking special meanings for `groupId < 0`?

**Comment by sudden6** [comment]
@robinlinden would it make sense to add this to the 0.2.0 milestone or will it conflict with #295?

**Comment by robinlinden** [comment]
Don't worry about #295. If it conflicts I'll change it in that PR. We'll put this in 0.2.0.

**Comment by iphydf** [comment]
This is legacy reasons. All numbers used to be signed ints, but we changed it a few years ago in the api redesign. These old groupav functions weren't part of the redesign because they are really strange (they take callbacks but aren't event-like functions).

**Comment by iphydf** [comment]
@sudden6 can you make a PR for this?

**Comment by sudden6** [comment]
to change the type to `uint32_t`?

**Comment by iphydf** [comment]
Yes.
