### ISSUE TITLE
PACKET_LOSSY_AV_RESERVED 8 # why?

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#610]
https://github.com/TokTok/c-toxcore/blob/0542ffa2db75fc6affd1b5c83bcb5af8e7d92c88/toxcore/Messenger.h#L70

why are there 8 packet types reserved for A/V ? are there more than 2 actually used?

**Comment by Diadlo** [comment]
@zoff99 reserved != used. Probably it 8 was used to make protocol compatible, if new AV package will be added

**Comment by zoff99** [comment]
@Diadlo oh i see.
#609 
this should also be changed i think. to make it more clear
