### ISSUE TITLE
core log messages are limited to 1024 bytes

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#614]
https://github.com/TokTok/c-toxcore/blob/master/toxcore/logger.c#L70

**Comment by nurupo** [comment]
It was decided that 1024 bytes for logs is long enough. There was a discussion about it in the PR that introduced this commit https://github.com/TokTok/c-toxcore/pull/46.

**Comment by nurupo** [comment]
Are you hitting the case where 1024 is not enough?

**Comment by zoff99** [comment]
i hit it all the time. the problem is that "FILE" has path information in it.
so depending on what directory you compile in, the path alone can take a lot of chars.
