### ISSUE TITLE
Q: where is the magic byte in video rtp message?

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#618]
in rtp_send_data() the packet type byte comes before the RTPHeader. --> rdata[0]

you can see RTPHeader starts at rdata + 1

https://github.com/TokTok/c-toxcore/blob/2651193b991f4b691aa978b079718606891c6d48/toxav/rtp.c#L122-L132

m_send_custom_lossy_packet also adds a "+1" to the length

https://github.com/TokTok/c-toxcore/blob/2651193b991f4b691aa978b079718606891c6d48/toxav/rtp.c#L166-L167

then on the receiving side in handle_rtp_packet() this byte just dissapeared.
now RTPHeader starts at data[0]

https://github.com/TokTok/c-toxcore/blob/2651193b991f4b691aa978b079718606891c6d48/toxav/rtp.c#L251

what am i missing? where is that byte going

**Comment by zoff99** [comment]
@mannol ? help

**Comment by SkyzohKey** [comment]
@irungentoo @grayhatter @tux3 ^

**Comment by zoff99** [comment]
ok it gets stripped here:

https://github.com/TokTok/c-toxcore/blob/2651193b991f4b691aa978b079718606891c6d48/toxav/rtp.c#L243-L244

thats not good, because further downstream the packet ID is not available any more, and you have to jump trough hoops to save it.

in vc_queue_message() this byte is not available.

**Comment by nurupo** [comment]
@SkyzohKey why did you mark it as Security and Critical? It's neither a security nor a critical issue.

**Comment by SkyzohKey** [comment]
@nurupo Because linked on another issue with BUG inside the title I guess. Maybe I can be wrong because of labeling many issues/PR at the same time, sorry if it isn't nice and feel free to edit :p

**Comment by GrayHatter** [comment]
@zoff99 why do you need access to the packet id number?

**Comment by GrayHatter** [comment]
I ask because it makes me think you're trying to do something magic with a separate packet int, but that's nearly guaranteed to be the wrong solution to the problem.

**Comment by zoff99** [comment]
@GrayHatter it just very strange and confusing. on the sending side you have that byte data[0] and on the receiving side it gets stripped and all you see is starting at data[1] this is unnessecary.
