### ISSUE TITLE
[Feature Reqest] Have an option to NOT send NICK to friends

### ISSUE THREAD

**Issue by physkets** [TokTok/c-toxcore#641]
An additional option for increased privacy would be to not send one's nick to friends. This can have uses where one wants to use different identities with different groups of people.

Say I want to be Mr. A to {B,C,D} and Ms. E to {F,G,H}, I can't do this currently, because the nick I set is sent to friends.

In this scenario, the friend will have to set a nick for me, when we bcome friends, that only they will see.

**Comment by redmanmale** [comment]
You could just use different instances of Tox (with different IDs). It's the simplest way to achive desired behavior.

**Comment by physkets** [comment]
Yes, that is one way, but it would be nice if this were possible without the overhead of running another client, and building this in would improve privacy and anonymity aspects of the protocol, no?

**Comment by stikonas** [comment]
It will improve anonimity, but I think there are probably more urgent fixes/features that need devs attention...

**Comment by sonOfRa** [comment]
This is a bad idea. You still have the same public key, so now you're linking two different identities to *the same public key*. If you want to be Mr. A to {B,C,D}, and Ms. E to {F,G,H}, you must use different public keys for those identities. This is not a problem that should be solved by choosing a nick.

**Comment by physkets** [comment]
@sonOfRa Why is it a bad idea, as long as I understand the level of separation it provides? It is a good idea if groups {B,C,D} and {F,G,H} are always separate. That is a use case.

**Comment by tox-user** [comment]
I think a much better solution would be to be able to run multiple profiles in one window. That way you could have multiple identities and use them for different things without having to open multiple instances. Here is an issue in qTox that explains it and you can even see different UI designs that would allow managing many identities: https://github.com/qTox/qTox/issues/1018

**Comment by physkets** [comment]
Agreed.
