### ISSUE TITLE
[Question] What are the features that need to be worked on first? Try 2

### ISSUE THREAD

**Issue by sudden6** [TokTok/c-toxcore#646]
Since #634 failed because of vote manipulation, we have to try again, this time using only GH stuff.

#### How to vote
- Use the 👍 emoticon on comments to vote for a Topic. Other emoticons on comments will be ignored.
- I'll count the votes in a few days and produce stats.
- Adding new poll options is allowed by starting the comment with `POLL: <Topic>` and a short description will be allowed.
- No discussion allowed to keep this thread clean. Comments not adhering to the rules will be deleted!

**Comment by sudden6** [comment]
POLL: New Groupchats

**Comment by sudden6** [comment]
POLL: Improved Documentation

**Comment by sudden6** [comment]
POLL: Multi devices

**Comment by sudden6** [comment]
POLL: Decentralized Offline Messages

**Comment by sudden6** [comment]
POLL: Decentralized Name Lookup

**Comment by sudden6** [comment]
POLL: Independent Security Audit

**Comment by sudden6** [comment]
POLL: Better File Transfer Support

**Comment by zoff99** [comment]
POLL: sent timestamps in massages

**Comment by zoff99** [comment]
POLL: long term message IDs (to get message receipt even after offline or restart)

**Comment by SlugFiller** [comment]
Hrm, can I add one? How about decentralized account persistence? That is, being able to restore an account using only the private key, or a key-generating memento phrase. It's level of difficulty is similar to offline messages and multi-device combined, since it involves both long-term storage and contact synchronization.

**Comment by iphydf** [comment]
So, multi device wins, and group chats are next. We're already working on group chats, so let's prioritise that.

**Comment by sudden6** [comment]
![spectacle e29798](https://user-images.githubusercontent.com/5585762/35012613-a1cc8c02-fb0a-11e7-873f-b35a4f9d7026.png)

Nice Graphics™

**Comment by iphydf** [comment]
NGC is first. We can re-do this poll at some point when we have at least rough plans for each of the other features, so we know whether it's feasible and how long it takes.
