### ISSUE TITLE
Make audio/video bit rates "properties" with get() instead of manual functions.

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#731]
As outlined in my comment in #578.

**Comment by iphydf** [comment]
@xhebox.

**Comment by xhebox** [comment]
@iphydf let me sleep on it, it's already late night

**Comment by iphydf** [comment]
Sure, no hurry. I've invited you to the org. Once you accept, please assign this issue to yourself.

**Comment by xhebox** [comment]
@iphydf well, i did not find that invitation.. And the original function, how do i do? Add it back in this pr or another pr?

**Comment by iphydf** [comment]
1. I don't think we have a get() right now, so we shouldn't add one. Yes, split into two separate events, but still keep the old one around and call that one as well. Mark the old single one as deprecated.

2. Yes, add the old function back. Also keep the old callback event.

**Comment by zoff99** [comment]
#732

**Comment by xhebox** [comment]
@zoff99 @iphydf OK, for not to waste zoff's work, please merge his code first, i'll open yet another pr to correct name changing and fix the old callbacks.

**Comment by iphydf** [comment]
Sounds good.

**Comment by xhebox** [comment]
this has been done, close it.
