### ISSUE TITLE
Tox needs funding

### ISSUE THREAD

**Issue by tox-user** [TokTok/c-toxcore#738]
The development of Tox is pretty slow. I am talking about toxcore, but also about most clients. There are features that have been requested by users years ago and still nobody is unable to tell when they are going to be finished. Improved group chats, multi device support, offline messaging, sending and receiving messages in order are some of them. Tox also needs a security audit in order to really become secure. I don't know much about them, but I doubt they are cheap.

The project survived all those years, even though there have been difficult problems and sometimes developers were even encouraged by other people to quit. Because of that I doubt Tox is going to die any time soon, but the progress is too slow to reach project's goals in any reasonable amount of time. Finishing those features might take years. Most people that need a safe way to communicate can't afford to wait that long.

One way (maybe the only one) to speed up the development is to get funding. Tox used to be an organisation once and I think it should become one again. People often ask how to donate and giving money to a random developer is not the best solution. Tox needs more developers spending more time on improving it. I understand that there has been a problem with handling money in the past (https://blog.tox.chat/2015/07/current-situation-3), but it's time to move on and try again. Except this time with a new approach that would decrease the possibility of having a single point of failure.

## Organisations that handle money for open source projects
There are non profit organisations that will handle projects' money (for example donation money) and might even use it to pay for some of the expenses (domains, hosting etc.) for the project. Here is one such organisation:
https://sfconservancy.org (https://sfconservancy.org/about)
Some of the projects (https://sfconservancy.org/projects/current) that are using them: coreboot, Etherpad, Git, Inkscape, Samba, Wine and some smaller projects too.

## Join GNU or similar organisation related to free software
I don't know exactly what would the benefits of joining GNU be, but I assume GNU helps with finances and marketing. In exchange they probably demand that the program uses a free software license.

## Other opportunities from being an organisation
- Mozilla gives money to open source projects: https://blog.mozilla.org/blog/2017/10/03/mozilla-awards-half-million-open-source-projects
- Tox could start participating in Google Summer of Code again
- getting donations from users

**Comment by iphydf** [comment]
Really good ideas, thanks! I'll look at all these. I definitely agree.

**Comment by zoff99** [comment]
+1 for GSoC

**Comment by iphydf** [comment]
GSoC is too late now. I proposed it 2 days before the deadline, and the response was "you'd be the only one mentoring". If we have more mentors for TokTok projects by then, we can try next year.

**Comment by SkyzohKey** [comment]
What about a multi-sig bitcoin wallet ? It would allow to get funds avoiding anyone to use the money until others are OK with that too. ;)

**Comment by nurupo** [comment]
@tox-user right, these are the exact thoughts we have had right after that donation mishandeling incident over 2 years ago.

We tried applying to Software Freedom Conservancy and Software in Public Interest, but no one seemed interested in picking us up. SFC replied about a year after our initial request and by that time no one wanted to deal with the legal stuff anymore (zero-one has left our team and he was the one pushing for this the most).

Google has disallowed Tox participation in 2016 GSoC after the 2015's donation incident, and we didn't apply for GSoC in 2017 and 2018 because a lot of developers became less active or left aroud that time, so we were low on people who can be GSoC mentors and their backup mentors. It takes a lot of work and time to be a mentor, you can't just half-ass it or disappear during it, not to mention that mentor's performance affects Tox's ability to participate in the future GSoCs. Also, GSoC gives something like $500/student donation to the org (not to the student's menor, i.e. it's not a personal donation), and it would be problematic to accept that without having a proper non-for-profit org set up.

iphydf wanted to setup a non-for-profit for TokTok last year, not sure what happened to that.

We could try applying to SFC and SIP again, perhaps they are more acceptive now. If we get accepted, we'd need to set up a Tox board for SFC or SIP, deal with legal stuff, decide on how to spend funding, why developer X should receive funding for their work but not developer Y, etc. Not sure if we have enough people who would be willing to take away their time from doing development to deal with this legal stuff instead. It might also require making their personal information public, which not many might be comfortable with. It's worth a try though, I think we should try applying again and then see from there how we should proceed.

**Comment by iphydf** [comment]
TokTok Ltd. is the legal entity owning the non-exclusive right to distribute every TokTok project (except c-toxcore) in their entirety, with all contributions from everyone under GPLv3. This incorporated entity does not own money, servers, data, etc. A not-for-profit, if created, would be a separate entity.

I'm not sure we would be paying developers for their time. Rather, we would use money to pay for external services from people not affiliated with the project.

**Comment by Pigpog** [comment]
> Rather, we would use money to pay for external services from people not affiliated with the project.

such as full security audits

**Comment by MrSorcus** [comment]
What about https://pineapplefund.org/ ?

**Comment by zoff99** [comment]
```
Apply

Applications are now closed for the Pineapple Fund.

Due to a large volume of applications, it may take until the end of January 2018 until we can get back to shortlisted applicants. Thank you for your patience!
```

**Comment by MrSorcus** [comment]
Oh, sad :cry:

**Comment by tox-user** [comment]
We need to have a non-profit first anyway.

**Comment by SlugFiller** [comment]
I'd be willing to throw a few satoshis at a multi-sig. The bigger question is: Will added funding actually help? Is there even a roadmap to using funds to accelerate development? Or is it just some theoretical "If we have money, we can maybe hire someone to do a thing" sort of deal?

**Comment by iphydf** [comment]
It depends on how much money. To really have high velocity, you need either one full time developer (expensive) backed by a slightly larger group of code reviewers and occasional contributors (so they are familiar enough with the code to review), or two devs reviewing each others code (even more expensive). If it's less than that, we need to think what to spend money on. I've been trying to stick with free solutions for infrastructure services, but e.g. I recently got access to a FreeBSD machine and it took me an hour to fix LAN discovery on it, which would have been a several day long task without it. This machine costs money, so that's one way to speed up development with money. The prospect of funding has been theoretical, so it's not been a great use of time to plan the spending of an unknown amount of theoretical money. I'm in favour of doing that, if we set a goal for the amount. Then we can optimise the spending for that amount.

**Comment by Zer0-One** [comment]
Like @nurupo said, SFC actually got back to us, but by then I was just *done*.

I'd be willing to pick up handling of Tox as an "organization" again, but not without some more solid guarantees that the devs actually *want* something that resembles organization. Having to drag along the boring business stuff that no devs want to touch with a 10-foot pole is too tedious.

**Comment by im-grey** [comment]
I talked about this in the groupchat *ages* ago but...bug bounties. Lots of libre software projects just have bug & feature bounties that users contribute to. If someone implements or fixes it, they get the money. Just an idea.

**Comment by zoff99** [comment]
Singal had this bitcoin payout thingy
https://signal.org/blog/bithub/
https://github.com/signalapp/BitHub
which seems to no longer be used (was working wonderful though)

now they have this:
https://freedom.press/crowdfunding/signal/

maybe we can/want deploy bithub (or something similar) ?

**Comment by zoff99** [comment]
https://tip4commit.com/

**Comment by SkyzohKey** [comment]
https://www.opentech.fund

**Comment by Zer0-One** [comment]
@SkyzohKey I reached out to them around the same time as SFC, never received any replies.

**Comment by tox-user** [comment]
What do you think of Freedom of the Press Foundation (https://freedom.press)? They are raising funds for Signal : https://freedom.press/crowdfunding/signal

**Comment by tox-user** [comment]
**I emailed Richard Stallman, the president of the Free Software Foundation and asked him about what it takes to join GNU. Below are my questions and his answers to them.**


  > Could you tell me if it's possible for any free software project to join GNU?

If the program runs on the GNU system and meets our ethical standards,
the program can become part of the GNU Project.  That's done by an
agreement between the leaders of the program's development and the GNU
Project.

  > What are the requirements and how does GNU help its member
  > projects? I couldn't find any information about this online.

Things we can do include:

* Publicize the package.

* Collect donations for the developers to use for the development of
  the package.

* Ask other GNU package developers to make changes to work
  better with this package.  (And vice versa.)

But the GNU Project is NOT simply a league of various packages that
cooperate to gain more success.  When a package is a GNU Package
that means it is a part of a larger project, the GNU Project.


Here's the explanation of what it means for a program to be a GNU
package, which also explains at a general level the responsibilities
of a GNU package maintainer.

GNU is not simply a collection of useful programs.  We started the GNU
Project with a specific overall goal: to create a free software
operating system, the GNU System.  To keep the GNU system technically
coherent, we make sure that the parts fit well together.

Thus, becoming a GNU maintainer is a somewhat formal process, since
affiliating with the GNU project as a maintainer means you must agree to
work (within the confines of the maintenance) with the GNU project's
mission for software freedom.

Here is the basic explanation.

======================================================================
Making a program GNU software means that its developers and the GNU
project agree that "This program is part of the GNU project, released
under the aegis of GNU"--and say so in the program.

The GNU Project appoints package maintainers--initially the main
developers, or those of them who wish to be appointed--to take
responsibility for the package on the behalf of the GNU project.  We
hope it won't happen, but if they step down, we look for other
maintainers.  The program remains a GNU package unless/until the GNU
project decides to drop ties with it.

Being a GNU package means we normally put the program on ftp.gnu.org
(although we can instead refer to your choice of ftp site, as long as
it allows connections from anyone anywhere).

The official site for the GNU package should be on www.gnu.org,
specifically in /software/PROGRAMNAME.  Whenever you give out the URL
for the package home page, you would give this address.  It is ok to
use another site for secondary topics, such as pages meant for people
helping develop the package, and for running data bases.  (We can make
an exception, and put the web pages somewhere else, if there is a
pressing reason.)

It means that the developers agree to pay attention to making the
program work well with the rest of the GNU system--and conversely that
the GNU project will encourage other GNU maintainers to pay attention
to making their programs fit in well with it.

Just what it means to make programs work well together is mainly a
practical matter that depends on what the program does.  But there are
a few general principles.  Certain parts of the GNU coding standards
directly affect the consistency of the whole system.  These include
the standards for configuring and building a program, and the
standards for command-line options.  It is important to make all GNU
programs follow these standards, where they are applicable.

Another important GNU standard is that GNU programs should come with
documentation in Texinfo format.  That is the GNU standard
documentation format, and it can be converted automatically into
various other formats.  You can use DocBook format or another suitable
format for the documentation sources, as long as converting it
automatically into Texinfo gives good results.

If a GNU program wants to be extensible, it should use Guile
(https://www.gnu.org/software/guile/guile.html) as the programming
language for extensibility, if possible.  For some programs there's a
reason to do things differently, but please use Guile if that is
feasible.

A GNU program should use the latest version of the license that the
GNU Project recommends--not just any free software license.  For most
packages, this means releasing under the GNU GPL, "version 3 or later."

A GNU program should not recommend use of any non-free program, and it
should not refer the user to any non-free documentation for free
software.  The campaign for free documentation to go with free
software is a major focus of the GNU project (see
https://www.gnu.org/philosophy/free-doc.html); to show that we are
serious about it, we must not undermine our position by recommending
documentation that isn't free.

Occasionally there are issues of terminology which are important for
the success of the GNU project as a whole.  So we expect maintainers
of GNU programs to follow them.  For example, the documentation files
and comments in the program should speak of GNU/Linux systems, rather
than calling the whole system "Linux", and should use the term "free
software" rather than "open source".  Since a GNU program is released
under the auspices of GNU, it should not say anything that contradicts
the GNU Project's views.

For a program to be GNU software does not require transferring
copyright to the FSF; that is a separate question.  If you transfer
the copyright to the FSF, the FSF will enforce the GPL for the program
if someone violates it; if you keep the copyright, enforcement will be
up to you.

As the GNU maintainer of the package, please make sure to stay in
touch with the GNU Project.  If we come across a problem relating to
the package, we need to tell you about it, and to discuss with you how
to solve it.  Sometimes we will need to ask you to work with other
maintainers to solve a problem that involves using multiple packages
together.  This probably will happen less than once a year, but please
make sure we can contact you in case it does happen.

Finally, if you decide to step down as maintainer at any time, please
inform us (see https://www.gnu.org/prep/maintain/html_node/Stepping-Down.html).

More details are available in these documents:
  Information For Maintainers of GNU Software:
  https://www.gnu.org/prep/maintain/

  GNU Coding Standards:
  https://www.gnu.org/prep/standards/

For the basic ideas of GNU and free software, please read these essays:
  https://www.gnu.org/gnu/the-gnu-project.html
  https://www.gnu.org/philosophy/free-sw.html
  https://www.gnu.org/philosophy/categories.html
  https://www.gnu.org/philosophy/compromise.html
  https://www.gnu.org/philosophy/words-to-avoid.html
  https://www.gnu.org/gnu/linux-and-gnu.html
  https://www.gnu.org/gnu/gnu-linux-faq.html
  https://www.gnu.org/philosophy/open-source-misses-the-point.html

**Comment by SlugFiller** [comment]
@tox-user I'm not too fond of Stallman. His motto is to sacrifice functionality for security. He believes in "free from", not "free to". As I've said above, I'm more than willing to throw some money at the Tox project if the main work is on features rather than patches. I feel like aligning with the GNU project would have the opposite effect.

Tox isn't the only encrypted IM program out there. Just as a random example, I previously used RetroShare and BitMessage. But Tox is the only one that's user friendly, and works out of the box. Tox is the only program that seems to be for users, rather than for hackers and engineers. Let's not lose the thing that makes Tox unique for the sake of funding.

**Comment by tox-user** [comment]
I understand your concern, but making the program less user friendly doesn't seem to be one of the requirements of joining GNU. Tox already is free and always will be (thanks to GPL), so we wouldn't have to do that much. FSF seems to be interested in chat programs that can replace Skype and FaceTime - programs made for normal people, not for hackers:
https://www.fsf.org/campaigns/priority-projects
https://www.fsf.org/campaigns/priority-projects/voicevideochat
They already support at least one messenger https://ring.cx, which looks like a user friendly program to me.

Personally I think that we don't have to join GNU if we can achieve our goals on our own. So far it looks that we can't. If joining GNU ended up hurting the project, we could leave them at any time.

**Comment by tox-user** [comment]
@TokTok/contributors is anyone interested in working on creating an organisation? I'm convinced it would benefit the project in the long run. There are many ways to get funding, but first we need do this first step.

**Comment by sudden6** [comment]
After reading this mail, I'm not to fond of joining GNU. I also don't have a strong motivation to join some other organisation. Mostly because I don't really see how funding could help Tox. If however the project as a whole decides to join such an organisation, I'll not stand in the way.

**Comment by tox-user** [comment]
> I don't really see how funding could help Tox

Here are a few examples:
- hiring developers to work on the project (on new group chats, offline messaging, multidevice, etc.)
- servers, hosting for tox.chat (a proper one - not Github websites with Cloudflare mitm)
- security audits
- bug bounties
- sending developers to conferences to talk about Tox

**Comment by SlugFiller** [comment]
@tox-user I didn't want to say anything until after I've tested ring.cx for myself. Now that I have, I'm even less inclined to the idea of GNU support. I don't know if it was meant to be pre-pre-alpha, but the thing was completely non-functional with nothing resembling status or error reporting. At least the worst I've faced with Tox is one friend who has to constantly fiddle with the IPv6 enable/disable setting. It never brought me to the absurd condition of being able to send messages but not receive them, unlike a certain would-be competitor.

If an umbrella is a must, maybe something along the lines of KDE, which actually have a few usable programs under their belt.

**Comment by tox-user** [comment]
@SlugFiller it's good to know that even despite its problems Tox is better than many other programs :). GNU has a lot of useful programs (they made an operating system...): https://www.gnu.org/software. This issue is about toxcore library, not the clients. As I said their requirements don't have anything to do with what features a program should have or how it should look like. You can disagree with some of the requirements, but just because some GNU program has issues, doesn't mean joining their project would be bad for us. Tox has a lot of problems too.

I don't know if it's possible to join KDE. Since they are a desktop environment, they probably only care about graphical programs? Toxcore has no UI.

We don't have to join any organisation, if we can just create our own and collect donations by ourselves. I'm only asking to do something as soon as possible.

**Comment by yurivict** [comment]
One other area where funding could help is mobile support. Antox on Android is broken, barely usable. And there is no client on iphone at all (?).

**Comment by redmanmale** [comment]
@yurivict for iOS there's an awesome [Antidote](https://github.com/Antidote-for-Tox/Antidote).

**Comment by zoff99** [comment]
@tox-user 

``sending developers to conferences to talk about Tox`` 
what developers would that be? do you have people ready to give talks?
there are talks about Tox all the time.
maybe instead of trolling, you could actually start doing some of the things that you are suggesting?

``is anyone interested in working on creating an organisation?``
there is an organisation already.

**Comment by sudden6** [comment]
>>sending developers to conferences to talk about Tox

>what developers would that be? do you have people ready to give talks?

I agree with @zoff99 here, who would give talks? AFAICT there are enough people that could, but no one that would. Do you want to motivate people with donations?

@zoff99 please stop accusing people, who want to and already do improve stuff, of trolling.

> there is an organisation already.

where? what kind of donations do they accept? what do they do with that money?

**Comment by SkyzohKey** [comment]
@sudden6 TokTok is a Limited organization managed & created by @iphydf. Ask him for more details.

**Comment by zoff99** [comment]
@sudden6 there is a github organisation and there is an actual company.

**Comment by zoff99** [comment]
@sudden6 you are right, so i edited out the bad part

**Comment by tox-user** [comment]
I'm not even going to respond to that poor attempt at a personal attack. Giving talks on conferences is not the main subject of this issue either. Unless you really feel this is something we should discuss here?

As @iphydf has said earlier:
>TokTok Ltd. is the legal entity owning the non-exclusive right to distribute every TokTok project (except c-toxcore) in their entirety, with all contributions from everyone under GPLv3. This incorporated entity does not own money, servers, data, etc. A not-for-profit, if created, would be a separate entity.

**Comment by iphydf** [comment]
No funding of TokTok for now. We're volunteers.
