### ISSUE TITLE
filetransfer only transfers 1 file until finished or paused (not round robin over all pending FTs)

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#763]
https://github.com/TokTok/c-toxcore/blob/fc0cc08b2115d037551369f69519e95e841643aa/toxcore/Messenger.c#L1544

@iphydf i think we need to change this while loop. can you help me here a little bit?

**Comment by sudden6** [comment]
personally I'd prefer to have one finished file instead of a bunch of half finished stuff if the chat contact goes offline. Why do you want to change this behavior?

**Comment by zoff99** [comment]
because now toxcore choses a random FT and finishes that. this FT maybe a very large file.
and other smaller (png, jpeg) will be blocked until this is finished.

i consider this a bug, rather than a feature.
the user should decide how many FTs he will start, not toxcore.

**Comment by tox-user** [comment]
I think it's always better to have one whole file than many broken parts that you can't use. If you get disconnected during a file transfer you will only have to resend that one file, which means less bandwidth wasted and increased chances of receiving a file when you are on a poor connection. If the user is sending multiple files, they should be sent one by one in order and not randomly.

**Comment by anthonybilinski** [comment]
The case zoff99 mentioned is convincing. If you're transferring a huge file to a friend that takes 20 minutes and are chatting at the same time, being able to also send small images that you're chatting about would be nice. Users can already manually accept files or pause if they want to focus the download, and clients could implement queueing of "large" files if wanted, but still allow "small" files or files of certain types to go at the same time.

**Comment by sudden6** [comment]
with the very large file it makes sense 👍

**Comment by zoff99** [comment]
@iphydf @robinlinden isn't this merged already?

**Comment by iphydf** [comment]
Yes that's done by you.
