### ISSUE TITLE
Proposal: TFCL [Tox Friend Capabilities Level]

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#777]
TFCL [Tox Friend Capabilities Level]
 =============

add a number (a bit like Android API Level) to know what capabilites a node (Friend) has.
so clients can react accordingly. (using a newer API, and so on ...)

<BR><BR>
getting the *capabilites_level* for a friend
--

**keep old API function:**
`TOX_CONNECTION tox_friend_get_connection_status(const Tox *tox, uint32_t friend_number, TOX_ERR_FRIEND_QUERY *error);`

and add a new one:
`TOX_CONNECTION tox_friend_get_connection_status_v2(const Tox *tox, uint32_t friend_number, uint32_t *capabilites_level, TOX_ERR_FRIEND_QUERY *error);`

**keep old API function:**
`void tox_callback_friend_connection_status(Tox *tox, tox_friend_connection_status_cb *callback);`

and add a new one:
`void tox_callback_friend_connection_status_v2(Tox *tox, tox_friend_connection_status_cb_v2 *callback);`

**keep old API function:**
`typedef void tox_friend_connection_status_cb(Tox *tox, uint32_t friend_number, TOX_CONNECTION connection_status,
void *user_data);`

and add a new one:
`typedef void tox_friend_connection_status_cb_v2(Tox *tox, uint32_t friend_number, uint32_t capabilites_level, TOX_CONNECTION connection_status,
void *user_data);`

<BR><BR>
getting the *capabilites_level* of own node
--

**at runtime**

add new API function:
`uint32_t tox_self_get_capabilites_level();`

<BR><BR>
**at compile time**

in toxcore/tox.h

`#define TOX_CAPABILITY_LEVEL 3`

<BR><BR>
description of *capabilites_level* value
--

| capabilites_level   | added capabilities     |
| ----------- | ---:|
| 0 |  Tox Base capabilites as of c-toxcore v0.1.11 | 
| 1 |  added Video Fix | 
| 2 |  added MessageV2 capability | 
| 3 |  added persistent Conferences | 
| ... |  ... | 
| ... |  ... |

**Comment by SkyzohKey** [comment]
Nice but this doesn't allow to tell what features every **client** does support. :/

**Comment by zoff99** [comment]
@SkyzohKey ??

**Comment by SkyzohKey** [comment]
What I mean is that clients should be able to know that Bob's client can handle text/action messages, file transfers and avatars, but do not handle inline stuffs, groupchats & stickers. Each client should publish a capabilities packet which makes friend's clients aware of which feature your client does supports. This allows to hide audio/video calls buttons if your friend's client do not have support for that, per exemple.

**Comment by zoff99** [comment]
i don't know. it seems unneeded.
audio and video will just not connect.
there are no stickers and inline stuff.

**Comment by SkyzohKey** [comment]
@zoff99 this is absolutely needed for nice UX. Instead of having the user waiting for a call that will never succeed, we could   display them a message saying that the contact do not supports calls. Or stickers. Or wathever

**Comment by sudden6** [comment]
I think the capabilities should also include the following flags:

- supports audio
- supports video
- supports filetransfer
- supports groups/conferences
