### ISSUE TITLE
LOGGER_ERROR: "Invalid video packet: ..."

### ISSUE THREAD

**Issue by hkarel** [TokTok/c-toxcore#812]
Hi, 
I'm developing a tox client that uses only audio calls. Chat and video calls are not supported. 
After the commit "Improve video key frame sending." (721358208b6650c62aa654be922867f10a5d6f38) in the log was displayed the message: "Invalid video packet: frame offset (0)> = full frame length (0)"
Why does that happen, I don't use video calls at all?

**Comment by sudden6** [comment]
cc @zoff99

**Comment by hkarel** [comment]
Bump!
Dear developers, I ask you to pay attention to this problem. I'm stuck on this issue and can not move on

**Comment by sudden6** [comment]
Does this error cause any problems or is it just the log message?

**Comment by sudden6** [comment]
To me it's still not clear what the actual error is, only the log message?

**Comment by zoff99** [comment]
@iphydf put those into rtp.c

https://github.com/TokTok/c-toxcore/blob/bd62d11860a4e6e540f7116f0ef6c56b28b18837/toxav/rtp.c#L470

i think this is wrong.
on old videp packets both values are "0" so this will always be true i think

**Comment by zoff99** [comment]
also this seems wrong to me:

https://github.com/TokTok/c-toxcore/blob/bd62d11860a4e6e540f7116f0ef6c56b28b18837/toxav/rtp.c#L772

header.flags = RTP_LARGE_FRAME should only be set if session->payload_type is video.
there is a condition on the receiving side, but its still sort of wrong to set this on audio packets

**Comment by hkarel** [comment]
Explanation: I updated toxcore to gitrev bd62d11860a4e6e540f7116f0ef6c56b28b18837. With this toxcore I built  qTox and my tox-client. When making a call to the qTox - I do not see any mistakes in the log of my tox-client.

**Comment by hkarel** [comment]
> header.flags = RTP_LARGE_FRAME should only be set if session->payload_type is video.

How can I test an option without using large frames? 
The matter is that I now test the my tox-client. @Diadlo has kindly agreed to help me with it. We are faced with the problem of the periodic disgusting quality of audio communication. And this does not apply only to my tox-client, a bunch of qTox-qTox works bad too. The sound strongly jingles, no word can be understood. I assume that this may be due to packet loss. Perhaps reducing the size of the transmitted data frames would reduce this problem. In any case, I'm ready to experiment.

**Comment by zoff99** [comment]
@hkarel is your client written in C ?

**Comment by hkarel** [comment]
> @hkarel is your client written in C ?
C++

**Comment by zoff99** [comment]
@hkarel try to build a version with

https://github.com/zoff99/c-toxcore/tree/zoff99/_0.1.10_2017_video_fix_09

to see if your video and audio issues are fixed.
but use this **only for testing**!!! that toxcore version is bleeding edge stuff

**Comment by zoff99** [comment]
@iphydf this is a critical bug i'll fix it tonight.

**Comment by Diadlo** [comment]
@zoff99 I with @hkarel have tested your branch with no effect. You can contact me in tox and we will try to reproduce
