### ISSUE TITLE
FAIL: network_test

### ISSUE THREAD

**Issue by loskiq** [TokTok/c-toxcore#816]
Hi. c-toxcore does not pass the network test.

```=====================================
   tox 0.2.0: build/test-suite.log
=====================================

# TOTAL: 8
# PASS:  7
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: network_test
==================

Running test suite: Network
../auto_tests/network_test.c:85: failed `ip.family == TOX_AF_INET': Expected family TOX_AF_INET (2), got 10.
FAIL network_test (exit status: 1)
```

**Comment by iphydf** [comment]
This probably means your IPv6 setup is non-existent or broken. We'll need to fix this test to be less sensitive to that, but this test does pass if you either disable IPv6 (`cmake -DUSE_IPV6=OFF`) or if your IPv6 setup is working.

**Comment by loskiq** [comment]
@iphydf Thank you! How to disable ipv6 test for `make check`? `make check -DUSE_IPV6=OFF` ?

**Comment by loskiq** [comment]
I added a line `set(USE_IPV6 "OFF")` to CMakeLists.txt, but that did not help me

**Comment by loskiq** [comment]
Solved: I changed 189 line in `confiure.ac` to `if test "$use_ipv6" == "yes"; then` :)
