### ISSUE TITLE
qTox, uTox, toxic fail with 0.2.0

### ISSUE THREAD

**Issue by yurivict** [TokTok/c-toxcore#827]
qTox fails with this error:
```
-- Checking for one of the modules 'libtoxav'
CMake Error at cmake/Dependencies.cmake:73 (message):
  TOXAV package, library or framework not found
```

Is qTox expected to make a release that will be compatible?

**Comment by iphydf** [comment]
Yes. qTox master should [work already](https://github.com/qTox/qTox/blob/master/cmake/Dependencies.cmake#L127).

**Comment by nurupo** [comment]
Toxic should work with 0.2.0, they made a release like ~18 hours ago.

**Comment by yurivict** [comment]
We need to update the FreeBSD ports. Besides the three mentioned here, py-toxcore-c needs to be fixed.

**Comment by iphydf** [comment]
Can you file an issue on py-toxcore-c explaining how to reproduce?
