### ISSUE TITLE
How to get groupchat identifier?

### ISSUE THREAD

**Issue by w3x731** [TokTok/c-toxcore#838]

**Comment by iphydf** [comment]
This is not implemented, yet. #295 will add local identifiers, but you can't use them to join the group chat. New DHT group chats are in the works which will allow that.

**Comment by w3x731** [comment]
Not need join by identifier. Just get 32-byte identifier.
[From here](https://toktok.ltd/spec.html#group)

> To create a group chat the peer will generate a random 32 byte id that will be used to uniquely identify this group chat. 

For friends released function ```tox_friend_get_public_key```, but no analog for group chat.

**Comment by iphydf** [comment]
That will be added soon, probably in 0.2.2. We're releasing 0.2.1 today or tomorrow. The version after that will have a group UID function.
