### ISSUE TITLE
function `cryptpacket_received` seems wrongly implemented 

### ISSUE THREAD

**Issue by hqwrong** [TokTok/c-toxcore#851]
function [cryptpacket_received](https://github.com/TokTok/c-toxcore/blob/master/toxcore/net_crypto.c#L2759) in `net_crypto.c` may wrongly implemented, 

```
int cryptpacket_received(Net_Crypto *c, int crypt_connection_id, uint32_t packet_number)
{
    Crypto_Connection *conn = get_crypto_connection(c, crypt_connection_id);

    if (conn == nullptr) {
        return -1;
    }

    uint32_t num = conn->send_array.buffer_end - conn->send_array.buffer_start;
    uint32_t num1 = packet_number - conn->send_array.buffer_start;

    if (num < num1) {
        return 0;
    }

    return -1;
}
```

since `num < num1` implies `packet_number > conn->send_array.buffer_end`, but when `packet_number` surpassed  `conn->send_array.buffer_end`, I think it's a packet never been sent.

I'll run a test to check later.

**Comment by hqwrong** [comment]
I thought it should be corrected to  `packet_number < conn->send_array.buffer_start`.

but to my surprise, the the original code still works, because that  as `num1` is a `uint32_t` type, it turns out to be a big number when `packet_number < conn->send_array.buffer_start`, and  `num < num1` still holds.

**Comment by sudden6** [comment]
Took a while to figure this out, but it's actually a clever, but of course undocumented (sigh), trick to handle the overflow of the packet number.

```
space of packet_number (reduced for example)
0 1 2 3 4 5 6 7

id's in the buffer are wrapping around
in the buffer are 6, 7 and 0
end = 1
start = 6

id = 7 (in buffer)

num = end - start = 1 - 6 = -5 = 3 (wrap around)
num1 = id - start = 1

num < num1 = false

id = 5 (sent)
num = end - start = 3 (from above)
num1 = id - start = 5 - 6 = -1 = 7 (wrap around)

num < num1 = true
```

The checks for the corner cases are left as an exercise to the reader :P

**Comment by hqwrong** [comment]
thanky you @sudden6 , I've figured it out. It's really a clever trick though

**Comment by iphydf** [comment]
Where is the issue about updating/adding the comments in the code so the next person looking doesn't need to ask the same question?

**Comment by hqwrong** [comment]
@iphydf  is this what you want? #859

**Comment by iphydf** [comment]
@hqwrong yes, thanks. I'll leave the review to @sudden6.
