### ISSUE TITLE
Is tox ready for production or only for testing?

### ISSUE THREAD

**Issue by matteoraggi** [TokTok/c-toxcore#855]
Hi, a friend asked me a solution for videochat and screensharign encrypted, he would use this whitelabel app for work. Can I suggest tox to him or this is not enough stable yet?

**Comment by tox-user** [comment]
It depends on what client you choose. Official desktop clients are pretty stable. I use Tox all the time and it usually works well. I don't know about mobile clients.

**Comment by SkyzohKey** [comment]
You will have to ask the devs of the choosen client. If no one is willing to whitelabel the app, you can always use ToxCore to build yours. I'd be happy to let you use the RicinApp/Ricin source code, but it doesn't supports A/V, so you have to add support for it (and contribute back to the original repo) or use another client (ie. qTox, uTox, Toxygen, etc)

**Comment by iphydf** [comment]
It's as ready as it's likely to get. You can use it. If it doesn't work well, file a bug.
