### ISSUE TITLE
Freenet as Offline Messaging Backend

### ISSUE THREAD

**Issue by HulaHoopWhonix** [TokTok/c-toxcore#86]
In your vision you already recognize the value of Freenet-like systems for the future of the private and secure web: https://toktok.github.io/vision.html

I propose implementing an offline messaging system that relies on offloading messages to Freenet without reinventing the wheel. 

Tox Bootstrap nodes can install Freenet and use its python bindings lib (pyFreenet) to upload/fetch message ciphertext on behalf of peers who could not connect to their contacts.

This will need some way for the Tox DHT to hold an advertisement for offline peers that they have pending messages/files. These advertisement messages will contain the Freenet keys for the uploaded media.

You should probably limit the permitted offline message number (and sizes) so advertisement messages don't get too big. Probably also limit the period you advertise to some number of days to avoid ballooning your DHT and because Freenet inserts are ephemeral and disappear if material is not requested after some time. The size limitation is needed because Freenet inserts take a long time.

When the intended recepient goes online they can ping the Tox DHT for the advertisement and ask for the bootstrap node to fetch them on their behalf - only if the sender is offline, otherwise the fallback to a direct transfer as normally happens.

cc/ @adrelanos

[1] https://github.com/freenet/pyFreenet
[2] https://pypi.python.org/pypi/pyFreenet/0.4.1

**Comment by Renha** [comment]
so if you send message like that, you wouldn't know if it would be delivered or not?

**Comment by HulaHoopWhonix** [comment]
Why's that? If the message receipt feature is available I don't see why a different message storage back-end couldn't work with it.

**Comment by aaannndddyyy** [comment]
I don't think freenet is the right library for that. 
It is not very reliable, and also big.
I would prefer a small custom implementation of offline messages. One where storage nodes need not be friends with the sender, where the network cannot be flooded, where offline messages are still end to end encrypted and storage nodes do not know the fox id's of neither sender nor recipient.
Furthermore, the implementation should be lean and robust, and let the storage node decide how much space it offers

**Comment by HulaHoopWhonix** [comment]
Since I opened the ticket I've taken a look at GNUnet and I think it has a superior design than Freenet. It can also exit traffic to to the internet like Tor and also has decetralized strorage and a set of clean well documented APIs for programs in other languages to interface with it.

The pEp messaging project is bundling it with its client for anonymous messaging. Its a P2P IM project too but optionally interoperates with legacy mail. Instead of long random alphanumeral strings fingerprints are five natural language words used to authenticate contacts out of band.

pep-project.org
prettyeasyprivacy.com

**Comment by iphydf** [comment]
We're not likely to pursue this path. Offline messaging will probably be federated or self-hosted, with possibly very temporary storage in DHT.
