### ISSUE TITLE
Disable the communication with other tox nodes.

### ISSUE THREAD

**Issue by PmAbi1993** [TokTok/c-toxcore#860]
Can we disable our tox server instance connecting to other bootstrap nodes. The bandwidth used by our instances are huge.

**Comment by tox-user** [comment]
I think you want your Tox client to stop connecting to the DHT? You can do that by disabling UDP in you client settings (in qTox it's in advanced tab). It will still connect to the internet, but it will use a TCP relay, which might decrease the network usage.

**Comment by nurupo** [comment]
I don't understand what @PmAbi1993 is asking. What is "tox server instance" and why would preventing it to connect to bootstrap nodes reduce the bandwidth, because that's not how DHT works, this won't reduce any bandwidth.

**Comment by PmAbi1993** [comment]
@nurupo  I have a DHT node in a metered network environment. All my data is being used by this node. Can we disable connections to other nodes so we can reduce the bandwidth used?

**Comment by nurupo** [comment]
There is no option to disable connections.

**Comment by iphydf** [comment]
Connections to other nodes are needed for communication and friend finding. You can use TCP-only mode to reduce traffic.
