### ISSUE TITLE
Building in cygwin

### ISSUE THREAD

**Issue by CardSnap** [TokTok/c-toxcore#880]
```Makefile
[ 78%] Linking C shared library cygtoxcore-2.dll
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: unrecognized option '-z'
/usr/lib/gcc/i686-pc-cygwin/6.4.0/../../../../i686-pc-cygwin/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/toxcore_shared.dir/build.make:928: cygtoxcore-2.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:882: CMakeFiles/toxcore_shared.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```
Cygwin's `ld` doesn't have `-z`. I'm not sure what i need to change to correct or patch this. If anyone can give me a pointer.

building in cygwin 32bit.

**Comment by sudden6** [comment]
This is probably caused by this line: https://github.com/TokTok/c-toxcore/blob/master/CMakeLists.txt#L190

You can remove the option and try if it works. If Cygwin doesn't support that flag a patch preventing it from being enabled is also welcome :)

**Comment by iphydf** [comment]
If anyone wants to build with cygwin and fails, reopen the issue.
