### ISSUE TITLE
Toxcore does not build with cmake on OpenBSD.

### ISSUE THREAD

**Issue by mazocomp** [TokTok/c-toxcore#881]
I've taken a look into toxcore/ccompat.h and this is what worries me:
```
#ifdef _WIN32
#include <malloc.h>
#elif defined(__FreeBSD__)
#include <stdlib.h>
#if !defined(alloca) && defined(__GNUC__)
#define alloca __builtin_alloca
#endif
#else
#include <alloca.h>
#endif
```
As far as I know <alloca.h> is a Linux-specific header (and perhaps also MacOS-specific header). That means toxcore works only at Windows, Linux and FreeBSD...
@iphydf Do you know that alloca(3) and malloc(3) are supposed to be at <stdlib.h> at any OS, including Windows and Linux? So this should work not only for FreeBSD:
```
-#ifdef _WIN32
-#include <malloc.h>
-#elif defined(__FreeBSD__)
 #include <stdlib.h>
 #if !defined(alloca) && defined(__GNUC__)
 #define alloca __builtin_alloca
 #endif
-#else
-#include <alloca.h>
-#endif
```
But quickly patching that doesn't help, I get a spam of undefined references: https://pastebin.com/raw/NbrasTWR
What have you done? You made toxcore completely non portable!

**Comment by endoffile78** [comment]
What operating system are you trying to build toxcore on?

**Comment by mazocomp** [comment]
@endoffile78 OpenBSD

**Comment by endoffile78** [comment]
I just tried on my OpenBSD virtual machine and I get the same thing. I tried both gcc and clang. I'm running OpenBSD 6.3.

**Comment by iphydf** [comment]
If you leave it as is, does it build on OpenBSD? I.e. does removing those lines *cause* the undefined references?

According to which standard is alloca supposed to be available in stdlib.h? It's inherently a non-standard function, neither in any C nor in any POSIX standard document.

On Linux/glibc, if you ask the compiler for C99 compliance, alloca is not available, hence the ifdef mess. Long term, I'd like to get rid of stack allocated buffers or at least allocate the maximum buffer every time (so no VLAs or alloca) so we can calculate the maximum stack depth.

**Comment by mazocomp** [comment]
@iphydf 

First, I don't have <alloca.h> header:
<pre>
test.c:1:10: fatal error: 'alloca.h' file not found
#include <alloca.h>
         ^~~~~~~~~~
1 error generated.
</pre>

Second, leaving it as is does not help to build (it didn't start building toxcore/ccompat.h, but at release 0.2.0 it returned error because toxcore/ccompat.h tryid to include <alloca.h>), still a flood of undefined references: https://pastebin.com/raw/8g9iyw2i

Third, according to man pages at Linux, FreeBSD, NetBSD and OpenBSD alloca() is terrible.

Fourth, it seems that including <stdlib.h> at Linux will work if you don't use -ansi and -std=c* with gcc https://man.openbsd.org/Linux-4.13/alloca#Notes_on_the_GNU_version

**Comment by mazocomp** [comment]
@iphydf If some compilers don't support VLAs, what's wrong with using malloc(3) (or calloc(3)) instead of alloca(3)? Anyway, I am going to make 0.2.2 port.
