### ISSUE TITLE
Feature request: INLINE preview/notification

### ISSUE THREAD

**Issue by fling-** [TokTok/c-toxcore#889]
Files auto-accept technique should be switched with another one for INLINE media.
The user should be able to have auto-accept/preview switch instead.
When the switch is set to preview the receiver should get a blurry thumbnail and a description of the message they are able to receive.
Clicking the thumbnail will tell the sender to send the payload.
This way INLINE media usage will become way much more convenient than with file auto-accept enable/disable setting involved.

File auto-accept should be left for non-inline regular file transfers. It has nothing to do with INLINE images, stickers, voicemail where we can send the thumbnail/notification first.

Enabling auto-accept for INLINE in client will just disable thumbnails and all the INLINE media will be auto accepted which could be a useful for a desktop client where you have fast connection and want to just accept whatever the certain contact sends you.

**Comment by Diadlo** [comment]
See #744

**Comment by zoff99** [comment]
there is no such thing as "INLINE".
thats a clients feature.

**Comment by fling-** [comment]
@zoff99 I thought preview/notification packets should be implemented in core as they are of the different message type. And https://github.com/TokTok/c-toxcore/pull/744 is missing this completely.

**Comment by tox-user** [comment]
What is INLINE?

>the receiver should get a blurry thumbnail and a description of the message they are able to receive.
Clicking the thumbnail will tell the sender to send the payload

qTox does that by default for all file transfers. Other clients have this feature too.

**Comment by iphydf** [comment]
@tox-user does qTox send 2 file transfers for every picture? How do other clients deal with that?

**Comment by tox-user** [comment]
2 file transfers? Why do you think that? I've never noticed it.

**Comment by tox-user** [comment]
>What is INLINE?
```
    the receiver should get a blurry thumbnail and a description of the message they are able to receive.
    Clicking the thumbnail will tell the sender to send the payload
```
qTox does that by default for all file transfers. Other clients have this feature too.

I was wrong. qTox doesn't do that for incoming images. Only for images that we have sent.
