### ISSUE TITLE
Add RTL support for Hebrew and Arabic

### ISSUE THREAD

**Issue by Stamimail** [TokTok/c-toxcore#901]
Flip the chat direction LTR/RTL by:
LeftCtrl + Left Shift = LTR
RightCtrl + RightShift = RTL

**Comment by duffert** [comment]
Honestly this is a usability issue and has nothing to do with the core. I agree, there might be reasoning in providing a text flow direction in the protocol (which to my knowledge can be achieved with enforcing Unicode/UTF-8 encoding).

**Comment by sudden6** [comment]
AFAIK there's no reason RTL or LTR text shouldn't work with Tox in general as Tox only is the transport for UTF-8 text. The specific functionality with the hotkeys must be implemented in the client you use and I suggest to open an issue on their repos.

**Comment by Stamimail** [comment]
I have no clue how to send this request to all Tox based apps.
Do you?

**Comment by sudden6** [comment]
What's the Tox client you have this problem with? For example qTox should render LTR text just fine, it doesn't however have the shortcuts you mentioned.

As for sending the request to all clients, you have to go to each of their issue trackers and open an issue there.

**Comment by Stamimail** [comment]
I'm thinking, it's not only an issue with the GUI of one client.
The side that recive the message, should recived it as LTR or RTL, depends how the sender sent it?

**Comment by Stamimail** [comment]
Test - this text was written in the Right side of this TextBox
First, שני, Third.

**Comment by Stamimail** [comment]
^ This was recived not as I sent it.

**Comment by tox-user** [comment]
I think the flipping should be automatic? What client do you use?

**Comment by tox-user** [comment]
And what client does the other person that you messaged use?

**Comment by nurupo** [comment]
<p dir='rtl' align='right'>It sounds like clients need to insert the RTL or LTR Unicode symbols whenever the keyboard shortcuts OP has mentioned are pressed? Not sure if this the right thing to do though, I mean, how would one re-format the text manually? It's probably unintuitive that they would need to delete an invisible direction-changing symbol for that.</p>
<p dir='rtl' align='right'>This would be hard for clients to add, I don't think there are any client developers experienced with RTL -- how it works and how it's implemented in common software.</p>

**Comment by tox-user** [comment]
>
אני צריך שטקסט כמו זה יהיה מימין לשמאל.
I need text like this will begin in the Right side of the TextBox.

I just pasted it into qTox and it works there. The problem must be with the client that you use. Post an issue in their repository.

![qtox rtl](https://user-images.githubusercontent.com/32248732/41041885-d45cc5bc-698f-11e8-9d32-c8fb97804c3d.png)

**Comment by tox-user** [comment]
This is client related and not an issue in toxcore. Closing.
