### ISSUE TITLE
2 qTox clients see each other online only after a delay of many minutes

### ISSUE THREAD

**Issue by yurivict** [TokTok/c-toxcore#904]
OS: FreeBSD, 11.1 on the desktop amd64 and 12.0 amd64 on the laptop.
qTox is from the FreeBSD port. version is 1.15.0, toxcore version is 0.2.2.

The desktop is static, always in one network, the laptop is moved between networks. After the move both clients are online, show the green color as their status, but see each other online only after a very long delay, usually 10 minutes or much longer, up to an hour.

Restarting qTox on the laptop doesn't help. Restarting qTox on the desktop likely helps.

**Comment by yurivict** [comment]
When I bring this laptop into the same LAN, the account on the laptop still doesn't come online, even though LAN discovery is enabled on both.

**Comment by tox-user** [comment]
Try a little experiment:
launch both clients on both computers at exactly the same time. There can be only a few seconds difference.

See if that makes them discover each other faster. It might be because of a bug that I found in qTox or toxcore some time ago.

**Comment by yurivict** [comment]
When I tried to launch them on the same LAN at the same time, they find each other. But yesterday they also found each other right away when I brought the laptop into that LAN. So the problem is intermittent for LAN.

This is the worst problem with Tox I've seen.

**Comment by tox-user** [comment]
I'm not sure if this is a problem with toxcore or qTox.

**Comment by yurivict** [comment]
I'm not sure either. I'll launch more Tox clients of different kinds under different unix users on the laptop and see if this makes any difference.

**Comment by tox-user** [comment]
Did you find out if it's a toxcore or qTox issue?

**Comment by iphydf** [comment]
Reopen if this is still an issue.
