### ISSUE TITLE
use dll  abnormal  System.AccessViolationException win7 x32 but x64 no problem

### ISSUE THREAD

**Issue by lottery2018** [TokTok/c-toxcore#907]
I'm sure I've made a serious distinction between x32 and x64

After countless attempts, it failed

You can see the two DLLS I use:https://github.com/alexbakker/SharpTox/files/2098274/libtcx.dll.zip

**Comment by lottery2018** [comment]
if i use libtoxcore-toktok_build his dll ,so it's gonna be "Could not create a new instance of tox, error: LoadBadFormat, decrypt error: Ok" ,Even in the case of recreating data

**Comment by iphydf** [comment]
We have tests running on win32 and win64. If this is still a problem, please reopen.
