### ISSUE TITLE
Crash in clear_entry in ping_array.c

### ISSUE THREAD

**Issue by endoffile78** [TokTok/c-toxcore#910]
My tox to irc bridge is getting segfaults in this function, I'm running it with a debug toxcore to get more information, ill update this issue when it crashes.

EDIT: I just got the crash, I got this message:

```
free(): invalid pointer
```

Here is the [Backtrace](https://gist.github.com/endoffile78/9197229404f368fe94247c24171685f9)

**Comment by nurupo** [comment]
Might be related to https://github.com/TokTok/c-toxcore/issues/472.

**Comment by endoffile78** [comment]
I haven't gotten this in a long time after making some changes to my bot, I'm think this was also caused by the memory issues.
