### ISSUE TITLE
Weekly Tox Dev Meeting

### ISSUE THREAD

**Issue by tox-user** [TokTok/c-toxcore#911]
I decided to bring back our old tradition and we will have weekly Tox Dev Meetings again. They will be about anything Tox related. There are always at least a few active toxcore and client developers, so there should always be something to talk about. It can be about our current work or current issues. The meetings will happen on #toktok IRC channel on freenode, at 6pm UTC every saturday. People can also join via Tox, which is recommended :). The first meeting is on 23.06.2018 at 06:00pm UTC.

You can suggest topics for the meeting here: https://github.com/tox-user/tox-dev-meetings/pull/1

**Comment by iphydf** [comment]
Done - we have a meeting.
