### ISSUE TITLE
Crash on malloc in ping_array_add

### ISSUE THREAD

**Issue by endoffile78** [TokTok/c-toxcore#923]
I just got a crash in `ping_array_add` while running my tox to IRC bridge. Error message:

```
_int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)` failed. 
```

[Backtrace](https://gist.github.com/endoffile78/8209c0914251095bd22f61fe4b9ed0bf)

**Comment by nurupo** [comment]
Possibly related crashes from the same module https://github.com/TokTok/c-toxcore/issues/910 https://github.com/TokTok/c-toxcore/issues/472

**Comment by nurupo** [comment]
From some googling it sounds like your machine might be simply running out of memory.

**Comment by endoffile78** [comment]
It was a memory issue, I'll close this.

**Comment by nurupo** [comment]
Are you sure? I wasn't certain about it, I was just taking a guess.

**Comment by endoffile78** [comment]
I'm pretty sure, after making some changes to how much memory is allocated these errors stopped so I'm pretty sure my vps was just running out of memory.
