### ISSUE TITLE
Help needed in testing a tox client,I need some dummy toxids to test .

### ISSUE THREAD

**Issue by blprasad** [TokTok/c-toxcore#936]
Though it's not a real issue. I am seeking help here because, I don't know where to seek.
I am experimenting with toxic client. I am trying to add few Tox Id's to my client for testing.I just want to show them in a menu in contacts list. How and where do I get some dummy tox Ids for testing.
I only got two machines on which I run a toxic client on each, these two client's Ids are only added to each other.If I want to add more Tox Ids on each of them how do I do that? I want to show some dummy ids and their corresponding names in a menu.As I could not get more tox Ids I cannot test the menu.

Thanks in advance

**Comment by iphydf** [comment]
You can start multiple toxes on one machine. You can also use tox-testbot (https://github.com/tox-user/tox-testbot). Run it with `testbot.py -b 10` to spawn 10 test bots you can add. They will start doing random things, but you can remove the code that does that if you don't need it.

**Comment by blprasad** [comment]
iphydf, thanks for input

**Comment by blprasad** [comment]
If I try running multiple instances of toxic client , I am getting same tox Id on both the instances.
But I need different tox Ids. I still need to look at testbot.py and how it works.

**Comment by blprasad** [comment]
I tried with some of the Public Keys from https://nodes.tox.chat/  as friend tox Ids . I don't get any error message while adding these.But they are not adding to my friends list. Are these Public Keys any different from tox Ids. I mean can I use them as tox Ids?

**Comment by blprasad** [comment]
I am facing problem while running tesbot.py , I think I need to run PyTox before I start testbot.py. I am facing problem in running PyTox ,because docker is not supported on my 32 bit system.

**Comment by iphydf** [comment]
You can build pytox from source without docker. Let me know if you run into problems trying to build it.

https://github.com/TokTok/py-toxcore-c

**Comment by tox-user** [comment]
If I remember correctly I was able to build pytox with:
```
python setup.py build
```

Then you can go to `build/lib.linux-x86_64-2.7` then copy `pytox.so` and paste it into testbot's directory.

I just added a new `-e` parameter to testbot that allows you to specify your Tox ID that bots will add. Example:
```
testbot.py -b 10 -e YOUR_TOX_ID_HERE
```

**Comment by blprasad** [comment]
It's not working for me,it's throwing headers missing error .I am thinking alternative.
I tried to compile qtox, that also has dependencies to be installed.For now I am getting some tox IDs by installing tox on my mobile devices.Closing it for now please keep suggesting.🙂

**Comment by nurupo** [comment]
```C
#include <stdio.h>
#include <string.h>
#include <ctype.h>

#include <sodium.h>

int main()
{
    unsigned char public_key[crypto_box_PUBLICKEYBYTES];
    unsigned char secret_key[crypto_box_SECRETKEYBYTES];
    crypto_box_keypair(public_key, secret_key);

    char tox_file[] = "\x00\x00\x00\x00\x1f\x1b\xed\x15\x44\x00\x00\x00\x01\x00\xce\x01\x00\x00\x00\x00";
    fwrite(tox_file, sizeof(tox_file) - 1, 1, stderr);
    fwrite(public_key, sizeof(public_key), 1, stderr);
    fwrite(secret_key, sizeof(secret_key), 1, stderr);

    char public_key_str[crypto_box_PUBLICKEYBYTES*2 + 1];
    char secret_key_str[crypto_box_SECRETKEYBYTES*2 + 1];
    sodium_bin2hex(public_key_str, sizeof(public_key_str), public_key, sizeof(public_key));
    sodium_bin2hex(secret_key_str, sizeof(secret_key_str), secret_key, sizeof(secret_key));
    for (size_t i = 0; i < sizeof(public_key_str); i ++) {
        public_key_str[i] = toupper(public_key_str[i]);
        secret_key_str[i] = toupper(secret_key_str[i]);
    }
    fprintf(stdout, "Public key: %s\n", public_key_str);
    fprintf(stdout, "Secret key: %s\n", secret_key_str);

    unsigned char checksum[2] = {0};
    for (size_t i = 0; i < crypto_box_PUBLICKEYBYTES; i ++) {
        checksum[i % 2] ^= public_key[i];
    }
    char checksum_str[sizeof(checksum)*2 + 1];
    sodium_bin2hex(checksum_str, sizeof(checksum_str), checksum, sizeof(checksum));
    for (size_t i = 0; i < sizeof(checksum_str); i ++) {
        checksum_str[i] = toupper(checksum_str[i]);
    }
    fprintf(stdout, "Tox Id: %s00000000%s\n", public_key_str, checksum_str);

    return 0;
}
```

```bash
$ gcc -o generate_keypair generate_keypair.c -lsodium -std=c99
$ ./generate_keypair >info 2>tox_savedata
$ cat info 
Public key: 5724FCBEFAA0ECFC9877E7058DF91A03FAF68AF42854446C3D454B4BE0C9386E
Secret key: 170A7606A074205E438DA7FAE70EAAD465483A6EC781DEB096A45ACA83FCDBFF
Tox Id: 5724FCBEFAA0ECFC9877E7058DF91A03FAF68AF42854446C3D454B4BE0C9386E00000000E7DD
$ xxd tox_savedata 
00000000: 0000 0000 1f1b ed15 4400 0000 0100 ce01  ........D.......
00000010: 0000 0000 5724 fcbe faa0 ecfc 9877 e705  ....W$.......w..
00000020: 8df9 1a03 faf6 8af4 2854 446c 3d45 4b4b  ........(TDl=EKK
00000030: e0c9 386e 170a 7606 a074 205e 438d a7fa  ..8n..v..t ^C...
00000040: e70e aad4 6548 3a6e c781 deb0 96a4 5aca  ....eH:n......Z.
00000050: 83fc dbff                          
```

**Comment by blprasad** [comment]
@nurupo
thanks for the input and effort. It is what I needed.It's working as expected.
