### ISSUE TITLE
Persistent groups don't work properly when using toxync bot

### ISSUE THREAD

**Issue by tox-user** [TokTok/c-toxcore#960]
**Reproducible:** always

**Steps:**
1. Install toxcore with persistent group chats.
2. Join a toxync (96BE12EB9AF2F6851704412FA2981E03E32BBD18D40F6040D01F107A20CACC07639D8D4F2A94) group, for example #qtox: `join #qtox`).
3. Make sure toxync is your only friend in that group.
4. Toxync will autoinvite you by default, which would make this test irrelevant. To disable autoinvite type: `leave #qtox`.
5. Exit Tox without leaving the group.
6. Start Tox again.

**Observed behaviour:**
Tox doesn't rejoin a toxync group. When you then request an invite by using `join #qtox` command, it will get automatically accepted - Tox will join the group without asking for permission. This only happens in toxync groups.

**Expected behaviour:**
Rejoin feature should work for all groups. Don't join groups without permission.

**Notes:**
- without step 3, you might get an automatic invite from your other friends, instead from toxync (even if they don't have a toxcore with persistent groupchats), which will most likely work, but the purpouse of this test is to show that it doesn't work with toxync
- step 4 is necessary, because toxync by default keeps sending you group invites to all groups that you've joined. That makes it impossibleto test persistent group's auto rejoin feature
- toxync often loses connection. Because it doesn't use persistent groups, it must create all of its groups again after it reconnects. It could be possible that we don't get reconnected to its group, because it no longer exists (toxync lost connection). If that was true, this problem would only be reproducible after toxync loses connection at least once, so it wouldn't be reproducible always

**Comment by envsh** [comment]
toxync author here. Put some note about toxync, not sure it related. Hope help if related.
1. toxync use toxcore 0.2.2, static linked.
2. **!!!** toxync will mannually reset group's internel identifier field after created(for fake persistent group identifier).
this is how do that(demo): 
```
    groupNumber = t.ConferenceNew()
    groupId := xtox.ConferenceNameToIdentifier(channel.Name)
    xtox.ConferenceSetIdentifier(t, groupNumber, groupId)
```
Set identifier is right after group created. No any code between that. https://github.com/envsh/matterbridge/blob/withtox-ups1.11/bridge/tox/tox.go#L246
The group id is name's sha256, 32 bytes long.
ConferenceSetIdentifier directly copy the 32 bytes to Group_c's identifier field,  https://github.com/envsh/go-toxcore/blob/master/xtox/group_intern.c#L264.

**Comment by tox-user** [comment]
@envsh toxync is using modified toxcore? Did I understand that correctly?

**Comment by envsh** [comment]
Not modified the toxcore's code. 
It's runtime modify memory pointer to Group_c struct.

**Comment by sudden6** [comment]
@envsh Isn't that basically the same? you effectively change the behaviour of toxcore

**Comment by iphydf** [comment]
Closing because we got rid of the old PGC PR.
