### ISSUE TITLE
Merge the two travis stages for freebsd back into one

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#982]
With parallel tests, we now seem to be well within the travis timeout, even without cache. We can now get rid of stages and just run all the builds in a single stage.

**Comment by nurupo** [comment]
@iphydf [it exceeded the time limit when I put them together](https://travis-ci.org/TokTok/c-toxcore/jobs/401406528).

**Comment by iphydf** [comment]
Too bad. We'll need to keep it staged then.
