### ISSUE TITLE
Registration on https://nodes.tox.chat (question)

### ISSUE THREAD

**Issue by hkarel** [TokTok/c-toxcore#988]
Hi, 
I have an easy home server, my tox-client are always working on it. The server has public dynamic IP (have a domain name). 
I wanted to ask: can my tox- client act as a bootstrap-node? If YES, how can I register it on https://nodes.tox.chat? 
Or for this purpose need a special bootstrap-client?

**Comment by tox-user** [comment]
There is some information here: https://wiki.tox.chat/users/runningnodes

To add your node to the list you might need to use this mailing list: https://lists.tox.chat/listinfo/bootstrap

**Comment by nurupo** [comment]
Regular tox clients change their DHT key after they are restarted, so it's probably a bad fit for being a bootstrap node.

**Comment by hkarel** [comment]
Ok, understood. I will establish the separate bootstrap-client.
Thanks.
